
#include "libccc/../../src/monad/array/arrnew.c"
#include "libccc/../../src/monad/array/arrdel.c"
#include "libccc/../../src/monad/array/arrdup.c"
#include "libccc/../../src/monad/array/arrget.c"
#include "libccc/../../src/monad/array/arrset.c"
#include "libccc/../../src/monad/array/arrcpy.c"
#include "libccc/../../src/monad/array/arrsub.c"
#include "libccc/../../src/monad/array/arrappend.c"
#include "libccc/../../src/monad/array/arrprepend.c"
#include "libccc/../../src/monad/array/arrinsert.c"
#include "libccc/../../src/monad/array/arrremove.c"
#include "libccc/../../src/monad/array/arrreplace.c"
#include "libccc/../../src/monad/array/arrequ.c"
#include "libccc/../../src/monad/array/arrcmp.c"
#include "libccc/../../src/monad/array/arriter.c"
#include "libccc/../../src/monad/array/arrmap.c"
#include "libccc/../../src/monad/array/arrfilt.c"
