#!/bin/sh

  IO_RESET="\033[0m"
    IO_RED="\033[0;31m"
  IO_GREEN="\033[0;32m"
 IO_YELLOW="\033[0;33m"
   IO_BLUE="\033[0;34m"
IO_MAGENTA="\033[0;35m"
   IO_CYAN="\033[0;36m"

# get commit hashes from stdin
while read line
do
	LINE=${line}
done
OLD=`echo $LINE | cut -d ' ' -f 4`
NEW=`echo $LINE | cut -d ' ' -f 2`
printf "old commit: $OLD\n"
printf "new commit: $NEW\n"

# get list of files with changes between the OLD and NEW commits
FILES=`git diff $OLD..$NEW --name-only` # | awk '{ print "\"" $0 "\"" } ' | tr '\n' ' '`
printf "Files changed:$C_CYAN\n$FILES\n$C_RESET"

# TODO: run code style formatter ?

exit 0
