#!/bin/sh

#! utility variables for terminal colored output
ansi_esc() { printf "\033[""$@""m" ; }
IO_RESET="`   ansi_esc 0`"
IO_RED="`     ansi_esc 31`"
IO_GREEN="`   ansi_esc 32`"
IO_YELLOW="`  ansi_esc 33`"
IO_BLUE="`    ansi_esc 34`"
IO_MAGENTA="` ansi_esc 35`"
IO_CYAN="`    ansi_esc 36`"



# get commit hashes from stdin
while read line
do
	LINE=${line}
done
OLD=`echo $LINE | cut -d ' ' -f 4`
NEW=`echo $LINE | cut -d ' ' -f 2`
printf "old commit: $OLD\n"
printf "new commit: $NEW\n"

# get list of files with changes between the OLD and NEW commits
FILES=`git diff $OLD..$NEW --name-only` # | awk '{ print "\"" $0 "\"" } ' | tr '\n' ' '`
printf "Files changed:$IO_CYAN\n$FILES\n$IO_RESET"

# TODO: run code style formatter ?

exit 0
