
#include "libccc.h"
#include "libccc/fixed.h"
#include "libccc/string.h"
#include "libccc/math.h"
#include "libccc/math/float.h"

#include LIBCONFIG_ERROR_INCLUDE



#define DEFINEFUNC_FIXED_FROM(BITS) \
t_q##BITS	Q##BITS##_From( \
	t_s##BITS numerator, \
	t_s##BITS denominator) \
{ \
	if CCCERROR((denominator == 0), ERROR_MATHDOMAIN, \
		"fraction denominator should never be zero") \
		return (Q##BITS##_ERROR); \
	if (denominator == Q##BITS##_DENOM) \
		return (t_q##BITS){ numerator }; \
	return (t_q##BITS){ (t_s##BITS)((numerator * Q##BITS##_DENOM) / denominator) }; \
} \

DEFINEFUNC_FIXED_FROM(8)
DEFINEFUNC_FIXED_FROM(16)
DEFINEFUNC_FIXED_FROM(32)
DEFINEFUNC_FIXED_FROM(64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_FIXED_FROM(128)
#endif



#define DEFINEFUNC_FIXED_FROMUINT(BITS, FROM) \
t_q##BITS	Q##BITS##_FromU##FROM(t_u##FROM number) \
{ \
	if (U##FROM##_IsNaN(number))	return (Q##BITS##_ERROR); \
	if (U##FROM##_IsInf(number))	return (Q##BITS##_MAX); \
	t_u##BITS result = (number * Q##BITS##_DENOM); \
	if CCCERROR((result < number), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point positive overflow for " SF_U##FROM " at " SF_Q##BITS, number, Q##BITS##_MAX) \
		return (Q##BITS##_MAX); \
	return ((t_q##BITS){ (t_s##BITS)(result) }); \
} \

DEFINEFUNC_FIXED_FROMUINT(8, 8)
DEFINEFUNC_FIXED_FROMUINT(8, 16)
DEFINEFUNC_FIXED_FROMUINT(8, 32)
DEFINEFUNC_FIXED_FROMUINT(8, 64)
DEFINEFUNC_FIXED_FROMUINT(16, 8)
DEFINEFUNC_FIXED_FROMUINT(16, 16)
DEFINEFUNC_FIXED_FROMUINT(16, 32)
DEFINEFUNC_FIXED_FROMUINT(16, 64)
DEFINEFUNC_FIXED_FROMUINT(32, 8)
DEFINEFUNC_FIXED_FROMUINT(32, 16)
DEFINEFUNC_FIXED_FROMUINT(32, 32)
DEFINEFUNC_FIXED_FROMUINT(32, 64)
DEFINEFUNC_FIXED_FROMUINT(64, 8)
DEFINEFUNC_FIXED_FROMUINT(64, 16)
DEFINEFUNC_FIXED_FROMUINT(64, 32)
DEFINEFUNC_FIXED_FROMUINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_FIXED_FROMUINT(8, 128)
DEFINEFUNC_FIXED_FROMUINT(16, 128)
DEFINEFUNC_FIXED_FROMUINT(32, 128)
DEFINEFUNC_FIXED_FROMUINT(64, 128)
DEFINEFUNC_FIXED_FROMUINT(128, 8)
DEFINEFUNC_FIXED_FROMUINT(128, 16)
DEFINEFUNC_FIXED_FROMUINT(128, 32)
DEFINEFUNC_FIXED_FROMUINT(128, 64)
DEFINEFUNC_FIXED_FROMUINT(128, 128)
#endif



#define DEFINEFUNC_FIXED_FROMSINT(BITS, FROM) \
t_q##BITS	Q##BITS##_FromS##FROM(t_s##FROM number) \
{ \
	if (S##FROM##_IsNaN(number))	return (Q##BITS##_ERROR); \
	if (S##FROM##_IsInf(number))	return ((number < 0) ? Q##BITS##_MIN : Q##BITS##_MAX); \
	t_s##BITS result = (number * Q##BITS##_DENOM); \
	if CCCERROR((S##BITS##_Abs(result) < S##FROM##_Abs(number)), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point %s overflow for " SF_U##FROM " at " SF_Q##BITS, \
		((number < 0) ? "negative" : "positive"), number, Q##BITS##_MAX) \
		return ((number < 0) ? Q##BITS##_MIN : Q##BITS##_MAX); \
	return ((t_q##BITS){ (t_s##BITS)result }); \
} \

DEFINEFUNC_FIXED_FROMSINT(8, 8)
DEFINEFUNC_FIXED_FROMSINT(8, 16)
DEFINEFUNC_FIXED_FROMSINT(8, 32)
DEFINEFUNC_FIXED_FROMSINT(8, 64)
DEFINEFUNC_FIXED_FROMSINT(16, 8)
DEFINEFUNC_FIXED_FROMSINT(16, 16)
DEFINEFUNC_FIXED_FROMSINT(16, 32)
DEFINEFUNC_FIXED_FROMSINT(16, 64)
DEFINEFUNC_FIXED_FROMSINT(32, 8)
DEFINEFUNC_FIXED_FROMSINT(32, 16)
DEFINEFUNC_FIXED_FROMSINT(32, 32)
DEFINEFUNC_FIXED_FROMSINT(32, 64)
DEFINEFUNC_FIXED_FROMSINT(64, 8)
DEFINEFUNC_FIXED_FROMSINT(64, 16)
DEFINEFUNC_FIXED_FROMSINT(64, 32)
DEFINEFUNC_FIXED_FROMSINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_FIXED_FROMSINT(8, 128)
DEFINEFUNC_FIXED_FROMSINT(16, 128)
DEFINEFUNC_FIXED_FROMSINT(32, 128)
DEFINEFUNC_FIXED_FROMSINT(64, 128)
DEFINEFUNC_FIXED_FROMSINT(128, 8)
DEFINEFUNC_FIXED_FROMSINT(128, 16)
DEFINEFUNC_FIXED_FROMSINT(128, 32)
DEFINEFUNC_FIXED_FROMSINT(128, 64)
DEFINEFUNC_FIXED_FROMSINT(128, 128)
#endif



#define DEFINEFUNC_FIXED_FROMFIXED(BITS, FROM) \
t_q##BITS	Q##BITS##_FromQ##FROM(t_q##FROM number) \
{ \
	if (Q##FROM##_IsNaN(number))	return (Q##BITS##_ERROR); \
	if (Q##FROM##_IsInf(number))	return ((number._ < 0) ? Q##BITS##_MIN : Q##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number._ >= (t_s##FROM)Q##BITS##_MAX._), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point positive overflow for " SF_Q##FROM " at " SF_Q##BITS, number._, Q##BITS##_MAX._) \
		return (Q##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number._ <= (t_s##FROM)Q##BITS##_MIN._), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point negative overflow for " SF_Q##FROM " at " SF_Q##BITS, number._, Q##BITS##_MIN._) \
		return (Q##BITS##_MIN); \
	return ((t_q##BITS){ (t_s##BITS)number._ }); \
} \

DEFINEFUNC_FIXED_FROMFIXED(8, 8)
DEFINEFUNC_FIXED_FROMFIXED(8, 16)
DEFINEFUNC_FIXED_FROMFIXED(8, 32)
DEFINEFUNC_FIXED_FROMFIXED(8, 64)
DEFINEFUNC_FIXED_FROMFIXED(16, 8)
DEFINEFUNC_FIXED_FROMFIXED(16, 16)
DEFINEFUNC_FIXED_FROMFIXED(16, 32)
DEFINEFUNC_FIXED_FROMFIXED(16, 64)
DEFINEFUNC_FIXED_FROMFIXED(32, 8)
DEFINEFUNC_FIXED_FROMFIXED(32, 16)
DEFINEFUNC_FIXED_FROMFIXED(32, 32)
DEFINEFUNC_FIXED_FROMFIXED(32, 64)
DEFINEFUNC_FIXED_FROMFIXED(64, 8)
DEFINEFUNC_FIXED_FROMFIXED(64, 16)
DEFINEFUNC_FIXED_FROMFIXED(64, 32)
DEFINEFUNC_FIXED_FROMFIXED(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_FIXED_FROMFIXED(8, 128)
DEFINEFUNC_FIXED_FROMFIXED(16, 128)
DEFINEFUNC_FIXED_FROMFIXED(32, 128)
DEFINEFUNC_FIXED_FROMFIXED(64, 128)
DEFINEFUNC_FIXED_FROMFIXED(128, 8)
DEFINEFUNC_FIXED_FROMFIXED(128, 16)
DEFINEFUNC_FIXED_FROMFIXED(128, 32)
DEFINEFUNC_FIXED_FROMFIXED(128, 64)
DEFINEFUNC_FIXED_FROMFIXED(128, 128)
#endif



#define DEFINEFUNC_FIXED_FROMFLOAT(BITS, FROM) \
t_q##BITS	Q##BITS##_FromF##FROM(t_f##FROM number) \
{ \
	if (F##FROM##_IsNaN(number))	return (Q##BITS##_ERROR); \
	if (F##FROM##_IsInf(number))	return ((number < 0) ? Q##BITS##_MIN : Q##BITS##_MAX); \
	if CCCERROR((number > F##FROM##_FromQ##BITS(Q##BITS##_MAX_VAL)), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point positive overflow for " SF_F##FROM " at " SF_Q##BITS, number, Q##BITS##_MAX) \
		return (Q##BITS##_MAX); \
	if CCCERROR((number < F##FROM##_FromQ##BITS(Q##BITS##_MIN_VAL)), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point negative overflow for " SF_F##FROM " at " SF_Q##BITS, number, Q##BITS##_MIN) \
		return (Q##BITS##_MIN); \
	if CCCERROR((number != 0.) && (F##FROM##_Abs(number) < 1. / Q##BITS##_DENOM), ERROR_RESULTRANGE, \
		#BITS"-bit fixed-point %s underflow for " SF_F##FROM, ((number < 0) ? "negative" : "positive"), number) \
		return ((t_q##BITS){ 0 }); \
	return ((t_q##BITS) \
	{	(t_s##BITS)( \
		(t_s##BITS)(F##FROM##_Trunc(number) * Q##BITS##_DENOM) + \
		(t_s##BITS)(F##FROM##_Mod(number, 1) * Q##BITS##_DENOM)) \
	}); \
} \

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_FIXED_FROMFLOAT(8, 16)
#endif
DEFINEFUNC_FIXED_FROMFLOAT(8, 32)

DEFINEFUNC_FIXED_FROMFLOAT(8, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_FIXED_FROMFLOAT(8, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_FIXED_FROMFLOAT(8, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_FIXED_FROMFLOAT(16, 16)
#endif
DEFINEFUNC_FIXED_FROMFLOAT(16, 32)

DEFINEFUNC_FIXED_FROMFLOAT(16, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_FIXED_FROMFLOAT(16, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_FIXED_FROMFLOAT(16, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_FIXED_FROMFLOAT(32, 16)
#endif
DEFINEFUNC_FIXED_FROMFLOAT(32, 32)

DEFINEFUNC_FIXED_FROMFLOAT(32, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_FIXED_FROMFLOAT(32, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_FIXED_FROMFLOAT(32, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_FIXED_FROMFLOAT(64, 16)
#endif
DEFINEFUNC_FIXED_FROMFLOAT(64, 32)

DEFINEFUNC_FIXED_FROMFLOAT(64, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_FIXED_FROMFLOAT(64, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_FIXED_FROMFLOAT(64, 128)
#endif

#if LIBCONFIG_USE_INT128
#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_FIXED_FROMFLOAT(128, 16)
#endif
DEFINEFUNC_FIXED_FROMFLOAT(128, 32)

DEFINEFUNC_FIXED_FROMFLOAT(128, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_FIXED_FROMFLOAT(128, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_FIXED_FROMFLOAT(128, 128)
#endif
#endif
