// This is a generated source file: see ./make/rules/test-simple.mk for more info

#include <libccc.h>
#include <libccc/bool.h>
#include <libccc/char.h>
#include <libccc/color.h>
#include <libccc/encode/common.h>
#include <libccc/encode/json.h>
#include <libccc/encode/toml.h>
#include <libccc/error.h>
#include <libccc/fixed.h>
#include <libccc/float.h>
#include <libccc/format.h>
#include <libccc/int.h>
#include <libccc/math/algebra.h>
#include <libccc/math/algebra/interval.h>
#include <libccc/math/algebra/matrix.h>
#include <libccc/math/algebra/vector.h>
#include <libccc/math/complex.h>
#include <libccc/math/constants.h>
#include <libccc/math/fixed.h>
#include <libccc/math/float.h>
#include <libccc/math/int.h>
#include <libccc/math/math.h>
#include <libccc/math/sort.h>
#include <libccc/math/stat.h>
#include <libccc/math/vlq.h>
#include <libccc/memory.h>
#include <libccc/monad/array.c>
#include <libccc/monad/dict.c>
#include <libccc/monad/hashmap.c>
#include <libccc/monad/list.c>
#include <libccc/monad/queue.c>
#include <libccc/monad/stack.c>
#include <libccc/monad/tree.c>
#include <libccc/pointer.h>
#include <libccc/pointerarray.h>
#include <libccc/random/csprng.h>
#include <libccc/random/prng.h>
#include <libccc/random/random.h>
#include <libccc/string.h>
#include <libccc/stringarray.h>
#include <libccc/sys/ansi.h>
#include <libccc/sys/io.h>
#include <libccc/sys/logger.h>
#include <libccc/sys/program.h>
#include <libccc/sys/time.h>
#include <libccc/text/ascii.h>
#include <libccc/text/regex.h>
#include <libccc/text/unicode.h>
#include <libccc_config.h>
#include <libccc_define.h>
#include <libccc_errors.h>
#include <libccc_naming.h>
#define T_TYPE	t_sint
#define T_NAME	int
#define T_NULL	0
#include <libccc/monad/array.c>
#define T_TYPE	t_float
#define T_NAME	float
#define T_NULL	0.0
#include <libccc/monad/array.c>

int main()
{
	t_char*              var_0001 = Bool_ToString                 (0, 0);
	t_size               var_0002 = Bool_Parse                    (NULL, NULL);
	t_bool               var_0003 = Bool_FromString               (NULL);
	t_u8                 var_0004 = Color_ARGB16_Get_A            (0);
	t_u8                 var_0005 = Color_ARGB16_Get_R            (0);
	t_u8                 var_0006 = Color_ARGB16_Get_G            (0);
	t_u8                 var_0007 = Color_ARGB16_Get_B            (0);
	t_argb16             var_0008 = Color_ARGB16_Set              (0, 0, 0, 0);
	t_argb16             var_0009 = Color_ARGB16_Set_A            (0, 0);
	t_argb16             var_0010 = Color_ARGB16_Set_R            (0, 0);
	t_argb16             var_0011 = Color_ARGB16_Set_G            (0, 0);
	t_argb16             var_0012 = Color_ARGB16_Set_B            (0, 0);
	t_argb32             var_0013 = Color_ARGB16_To_ARGB32        (0);
	s_argb               var_0014 = Color_ARGB16_To_ARGB          (0);
	t_u16                var_0015 = Color_ARGB16_Difference       (0, 0);
	t_argb16 const*      var_0016 = Color_ARGB16_GetNearest       (0, NULL, 0);
	t_u8                 var_0017 = Color_ARGB32_Get_A            (0);
	t_u8                 var_0018 = Color_ARGB32_Get_R            (0);
	t_u8                 var_0019 = Color_ARGB32_Get_G            (0);
	t_u8                 var_0020 = Color_ARGB32_Get_B            (0);
	t_argb32             var_0021 = Color_ARGB32_Set              (0, 0, 0, 0);
	t_argb32             var_0022 = Color_ARGB32_Set_A            (0, 0);
	t_argb32             var_0023 = Color_ARGB32_Set_R            (0, 0);
	t_argb32             var_0024 = Color_ARGB32_Set_G            (0, 0);
	t_argb32             var_0025 = Color_ARGB32_Set_B            (0, 0);
	t_argb16             var_0026 = Color_ARGB32_To_ARGB16        (0);
	s_argb               var_0027 = Color_ARGB32_To_ARGB          (0);
	t_u32                var_0028 = Color_ARGB32_Difference       (0, 0);
	t_argb32 const*      var_0029 = Color_ARGB32_GetNearest       (0, NULL, 0);
	s_argb               var_0030 = Color_ARGB_Set                (0, 0, 0, 0);
	                                Color_ARGB_Set_A              (NULL, 0);
	                                Color_ARGB_Set_R              (NULL, 0);
	                                Color_ARGB_Set_G              (NULL, 0);
	                                Color_ARGB_Set_B              (NULL, 0);
	t_argb16             var_0035 = Color_ARGB_To_ARGB16          (NULL);
	t_argb32             var_0036 = Color_ARGB_To_ARGB32          (NULL);
	s_ahsl               var_0037 = Color_ARGB_To_AHSL            (NULL);
	s_argb const*        var_0038 = Color_ARGB_GetNearest         ((s_argb){0}, NULL, 0);
	s_ahsl               var_0039 = Color_AHSL_Set                (0, 0, 0, 0);
	                                Color_AHSL_Set_A              (NULL, 0);
	                                Color_AHSL_Set_H              (NULL, 0);
	                                Color_AHSL_Set_S              (NULL, 0);
	                                Color_AHSL_Set_L              (NULL, 0);
	s_argb               var_0044 = Color_AHSL_To_ARGB            (NULL);
	s_ahsl const*        var_0045 = Color_AHSL_GetNearest         ((s_ahsl){0}, NULL, 0);
	                                KVT_Print_UpdateOffset        (NULL);
	t_utf8*              var_0047 = KVT_Print_EnsureBuffer        (NULL, 0);
	s_kvt*               var_0048 = KVT_Item                      ();
	s_kvt*               var_0049 = KVT_Duplicate                 (NULL, 0);
	t_bool               var_0050 = KVT_Equals                    (NULL, NULL, 0);
	s_kvt*               var_0051 = KVT_CreateNull                ();
	s_kvt*               var_0052 = KVT_CreateBoolean             (0);
	s_kvt*               var_0053 = KVT_CreateInteger             (0);
	s_kvt*               var_0054 = KVT_CreateFloat               (0);
	s_kvt*               var_0055 = KVT_CreateString              (NULL);
	s_kvt*               var_0056 = KVT_CreateArray               ();
	s_kvt*               var_0057 = KVT_CreateObject              ();
	s_kvt*               var_0058 = KVT_CreateRaw                 (NULL);
	s_kvt*               var_0059 = KVT_CreateStringReference     (NULL);
	s_kvt*               var_0060 = KVT_CreateArrayReference      (NULL);
	s_kvt*               var_0061 = KVT_CreateObjectReference     (NULL);
	s_kvt*               var_0062 = KVT_CreateArray_Boolean       (NULL, 0);
	s_kvt*               var_0063 = KVT_CreateArray_UInt          (NULL, 0);
	s_kvt*               var_0064 = KVT_CreateArray_U8            (NULL, 0);
	s_kvt*               var_0065 = KVT_CreateArray_U16           (NULL, 0);
	s_kvt*               var_0066 = KVT_CreateArray_U32           (NULL, 0);
	s_kvt*               var_0067 = KVT_CreateArray_U64           (NULL, 0);
	s_kvt*               var_0068 = KVT_CreateArray_SInt          (NULL, 0);
	s_kvt*               var_0069 = KVT_CreateArray_S8            (NULL, 0);
	s_kvt*               var_0070 = KVT_CreateArray_S16           (NULL, 0);
	s_kvt*               var_0071 = KVT_CreateArray_S32           (NULL, 0);
	s_kvt*               var_0072 = KVT_CreateArray_S64           (NULL, 0);
	s_kvt*               var_0073 = KVT_CreateArray_Float         (NULL, 0);
	s_kvt*               var_0074 = KVT_CreateArray_F32           (NULL, 0);
	s_kvt*               var_0075 = KVT_CreateArray_F64           (NULL, 0);
	s_kvt*               var_0076 = KVT_CreateArray_F80           (NULL, 0);
	s_kvt*               var_0077 = KVT_CreateArray_String        (NULL, 0);
	t_sint               var_0078 = KVT_GetArrayLength            (NULL);
	s_kvt*               var_0079 = KVT_GetArrayItem              (NULL, 0);
	t_bool               var_0080 = KVT_GetValue_Boolean          (NULL);
	t_s64                var_0081 = KVT_GetValue_Integer          (NULL);
	t_f64                var_0082 = KVT_GetValue_Float            (NULL);
	t_char*              var_0083 = KVT_GetValue_String           (NULL);
	e_cccerror           var_0084 = KVT_SetValue_Boolean          (NULL, 0);
	e_cccerror           var_0085 = KVT_SetValue_Integer          (NULL, 0);
	e_cccerror           var_0086 = KVT_SetValue_Float            (NULL, 0);
	e_cccerror           var_0087 = KVT_SetValue_String           (NULL, NULL);
	e_cccerror           var_0088 = KVT_AddToArray_Item           (NULL, NULL);
	e_cccerror           var_0089 = KVT_AddToArray_ItemReference  (NULL, NULL);
	e_cccerror           var_0090 = KVT_AddToObject_Item          (NULL, NULL, NULL);
	e_cccerror           var_0091 = KVT_AddToObject_ItemReference (NULL, NULL, NULL);
	s_kvt*               var_0092 = KVT_AddToObject_Null          (NULL, NULL);
	s_kvt*               var_0093 = KVT_AddToObject_Boolean       (NULL, NULL, 0);
	s_kvt*               var_0094 = KVT_AddToObject_Integer       (NULL, NULL, 0);
	s_kvt*               var_0095 = KVT_AddToObject_Float         (NULL, NULL, 0);
	s_kvt*               var_0096 = KVT_AddToObject_String        (NULL, NULL, NULL);
	s_kvt*               var_0097 = KVT_AddToObject_Object        (NULL, NULL);
	s_kvt*               var_0098 = KVT_AddToObject_Array         (NULL, NULL);
	s_kvt*               var_0099 = KVT_AddToObject_Raw           (NULL, NULL, NULL);
	t_bool               var_0100 = KVT_IsInvalid                 (NULL);
	t_bool               var_0101 = KVT_IsNull                    (NULL);
	t_bool               var_0102 = KVT_IsBoolean                 (NULL);
	t_bool               var_0103 = KVT_IsInteger                 (NULL);
	t_bool               var_0104 = KVT_IsFloat                   (NULL);
	t_bool               var_0105 = KVT_IsString                  (NULL);
	t_bool               var_0106 = KVT_IsArray                   (NULL);
	t_bool               var_0107 = KVT_IsObject                  (NULL);
	t_bool               var_0108 = KVT_IsRaw                     (NULL);
	e_cccerror           var_0109 = KVT_Delete                    (NULL);
	s_kvt*               var_0110 = KVT_Detach                    (NULL, NULL);
	e_cccerror           var_0111 = KVT_Replace                   (NULL, NULL, NULL);
	e_cccerror           var_0112 = KVT_Delete_FromArray          (NULL, 0);
	s_kvt*               var_0113 = KVT_Detach_FromArray          (NULL, 0);
	e_cccerror           var_0114 = KVT_Replace_InArray           (NULL, 0, NULL);
	e_cccerror           var_0115 = KVT_Insert_InArray            (NULL, 0, NULL);
	s_kvt*               var_0116 = KVT_Concat                    (NULL, NULL);
	s_kvt*               var_0117 = KVT_Concat_Array              (NULL, NULL);
	s_kvt*               var_0118 = KVT_Concat_Object             (NULL, NULL);
	s_kvt*               var_0119 = KVT_Merge                     (NULL, NULL, 0);
	t_size               var_0120 = JSON_Parse_Lenient            (NULL, NULL, 0);
	s_json*              var_0121 = JSON_FromString_Lenient       (NULL);
	t_size               var_0122 = JSON_Parse_Strict             (NULL, NULL, 0);
	s_json*              var_0123 = JSON_FromString_Strict        (NULL);
	t_size               var_0124 = JSON_Print_Pretty             (NULL, NULL, 0);
	t_utf8*              var_0125 = JSON_ToString_Pretty          (NULL);
	t_size               var_0126 = JSON_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0127 = JSON_ToString_Minify          (NULL);
	t_size               var_0128 = TOML_Parse_Lenient            (NULL, NULL, 0);
	s_toml*              var_0129 = TOML_FromString_Lenient       (NULL);
	t_size               var_0130 = TOML_Parse_Strict             (NULL, NULL, 0);
	s_toml*              var_0131 = TOML_FromString_Strict        (NULL);
	t_size               var_0132 = TOML_Print_Pretty             (NULL, NULL, 0);
	t_size               var_0133 = TOML_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0134 = TOML_ToString_Pretty          (NULL);
	t_utf8*              var_0135 = TOML_ToString_Minify          (NULL);
	t_char*              var_0136 = Error_STDC                    (0);
	e_cccerror           var_0137 = Error_Get                     ();
	e_cccerror           var_0138 = Error_Set                     (0);
	t_char*              var_0139 = Error_GetMessage              (0);
	t_char*              var_0140 = Error_GetName                 (0);
	e_cccerror           var_0141 = Error_GetCode                 (NULL);
	                                Error_Handle                  (0, NULL, NULL);
	                                Error_Handler                 (0, NULL);
	f_ccchandler         var_0144 = Error_GetHandler              (0);
	                                Error_SetHandler              (0, 0);
	                                Error_SetAllHandlers          (0);
	t_q16                var_0147 = Q16_FromInt                   (0);
	t_q32                var_0148 = Q32_FromInt                   (0);
	t_q64                var_0149 = Q64_FromInt                   (0);
	t_q16                var_0150 = Q16_FromFixed                 (0);
	t_q32                var_0151 = Q32_FromFixed                 (0);
	t_q64                var_0152 = Q64_FromFixed                 (0);
	t_q16                var_0153 = Q16_FromFloat                 (0);
	t_q32                var_0154 = Q32_FromFloat                 (0);
	t_q64                var_0155 = Q64_FromFloat                 (0);
	t_q16                var_0156 = Q16_From                      (0, 0);
	t_q32                var_0157 = Q32_From                      (0, 0);
	t_q64                var_0158 = Q64_From                      (0, 0);
	t_s16                var_0159 = Q16_IntegerPart               (0);
	t_s32                var_0160 = Q32_IntegerPart               (0);
	t_s64                var_0161 = Q64_IntegerPart               (0);
	t_s16                var_0162 = Q16_FractionPart              (0);
	t_s32                var_0163 = Q32_FractionPart              (0);
	t_s64                var_0164 = Q64_FractionPart              (0);
	t_size               var_0165 = Q16_Parse                     (NULL, NULL, 0);
	t_size               var_0166 = Q32_Parse                     (NULL, NULL, 0);
	t_size               var_0167 = Q64_Parse                     (NULL, NULL, 0);
	t_size               var_0168 = Q16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0169 = Q32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0170 = Q64_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0171 = Q16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0172 = Q32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0173 = Q64_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0174 = Q16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0175 = Q32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0176 = Q64_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0177 = Q16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0178 = Q32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0179 = Q64_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0180 = Q16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0181 = Q32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0182 = Q64_Parse_Base                (NULL, NULL, NULL, 0);
	t_f32                var_0183 = F32_FromInt                   (0);
	t_f64                var_0184 = F64_FromInt                   (0);
	t_f80                var_0185 = F80_FromInt                   (0);
	t_f32                var_0186 = F32_FromFixed                 (0);
	t_f64                var_0187 = F64_FromFixed                 (0);
	t_f80                var_0188 = F80_FromFixed                 (0);
	t_f32                var_0189 = F32_FromFloat                 (0);
	t_f64                var_0190 = F64_FromFloat                 (0);
	t_f80                var_0191 = F80_FromFloat                 (0);
	t_f32                var_0192 = F32_From                      (0, 0);
	t_f64                var_0193 = F64_From                      (0, 0);
	t_f80                var_0194 = F80_From                      (0, 0);
	t_sint               var_0195 = F32_GetExp2                   (0);
	t_sint               var_0196 = F64_GetExp2                   (0);
	t_sint               var_0197 = F80_GetExp2                   (0);
	t_sint               var_0198 = F32_GetExp10                  (0);
	t_sint               var_0199 = F64_GetExp10                  (0);
	t_sint               var_0200 = F80_GetExp10                  (0);
	t_char*              var_0201 = F32_ToString                  (0, 0);
	t_char*              var_0202 = F64_ToString                  (0, 0);
	t_char*              var_0203 = F80_ToString                  (0, 0);
	t_char*              var_0204 = F32_ToString_Exp              (0, 0);
	t_char*              var_0205 = F64_ToString_Exp              (0, 0);
	t_char*              var_0206 = F80_ToString_Exp              (0, 0);
	t_char*              var_0207 = F32_ToString_Dec              (0, 0);
	t_char*              var_0208 = F64_ToString_Dec              (0, 0);
	t_char*              var_0209 = F80_ToString_Dec              (0, 0);
	t_char*              var_0210 = F32_ToString_Hex              (0, 0);
	t_char*              var_0211 = F64_ToString_Hex              (0, 0);
	t_char*              var_0212 = F80_ToString_Hex              (0, 0);
	t_char*              var_0213 = F32_ToString_Bin              (0, 0);
	t_char*              var_0214 = F64_ToString_Bin              (0, 0);
	t_char*              var_0215 = F80_ToString_Bin              (0, 0);
	t_size               var_0216 = F32_Parse                     (NULL, NULL, 0);
	t_size               var_0217 = F64_Parse                     (NULL, NULL, 0);
	t_size               var_0218 = F80_Parse                     (NULL, NULL, 0);
	t_f32                var_0219 = F32_FromString                (NULL);
	t_f64                var_0220 = F64_FromString                (NULL);
	t_f80                var_0221 = F80_FromString                (NULL);
	t_size               var_0222 = F32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0223 = F64_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0224 = F80_Parse_Dec                 (NULL, NULL, 0);
	t_f32                var_0225 = F32_FromString_Dec            (NULL);
	t_f64                var_0226 = F64_FromString_Dec            (NULL);
	t_f80                var_0227 = F80_FromString_Dec            (NULL);
	t_size               var_0228 = F32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0229 = F64_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0230 = F80_Parse_Hex                 (NULL, NULL, 0);
	t_f32                var_0231 = F32_FromString_Hex            (NULL);
	t_f64                var_0232 = F64_FromString_Hex            (NULL);
	t_f80                var_0233 = F80_FromString_Hex            (NULL);
	t_size               var_0234 = F32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0235 = F64_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0236 = F80_Parse_Oct                 (NULL, NULL, 0);
	t_f32                var_0237 = F32_FromString_Oct            (NULL);
	t_f64                var_0238 = F64_FromString_Oct            (NULL);
	t_f80                var_0239 = F80_FromString_Oct            (NULL);
	t_size               var_0240 = F32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0241 = F64_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0242 = F80_Parse_Bin                 (NULL, NULL, 0);
	t_f32                var_0243 = F32_FromString_Bin            (NULL);
	t_f64                var_0244 = F64_FromString_Bin            (NULL);
	t_f80                var_0245 = F80_FromString_Bin            (NULL);
	t_char*              var_0246 = String_Format                 (NULL);
	t_char*              var_0247 = String_Format_VA              (NULL, 0);
	t_size               var_0248 = String_Format_N               (NULL, 0, NULL);
	t_size               var_0249 = String_Format_N_VA            (NULL, 0, NULL, 0);
	t_char*              var_0250 = U8_ToString                   (0);
	t_char*              var_0251 = U16_ToString                  (0);
	t_char*              var_0252 = U32_ToString                  (0);
	t_char*              var_0253 = U64_ToString                  (0);
	t_char*              var_0254 = S8_ToString                   (0);
	t_char*              var_0255 = S16_ToString                  (0);
	t_char*              var_0256 = S32_ToString                  (0);
	t_char*              var_0257 = S64_ToString                  (0);
	t_char*              var_0258 = S8_ToString_Dec               (0);
	t_char*              var_0259 = S16_ToString_Dec              (0);
	t_char*              var_0260 = S32_ToString_Dec              (0);
	t_char*              var_0261 = S64_ToString_Dec              (0);
	t_char*              var_0262 = U8_ToString_Hex               (0, 0);
	t_char*              var_0263 = U16_ToString_Hex              (0, 0);
	t_char*              var_0264 = U32_ToString_Hex              (0, 0);
	t_char*              var_0265 = U64_ToString_Hex              (0, 0);
	t_char*              var_0266 = S8_ToString_Hex               (0, 0);
	t_char*              var_0267 = S16_ToString_Hex              (0, 0);
	t_char*              var_0268 = S32_ToString_Hex              (0, 0);
	t_char*              var_0269 = S64_ToString_Hex              (0, 0);
	t_char*              var_0270 = U8_ToString_Oct               (0, 0);
	t_char*              var_0271 = U16_ToString_Oct              (0, 0);
	t_char*              var_0272 = U32_ToString_Oct              (0, 0);
	t_char*              var_0273 = U64_ToString_Oct              (0, 0);
	t_char*              var_0274 = S8_ToString_Oct               (0, 0);
	t_char*              var_0275 = S16_ToString_Oct              (0, 0);
	t_char*              var_0276 = S32_ToString_Oct              (0, 0);
	t_char*              var_0277 = S64_ToString_Oct              (0, 0);
	t_char*              var_0278 = U8_ToString_Bin               (0, 0);
	t_char*              var_0279 = U16_ToString_Bin              (0, 0);
	t_char*              var_0280 = U32_ToString_Bin              (0, 0);
	t_char*              var_0281 = U64_ToString_Bin              (0, 0);
	t_char*              var_0282 = S8_ToString_Bin               (0, 0);
	t_char*              var_0283 = S16_ToString_Bin              (0, 0);
	t_char*              var_0284 = S32_ToString_Bin              (0, 0);
	t_char*              var_0285 = S64_ToString_Bin              (0, 0);
	t_char*              var_0286 = U8_ToString_Base              (0, NULL);
	t_char*              var_0287 = U16_ToString_Base             (0, NULL);
	t_char*              var_0288 = U32_ToString_Base             (0, NULL);
	t_char*              var_0289 = U64_ToString_Base             (0, NULL);
	t_char*              var_0290 = S8_ToString_Base              (0, NULL);
	t_char*              var_0291 = S16_ToString_Base             (0, NULL);
	t_char*              var_0292 = S32_ToString_Base             (0, NULL);
	t_char*              var_0293 = S64_ToString_Base             (0, NULL);
	t_size               var_0294 = U8_Parse                      (NULL, NULL, 0);
	t_size               var_0295 = U16_Parse                     (NULL, NULL, 0);
	t_size               var_0296 = U32_Parse                     (NULL, NULL, 0);
	t_size               var_0297 = U64_Parse                     (NULL, NULL, 0);
	t_u8                 var_0298 = U8_FromString                 (NULL);
	t_u16                var_0299 = U16_FromString                (NULL);
	t_u32                var_0300 = U32_FromString                (NULL);
	t_u64                var_0301 = U64_FromString                (NULL);
	t_size               var_0302 = S8_Parse                      (NULL, NULL, 0);
	t_size               var_0303 = S16_Parse                     (NULL, NULL, 0);
	t_size               var_0304 = S32_Parse                     (NULL, NULL, 0);
	t_size               var_0305 = S64_Parse                     (NULL, NULL, 0);
	t_s8                 var_0306 = S8_FromString                 (NULL);
	t_s16                var_0307 = S16_FromString                (NULL);
	t_s32                var_0308 = S32_FromString                (NULL);
	t_s64                var_0309 = S64_FromString                (NULL);
	t_size               var_0310 = U8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0311 = U16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0312 = U32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0313 = U64_Parse_Dec                 (NULL, NULL, 0);
	t_u8                 var_0314 = U8_FromString_Dec             (NULL);
	t_u16                var_0315 = U16_FromString_Dec            (NULL);
	t_u32                var_0316 = U32_FromString_Dec            (NULL);
	t_u64                var_0317 = U64_FromString_Dec            (NULL);
	t_size               var_0318 = S8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0319 = S16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0320 = S32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0321 = S64_Parse_Dec                 (NULL, NULL, 0);
	t_s8                 var_0322 = S8_FromString_Dec             (NULL);
	t_s16                var_0323 = S16_FromString_Dec            (NULL);
	t_s32                var_0324 = S32_FromString_Dec            (NULL);
	t_s64                var_0325 = S64_FromString_Dec            (NULL);
	t_size               var_0326 = U8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0327 = U16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0328 = U32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0329 = U64_Parse_Hex                 (NULL, NULL, 0);
	t_u8                 var_0330 = U8_FromString_Hex             (NULL);
	t_u16                var_0331 = U16_FromString_Hex            (NULL);
	t_u32                var_0332 = U32_FromString_Hex            (NULL);
	t_u64                var_0333 = U64_FromString_Hex            (NULL);
	t_size               var_0334 = S8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0335 = S16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0336 = S32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0337 = S64_Parse_Hex                 (NULL, NULL, 0);
	t_s8                 var_0338 = S8_FromString_Hex             (NULL);
	t_s16                var_0339 = S16_FromString_Hex            (NULL);
	t_s32                var_0340 = S32_FromString_Hex            (NULL);
	t_s64                var_0341 = S64_FromString_Hex            (NULL);
	t_size               var_0342 = U8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0343 = U16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0344 = U32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0345 = U64_Parse_Oct                 (NULL, NULL, 0);
	t_u8                 var_0346 = U8_FromString_Oct             (NULL);
	t_u16                var_0347 = U16_FromString_Oct            (NULL);
	t_u32                var_0348 = U32_FromString_Oct            (NULL);
	t_u64                var_0349 = U64_FromString_Oct            (NULL);
	t_size               var_0350 = S8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0351 = S16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0352 = S32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0353 = S64_Parse_Oct                 (NULL, NULL, 0);
	t_s8                 var_0354 = S8_FromString_Oct             (NULL);
	t_s16                var_0355 = S16_FromString_Oct            (NULL);
	t_s32                var_0356 = S32_FromString_Oct            (NULL);
	t_s64                var_0357 = S64_FromString_Oct            (NULL);
	t_size               var_0358 = U8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0359 = U16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0360 = U32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0361 = U64_Parse_Bin                 (NULL, NULL, 0);
	t_u8                 var_0362 = U8_FromString_Bin             (NULL);
	t_u16                var_0363 = U16_FromString_Bin            (NULL);
	t_u32                var_0364 = U32_FromString_Bin            (NULL);
	t_u64                var_0365 = U64_FromString_Bin            (NULL);
	t_size               var_0366 = S8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0367 = S16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0368 = S32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0369 = S64_Parse_Bin                 (NULL, NULL, 0);
	t_s8                 var_0370 = S8_FromString_Bin             (NULL);
	t_s16                var_0371 = S16_FromString_Bin            (NULL);
	t_s32                var_0372 = S32_FromString_Bin            (NULL);
	t_s64                var_0373 = S64_FromString_Bin            (NULL);
	t_size               var_0374 = U8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0375 = U16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0376 = U32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0377 = U64_Parse_Base                (NULL, NULL, NULL, 0);
	t_u8                 var_0378 = U8_FromString_Base            (NULL, NULL);
	t_u16                var_0379 = U16_FromString_Base           (NULL, NULL);
	t_u32                var_0380 = U32_FromString_Base           (NULL, NULL);
	t_u64                var_0381 = U64_FromString_Base           (NULL, NULL);
	t_size               var_0382 = S8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0383 = S16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0384 = S32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0385 = S64_Parse_Base                (NULL, NULL, NULL, 0);
	t_s8                 var_0386 = S8_FromString_Base            (NULL, NULL);
	t_s16                var_0387 = S16_FromString_Base           (NULL, NULL);
	t_s32                var_0388 = S32_FromString_Base           (NULL, NULL);
	t_s64                var_0389 = S64_FromString_Base           (NULL, NULL);
	t_float              var_0390 = c_integrate                   (0, (s_interval){0}, 0);
	t_float              var_0391 = c_mc_integrate_1d             (0, (s_box1d){0});
	t_float              var_0392 = c_mc_integrate_2d             (0, (s_box2d){0});
	t_float              var_0393 = c_mc_integrate_3d             (0, (s_box3d){0});
	t_float              var_0394 = c_mc_integrate_4d             (0, (s_box4d){0});
	t_float              var_0395 = c_distance_float              (0, 0);
	t_f32                var_0396 = c_distance_f32                (0, 0);
	t_f64                var_0397 = c_distance_f64                (0, 0);
	t_uint               var_0398 = c_distance_uint               (0, 0);
	t_u8                 var_0399 = c_distance_u8                 (0, 0);
	t_u16                var_0400 = c_distance_u16                (0, 0);
	t_u32                var_0401 = c_distance_u32                (0, 0);
	t_u64                var_0402 = c_distance_u64                (0, 0);
	t_sint               var_0403 = c_distance_int                (0, 0);
	t_s8                 var_0404 = c_distance_s8                 (0, 0);
	t_s16                var_0405 = c_distance_s16                (0, 0);
	t_s32                var_0406 = c_distance_s32                (0, 0);
	t_s64                var_0407 = c_distance_s64                (0, 0);
	s_matrix2d           var_0408 = Matrix2D                      (NULL, NULL);
	s_matrix2d*          var_0409 = Matrix2D_New                  (NULL, NULL);
	t_bool               var_0410 = Matrix2D_Equals               (NULL, NULL);
	s_vector2d           var_0411 = Matrix2D_Apply                (NULL, NULL);
	t_float              var_0412 = Matrix2D_Determinant          (NULL);
	s_matrix2d           var_0413 = Matrix2D_Inverse              (NULL);
	s_matrix2d           var_0414 = Matrix2D_Transpose            (NULL);
	s_matrix2d           var_0415 = Matrix2D_Multiply             (NULL, NULL);
	s_matrix3d           var_0416 = Matrix3D                      (NULL, NULL, NULL);
	s_matrix3d*          var_0417 = Matrix3D_New                  (NULL, NULL, NULL);
	t_bool               var_0418 = Matrix3D_Equals               (NULL, NULL);
	s_vector3d           var_0419 = Matrix3D_Apply                (NULL, NULL);
	t_float              var_0420 = Matrix3D_Determinant          (NULL);
	s_matrix3d           var_0421 = Matrix3D_Inverse              (NULL);
	s_matrix3d           var_0422 = Matrix3D_Transpose            (NULL);
	s_matrix3d           var_0423 = Matrix3D_Multiply             (NULL, NULL);
	s_vector2d           var_0424 = Vector2D                      (0, 0);
	s_vector2d*          var_0425 = Vector2D_New                  (0, 0);
	t_bool               var_0426 = Vector2D_Equals               (NULL, NULL);
	s_vector2d           var_0427 = Vector2D_Scale                (NULL, 0);
	s_vector2d           var_0428 = Vector2D_Invert               (NULL);
	t_float              var_0429 = Vector2D_Norm                 (NULL);
	s_vector2d           var_0430 = Vector2D_Normalize            (NULL);
	s_vector2d           var_0431 = Vector2D_Add                  (NULL, NULL);
	t_float              var_0432 = Vector2D_Dot                  (NULL, NULL);
	s_vector3d           var_0433 = Vector3D                      (0, 0, 0);
	s_vector3d*          var_0434 = Vector3D_New                  (0, 0, 0);
	t_bool               var_0435 = Vector3D_Equals               (NULL, NULL);
	s_vector3d           var_0436 = Vector3D_Scale                (NULL, 0);
	s_vector3d           var_0437 = Vector3D_Invert               (NULL);
	t_float              var_0438 = Vector3D_Norm                 (NULL);
	s_vector3d           var_0439 = Vector3D_Normalize            (NULL);
	s_vector3d           var_0440 = Vector3D_Add                  (NULL, NULL);
	t_float              var_0441 = Vector3D_Dot                  (NULL, NULL);
	s_vector3d           var_0442 = Vector3D_Cross                (NULL, NULL);
	s_complex            var_0443 = Complex                       (0, 0);
	s_complex*           var_0444 = Complex_New                   (0, 0);
	t_bool               var_0445 = Complex_Equals                (NULL, NULL);
	t_float              var_0446 = Complex_Abs                   (NULL);
	s_complex            var_0447 = Complex_Conjugate             (NULL);
	s_complex            var_0448 = Complex_Add                   (NULL, NULL);
	s_complex            var_0449 = Complex_Sub                   (NULL, NULL);
	s_complex            var_0450 = Complex_Mul                   (NULL, NULL);
	s_complex            var_0451 = Complex_Div                   (NULL, NULL);
	s_complex            var_0452 = Complex_Pow                   (NULL, 0);
	t_q16                var_0453 = Q16_Abs                       (0);
	t_q32                var_0454 = Q32_Abs                       (0);
	t_q64                var_0455 = Q64_Abs                       (0);
	t_q16                var_0456 = Q16_Round                     (0);
	t_q32                var_0457 = Q32_Round                     (0);
	t_q64                var_0458 = Q64_Round                     (0);
	t_q16                var_0459 = Q16_Trunc                     (0);
	t_q32                var_0460 = Q32_Trunc                     (0);
	t_q64                var_0461 = Q64_Trunc                     (0);
	t_q16                var_0462 = Q16_Floor                     (0);
	t_q32                var_0463 = Q32_Floor                     (0);
	t_q64                var_0464 = Q64_Floor                     (0);
	t_q16                var_0465 = Q16_Ceil                      (0);
	t_q32                var_0466 = Q32_Ceil                      (0);
	t_q64                var_0467 = Q64_Ceil                      (0);
	t_bool               var_0468 = Q16_Equals                    (0, 0);
	t_bool               var_0469 = Q32_Equals                    (0, 0);
	t_bool               var_0470 = Q64_Equals                    (0, 0);
	t_bool               var_0471 = Q16_EqualsApprox              (0, 0);
	t_bool               var_0472 = Q32_EqualsApprox              (0, 0);
	t_bool               var_0473 = Q64_EqualsApprox              (0, 0);
	t_q16                var_0474 = Q16_Add                       (0, 0);
	t_q32                var_0475 = Q32_Add                       (0, 0);
	t_q64                var_0476 = Q64_Add                       (0, 0);
	t_q16                var_0477 = Q16_Sub                       (0, 0);
	t_q32                var_0478 = Q32_Sub                       (0, 0);
	t_q64                var_0479 = Q64_Sub                       (0, 0);
	t_q16                var_0480 = Q16_Mul                       (0, 0);
	t_q32                var_0481 = Q32_Mul                       (0, 0);
	t_q64                var_0482 = Q64_Mul                       (0, 0);
	t_q16                var_0483 = Q16_Div                       (0, 0);
	t_q32                var_0484 = Q32_Div                       (0, 0);
	t_q64                var_0485 = Q64_Div                       (0, 0);
	t_q16                var_0486 = Q16_Mod                       (0, 0);
	t_q32                var_0487 = Q32_Mod                       (0, 0);
	t_q64                var_0488 = Q64_Mod                       (0, 0);
	t_q16                var_0489 = Q16_Pow                       (0, 0);
	t_q32                var_0490 = Q32_Pow                       (0, 0);
	t_q64                var_0491 = Q64_Pow                       (0, 0);
	t_q16                var_0492 = Q16_IntPow                    (0, 0);
	t_q32                var_0493 = Q32_IntPow                    (0, 0);
	t_q64                var_0494 = Q64_IntPow                    (0, 0);
	t_q16                var_0495 = Q16_Root2                     (0);
	t_q32                var_0496 = Q32_Root2                     (0);
	t_q64                var_0497 = Q64_Root2                     (0);
	t_q16                var_0498 = Q16_Root3                     (0);
	t_q32                var_0499 = Q32_Root3                     (0);
	t_q64                var_0500 = Q64_Root3                     (0);
	t_q16                var_0501 = Q16_RootN                     (0, 0);
	t_q32                var_0502 = Q32_RootN                     (0, 0);
	t_q64                var_0503 = Q64_RootN                     (0, 0);
	t_q16                var_0504 = Q16_Exp                       (0);
	t_q32                var_0505 = Q32_Exp                       (0);
	t_q64                var_0506 = Q64_Exp                       (0);
	t_q16                var_0507 = Q16_Ln                        (0);
	t_q32                var_0508 = Q32_Ln                        (0);
	t_q64                var_0509 = Q64_Ln                        (0);
	t_q16                var_0510 = Q16_Log2                      (0);
	t_q32                var_0511 = Q32_Log2                      (0);
	t_q64                var_0512 = Q64_Log2                      (0);
	t_q16                var_0513 = Q16_Log10                     (0);
	t_q32                var_0514 = Q32_Log10                     (0);
	t_q64                var_0515 = Q64_Log10                     (0);
	t_q16                var_0516 = Q16_LogN                      (0, 0);
	t_q32                var_0517 = Q32_LogN                      (0, 0);
	t_q64                var_0518 = Q64_LogN                      (0, 0);
	t_q16                var_0519 = Q16_Cos                       (0);
	t_q32                var_0520 = Q32_Cos                       (0);
	t_q64                var_0521 = Q64_Cos                       (0);
	t_q16                var_0522 = Q16_Sin                       (0);
	t_q32                var_0523 = Q32_Sin                       (0);
	t_q64                var_0524 = Q64_Sin                       (0);
	t_q16                var_0525 = Q16_Tan                       (0);
	t_q32                var_0526 = Q32_Tan                       (0);
	t_q64                var_0527 = Q64_Tan                       (0);
	t_q16                var_0528 = Q16_ArcCos                    (0);
	t_q32                var_0529 = Q32_ArcCos                    (0);
	t_q64                var_0530 = Q64_ArcCos                    (0);
	t_q16                var_0531 = Q16_ArcSin                    (0);
	t_q32                var_0532 = Q32_ArcSin                    (0);
	t_q64                var_0533 = Q64_ArcSin                    (0);
	t_q16                var_0534 = Q16_ArcTan                    (0);
	t_q32                var_0535 = Q32_ArcTan                    (0);
	t_q64                var_0536 = Q64_ArcTan                    (0);
	t_q16                var_0537 = Q16_                          (0, 0);
	t_q32                var_0538 = Q32_                          (0, 0);
	t_q64                var_0539 = Q64_                          (0, 0);
	t_q16                var_0540 = Q16_CosH                      (0);
	t_q32                var_0541 = Q32_CosH                      (0);
	t_q64                var_0542 = Q64_CosH                      (0);
	t_q16                var_0543 = Q16_SinH                      (0);
	t_q32                var_0544 = Q32_SinH                      (0);
	t_q64                var_0545 = Q64_SinH                      (0);
	t_q16                var_0546 = Q16_TanH                      (0);
	t_q32                var_0547 = Q32_TanH                      (0);
	t_q64                var_0548 = Q64_TanH                      (0);
	t_q16                var_0549 = Q16_InvCosH                   (0);
	t_q32                var_0550 = Q32_InvCosH                   (0);
	t_q64                var_0551 = Q64_InvCosH                   (0);
	t_q16                var_0552 = Q16_InvSinH                   (0);
	t_q32                var_0553 = Q32_InvSinH                   (0);
	t_q64                var_0554 = Q64_InvSinH                   (0);
	t_q16                var_0555 = Q16_InvTanH                   (0);
	t_q32                var_0556 = Q32_InvTanH                   (0);
	t_q64                var_0557 = Q64_InvTanH                   (0);
	t_f32                var_0558 = F32_Abs                       (0);
	t_f64                var_0559 = F64_Abs                       (0);
	t_f80                var_0560 = F80_Abs                       (0);
	t_f32                var_0561 = F32_Round                     (0);
	t_f64                var_0562 = F64_Round                     (0);
	t_f80                var_0563 = F80_Round                     (0);
	t_f32                var_0564 = F32_Trunc                     (0);
	t_f64                var_0565 = F64_Trunc                     (0);
	t_f80                var_0566 = F80_Trunc                     (0);
	t_f32                var_0567 = F32_Floor                     (0);
	t_f64                var_0568 = F64_Floor                     (0);
	t_f80                var_0569 = F80_Floor                     (0);
	t_f32                var_0570 = F32_Ceil                      (0);
	t_f64                var_0571 = F64_Ceil                      (0);
	t_f80                var_0572 = F80_Ceil                      (0);
	t_bool               var_0573 = F32_Equals                    (0, 0);
	t_bool               var_0574 = F64_Equals                    (0, 0);
	t_bool               var_0575 = F80_Equals                    (0, 0);
	t_bool               var_0576 = F32_EqualsApprox              (0, 0);
	t_bool               var_0577 = F64_EqualsApprox              (0, 0);
	t_bool               var_0578 = F80_EqualsApprox              (0, 0);
	t_f32                var_0579 = F32_Add                       (0, 0);
	t_f64                var_0580 = F64_Add                       (0, 0);
	t_f80                var_0581 = F80_Add                       (0, 0);
	t_f32                var_0582 = F32_Sub                       (0, 0);
	t_f64                var_0583 = F64_Sub                       (0, 0);
	t_f80                var_0584 = F80_Sub                       (0, 0);
	t_f32                var_0585 = F32_Mul                       (0, 0);
	t_f64                var_0586 = F64_Mul                       (0, 0);
	t_f80                var_0587 = F80_Mul                       (0, 0);
	t_f32                var_0588 = F32_Div                       (0, 0);
	t_f64                var_0589 = F64_Div                       (0, 0);
	t_f80                var_0590 = F80_Div                       (0, 0);
	t_f32                var_0591 = F32_Mod                       (0, 0);
	t_f64                var_0592 = F64_Mod                       (0, 0);
	t_f80                var_0593 = F80_Mod                       (0, 0);
	t_f32                var_0594 = F32_Pow                       (0, 0);
	t_f64                var_0595 = F64_Pow                       (0, 0);
	t_f80                var_0596 = F80_Pow                       (0, 0);
	t_f32                var_0597 = F32_IntPow                    (0, 0);
	t_f64                var_0598 = F64_IntPow                    (0, 0);
	t_f80                var_0599 = F80_IntPow                    (0, 0);
	t_f32                var_0600 = F32_Root2                     (0);
	t_f64                var_0601 = F64_Root2                     (0);
	t_f80                var_0602 = F80_Root2                     (0);
	t_f32                var_0603 = F32_Root3                     (0);
	t_f64                var_0604 = F64_Root3                     (0);
	t_f80                var_0605 = F80_Root3                     (0);
	t_f32                var_0606 = F32_RootN                     (0, 0);
	t_f64                var_0607 = F64_RootN                     (0, 0);
	t_f80                var_0608 = F80_RootN                     (0, 0);
	t_f32                var_0609 = F32_Exp                       (0);
	t_f64                var_0610 = F64_Exp                       (0);
	t_f80                var_0611 = F80_Exp                       (0);
	t_f32                var_0612 = F32_Ln                        (0);
	t_f64                var_0613 = F64_Ln                        (0);
	t_f80                var_0614 = F80_Ln                        (0);
	t_f32                var_0615 = F32_Log2                      (0);
	t_f64                var_0616 = F64_Log2                      (0);
	t_f80                var_0617 = F80_Log2                      (0);
	t_f32                var_0618 = F32_Log10                     (0);
	t_f64                var_0619 = F64_Log10                     (0);
	t_f80                var_0620 = F80_Log10                     (0);
	t_f32                var_0621 = F32_LogN                      (0, 0);
	t_f64                var_0622 = F64_LogN                      (0, 0);
	t_f80                var_0623 = F80_LogN                      (0, 0);
	t_f32                var_0624 = F32_Cos                       (0);
	t_f64                var_0625 = F64_Cos                       (0);
	t_f80                var_0626 = F80_Cos                       (0);
	t_f32                var_0627 = F32_Sin                       (0);
	t_f64                var_0628 = F64_Sin                       (0);
	t_f80                var_0629 = F80_Sin                       (0);
	t_f32                var_0630 = F32_Tan                       (0);
	t_f64                var_0631 = F64_Tan                       (0);
	t_f80                var_0632 = F80_Tan                       (0);
	t_f32                var_0633 = F32_ArcCos                    (0);
	t_f64                var_0634 = F64_ArcCos                    (0);
	t_f80                var_0635 = F80_ArcCos                    (0);
	t_f32                var_0636 = F32_ArcSin                    (0);
	t_f64                var_0637 = F64_ArcSin                    (0);
	t_f80                var_0638 = F80_ArcSin                    (0);
	t_f32                var_0639 = F32_ArcTan                    (0);
	t_f64                var_0640 = F64_ArcTan                    (0);
	t_f80                var_0641 = F80_ArcTan                    (0);
	t_f32                var_0642 = F32_ArcTan2                   (0, 0);
	t_f64                var_0643 = F64_ArcTan2                   (0, 0);
	t_f80                var_0644 = F80_ArcTan2                   (0, 0);
	t_f32                var_0645 = F32_CosH                      (0);
	t_f64                var_0646 = F64_CosH                      (0);
	t_f80                var_0647 = F80_CosH                      (0);
	t_f32                var_0648 = F32_SinH                      (0);
	t_f64                var_0649 = F64_SinH                      (0);
	t_f80                var_0650 = F80_SinH                      (0);
	t_f32                var_0651 = F32_TanH                      (0);
	t_f64                var_0652 = F64_TanH                      (0);
	t_f80                var_0653 = F80_TanH                      (0);
	t_f32                var_0654 = F32_InvCosH                   (0);
	t_f64                var_0655 = F64_InvCosH                   (0);
	t_f80                var_0656 = F80_InvCosH                   (0);
	t_f32                var_0657 = F32_InvSinH                   (0);
	t_f64                var_0658 = F64_InvSinH                   (0);
	t_f80                var_0659 = F80_InvSinH                   (0);
	t_f32                var_0660 = F32_InvTanH                   (0);
	t_f64                var_0661 = F64_InvTanH                   (0);
	t_f80                var_0662 = F80_InvTanH                   (0);
	t_s8                 var_0663 = S8_Abs                        (0);
	t_s16                var_0664 = S16_Abs                       (0);
	t_s32                var_0665 = S32_Abs                       (0);
	t_s64                var_0666 = S64_Abs                       (0);
	t_bool               var_0667 = S8_Equals                     (0, 0);
	t_bool               var_0668 = S16_Equals                    (0, 0);
	t_bool               var_0669 = S32_Equals                    (0, 0);
	t_bool               var_0670 = S64_Equals                    (0, 0);
	t_bool               var_0671 = S8_EqualsApprox               (0, 0);
	t_bool               var_0672 = S16_EqualsApprox              (0, 0);
	t_bool               var_0673 = S32_EqualsApprox              (0, 0);
	t_bool               var_0674 = S64_EqualsApprox              (0, 0);
	t_u8                 var_0675 = U8_Add                        (0, 0);
	t_u16                var_0676 = U16_Add                       (0, 0);
	t_u32                var_0677 = U32_Add                       (0, 0);
	t_u64                var_0678 = U64_Add                       (0, 0);
	t_s8                 var_0679 = S8_Add                        (0, 0);
	t_s16                var_0680 = S16_Add                       (0, 0);
	t_s32                var_0681 = S32_Add                       (0, 0);
	t_s64                var_0682 = S64_Add                       (0, 0);
	t_u8                 var_0683 = U8_Sub                        (0, 0);
	t_u16                var_0684 = U16_Sub                       (0, 0);
	t_u32                var_0685 = U32_Sub                       (0, 0);
	t_u64                var_0686 = U64_Sub                       (0, 0);
	t_s8                 var_0687 = S8_Sub                        (0, 0);
	t_s16                var_0688 = S16_Sub                       (0, 0);
	t_s32                var_0689 = S32_Sub                       (0, 0);
	t_s64                var_0690 = S64_Sub                       (0, 0);
	t_u8                 var_0691 = U8_Mul                        (0, 0);
	t_u16                var_0692 = U16_Mul                       (0, 0);
	t_u32                var_0693 = U32_Mul                       (0, 0);
	t_u64                var_0694 = U64_Mul                       (0, 0);
	t_s8                 var_0695 = S8_Mul                        (0, 0);
	t_s16                var_0696 = S16_Mul                       (0, 0);
	t_s32                var_0697 = S32_Mul                       (0, 0);
	t_s64                var_0698 = S64_Mul                       (0, 0);
	t_u8                 var_0699 = U8_Div                        (0, 0);
	t_u16                var_0700 = U16_Div                       (0, 0);
	t_u32                var_0701 = U32_Div                       (0, 0);
	t_u64                var_0702 = U64_Div                       (0, 0);
	t_s8                 var_0703 = S8_Div                        (0, 0);
	t_s16                var_0704 = S16_Div                       (0, 0);
	t_s32                var_0705 = S32_Div                       (0, 0);
	t_s64                var_0706 = S64_Div                       (0, 0);
	t_u8                 var_0707 = U8_Mod                        (0, 0);
	t_u16                var_0708 = U16_Mod                       (0, 0);
	t_u32                var_0709 = U32_Mod                       (0, 0);
	t_u64                var_0710 = U64_Mod                       (0, 0);
	t_s8                 var_0711 = S8_Mod                        (0, 0);
	t_s16                var_0712 = S16_Mod                       (0, 0);
	t_s32                var_0713 = S32_Mod                       (0, 0);
	t_s64                var_0714 = S64_Mod                       (0, 0);
	t_u8                 var_0715 = U8_Pow                        (0, 0);
	t_u16                var_0716 = U16_Pow                       (0, 0);
	t_u32                var_0717 = U32_Pow                       (0, 0);
	t_u64                var_0718 = U64_Pow                       (0, 0);
	t_s8                 var_0719 = S8_Pow                        (0, 0);
	t_s16                var_0720 = S16_Pow                       (0, 0);
	t_s32                var_0721 = S32_Pow                       (0, 0);
	t_s64                var_0722 = S64_Pow                       (0, 0);
	t_u8                 var_0723 = U8_Root2                      (0);
	t_u16                var_0724 = U16_Root2                     (0);
	t_u32                var_0725 = U32_Root2                     (0);
	t_u64                var_0726 = U64_Root2                     (0);
	t_s8                 var_0727 = S8_Root2                      (0);
	t_s16                var_0728 = S16_Root2                     (0);
	t_s32                var_0729 = S32_Root2                     (0);
	t_s64                var_0730 = S64_Root2                     (0);
	s_array_int          var_0731 = Stat_Int_NewList              (0);
	                                Stat_Int_FreeList             (NULL);
	s_array_int          var_0733 = Stat_Int_MergeList            (NULL, NULL);
	s_array_int          var_0734 = Stat_Int_Quicksort            ((s_array_int){0});
	                                Stat_Int_Quicksort_InPlace    ((s_array_int){0});
	t_float              var_0736 = Stat_Int_Median               ((s_sorted_int){0});
	t_float              var_0737 = Stat_Int_Average              ((s_array_int){0});
	t_float              var_0738 = Stat_Int_Variance             ((s_array_int){0});
	t_float              var_0739 = Stat_Int_StandardDeviation    ((s_array_int){0});
	                                Stat_Int_Decile               ((s_array_int){0});
	s_array_float        var_0741 = Stat_Float_NewList            (0);
	                                Stat_Float_FreeList           (NULL);
	s_array_float        var_0743 = Stat_Float_MergeList          (NULL, NULL);
	s_array_float        var_0744 = Stat_Float_Quicksort          ((s_array_float){0});
	                                Stat_Float_Quicksort_InPlace  ((s_array_float){0});
	t_float              var_0746 = Stat_Float_Median             ((s_sorted_float){0});
	t_float              var_0747 = Stat_Float_Average            ((s_array_float){0});
	t_float              var_0748 = Stat_Float_Variance           ((s_array_float){0});
	t_float              var_0749 = Stat_Float_StandardDeviation  ((s_array_float){0});
	                                Stat_Float_Decile             ((s_array_float){0});
	s_prob_mass          var_0751 = Stat_NewPMF                   (0);
	                                Stat_FreePMF                  (NULL);
	s_array_int          var_0753 = Stat_IntList_To_Set           ((s_array_int){0});
	t_uint               var_0754 = Stat_IntList_Count            ((s_array_int){0}, 0);
	s_prob_mass          var_0755 = Stat_IntList_To_PMF           ((s_array_int){0});
	void*                var_0756 = Memory_New                    (0);
	void*                var_0757 = Memory_New_C                  (0, 0);
	void*                var_0758 = Memory_Allocate               (0);
	void*                var_0759 = Memory_Reallocate             (NULL, 0);
	                                Memory_Deallocate             (NULL);
	                                Memory_Delete                 (NULL);
	                                Memory_Set                    (NULL, 0, 0);
	                                Memory_Clear                  (NULL, 0);
	void*                var_0764 = Memory_Copy                   (NULL, NULL, 0);
	void*                var_0765 = Memory_Copy_C                 (NULL, NULL, 0, 0);
	void*                var_0766 = Memory_Move                   (NULL, NULL, 0);
	void*                var_0767 = Memory_Duplicate              (NULL, 0);
	void*                var_0768 = Memory_Join                   (NULL, 0, NULL, 0);
	void*                var_0769 = Memory_Append                 (NULL, 0, NULL, 0);
	void*                var_0770 = Memory_Prepend                (NULL, 0, NULL, 0);
	void*                var_0771 = Memory_Merge                  (NULL, 0, NULL, 0);
	void*                var_0772 = Memory_Find                   (NULL, 0, 0);
	                                Memory_Replace                (NULL, 0, 0, 0);
	t_sint               var_0774 = Memory_Compare                (NULL, NULL, 0);
	t_bool               var_0775 = Memory_Equals                 (NULL, NULL, 0);
	t_size               var_0776 = Memory_Print                  (NULL, NULL, 0);
	t_char*              var_0777 = Memory_ToString               (NULL, 0);
	t_uintmax            var_0778 = Memory_GetBits                (NULL, 0, 0);
	                                Memory_SetBits                (NULL, 0, 0, 0);
	t_uintmax            var_0780 = Memory_BitRegion              (0, 0, 0);
	t_u8                 var_0781 = Memory_CountBits              (0);
	t_s8                 var_0782 = Memory_GetMostSignificantBit  (0);
	t_s8                 var_0783 = Memory_GetLeastSignificantBit (0);
	s_array(any)         var_0784 = Array_Item(any)               (NULL);
	void**               var_0785 = Array_Get(any)                (NULL, 0);
	void**               var_0786 = Array_Set(any)                (NULL, 0, NULL);
	s_array(any)*        var_0787 = Array_New(any)                (NULL, NULL);
	s_array(any)*        var_0788 = Array_Create(any)             (NULL);
	s_array(any)*        var_0789 = Array_Duplicate(any)          (NULL);
	s_array(any)*        var_0790 = Array_Sub(any)                (NULL, 0, 0);
	s_array(any)*        var_0791 = Array_Copy(any)               (NULL, 0, NULL, 0, 0);
	                                Array_Free(any)               (NULL);
	                                Array_Free_F(any)             (NULL, NULL);
	                                Array_Delete(any)             (NULL);
	                                Array_Delete_F(any)           (NULL, NULL);
	s_array(any)*        var_0796 = Array_Add(any)                (NULL, NULL);
	s_array(any)*        var_0797 = Array_Insert(any)             (NULL, NULL, 0);
	s_array(any)*        var_0798 = Array_Wedge(any)              (NULL, NULL, 0);
	                                Array_RemoveAt(any)           (NULL, 0);
	                                Array_RemoveAt_F(any)         (NULL, 0, NULL);
	                                Array_Remove(any)             (NULL, NULL);
	                                Array_Remove_F(any)           (NULL, NULL, NULL);
	                                Array_RemoveAll(any)          (NULL, NULL);
	                                Array_RemoveAll_F(any)        (NULL, NULL, NULL);
	s_array(any)*        var_0805 = Array_Replace(any)            (NULL, NULL, NULL);
	s_array(any)*        var_0806 = Array_ReplaceFirst(any)       (NULL, NULL, NULL, 0);
	s_array(any)*        var_0807 = Array_ReplaceLast(any)        (NULL, NULL, NULL, 0);
	s_array(any)*        var_0808 = Array_Reverse(any)            (NULL);
	s_array(any)*        var_0809 = Array_Concat(any)             (NULL, NULL);
	s_array(any)*        var_0810 = Array_Append(any)             (NULL, NULL);
	s_array(any)*        var_0811 = Array_Prepend(any)            (NULL, NULL);
	s_array(any)*        var_0812 = Array_Merge(any)              (NULL, NULL);
	t_bool               var_0813 = Array_Equals(any)             (NULL, NULL);
	t_bool               var_0814 = Array_Equals_N(any)           (NULL, NULL, 0);
	t_sint               var_0815 = Array_Compare(any)            (NULL, NULL, NULL);
	t_sint               var_0816 = Array_Compare_N(any)          (NULL, NULL, NULL, 0);
	void**               var_0817 = Array_Find(any)               (NULL, NULL);
	void**               var_0818 = Array_Find_F(any)             (NULL, NULL);
	t_sint               var_0819 = Array_IndexOf(any)            (NULL, NULL);
	t_sint               var_0820 = Array_IndexOf_F(any)          (NULL, NULL);
	t_uint               var_0821 = Array_Count(any)              (NULL, NULL);
	t_bool               var_0822 = Array_Contains(any)           (NULL, NULL);
	t_bool               var_0823 = Array_Has(any)                (NULL, NULL);
	t_bool               var_0824 = Array_HasOnly(any)            (NULL, NULL);
	                                Array_Iterate(any)            (NULL, NULL);
	                                Array_Iterate_I(any)          (NULL, NULL);
	s_array(any)*        var_0827 = Array_Map(any)                (NULL, NULL);
	s_array(any)*        var_0828 = Array_Map_I(any)              (NULL, NULL);
	s_array(any)*        var_0829 = Array_Filter(any)             (NULL, NULL);
	s_array(any)*        var_0830 = Array_Filter_I(any)           (NULL, NULL);
	void*                var_0831 = Array_Reduce(any)             (NULL, NULL);
	void*                var_0832 = Array_Reduce_I(any)           (NULL, NULL);
	void*                var_0833 = Array_Fold(any)               (NULL, NULL, NULL);
	void*                var_0834 = Array_Fold_I(any)             (NULL, NULL, NULL);
	s_array(any)*        var_0835 = List_ToArray                  (NULL);
	void**               var_0836 = List_ToPointerArray           (NULL);
	s_list(any)*         var_0837 = List_Item(any)                (NULL);
	t_uint               var_0838 = List_Length(any)              (NULL);
	void**               var_0839 = List_Get(any)                 (NULL, 0);
	void**               var_0840 = List_Set(any)                 (NULL, 0, NULL);
	s_list(any)*         var_0841 = List_New(any)                 (NULL, NULL);
	s_list(any)*         var_0842 = List_Create(any)              (NULL);
	s_list(any)*         var_0843 = List_Duplicate(any)           (NULL);
	s_list(any)*         var_0844 = List_Sub(any)                 (NULL, 0, 0);
	s_list(any)*         var_0845 = List_Copy(any)                (NULL, 0, NULL, 0, 0);
	                                List_Free(any)                (NULL);
	                                List_Free_F(any)              (NULL, NULL);
	                                List_Delete(any)              (NULL);
	                                List_Delete_F(any)            (NULL, NULL);
	s_list(any)*         var_0850 = List_Add(any)                 (NULL, NULL);
	s_list(any)*         var_0851 = List_Insert(any)              (NULL, NULL, 0);
	s_list(any)*         var_0852 = List_Wedge(any)               (NULL, NULL, 0);
	s_list(any)*         var_0853 = List_RemoveAt(any)            (NULL, 0);
	s_list(any)*         var_0854 = List_RemoveAt_F(any)          (NULL, 0, NULL);
	s_list(any)*         var_0855 = List_Remove(any)              (NULL, NULL);
	s_list(any)*         var_0856 = List_Remove_F(any)            (NULL, NULL, NULL);
	s_list(any)*         var_0857 = List_RemoveAll(any)           (NULL, NULL);
	s_list(any)*         var_0858 = List_RemoveAll_F(any)         (NULL, NULL, NULL);
	s_list(any)*         var_0859 = List_Replace(any)             (NULL, NULL, NULL);
	s_list(any)*         var_0860 = List_ReplaceFirst(any)        (NULL, NULL, NULL, 0);
	s_list(any)*         var_0861 = List_ReplaceLast(any)         (NULL, NULL, NULL, 0);
	s_list(any)*         var_0862 = List_Reverse(any)             (NULL);
	s_list(any)*         var_0863 = List_Concat(any)              (NULL, NULL);
	s_list(any)*         var_0864 = List_Append(any)              (NULL, NULL);
	s_list(any)*         var_0865 = List_Prepend(any)             (NULL, NULL);
	s_list(any)*         var_0866 = List_Merge(any)               (NULL, NULL);
	t_bool               var_0867 = List_Equals(any)              (NULL, NULL);
	t_bool               var_0868 = List_Equals_N(any)            (NULL, NULL, 0);
	t_sint               var_0869 = List_Compare(any)             (NULL, NULL, NULL);
	t_sint               var_0870 = List_Compare_N(any)           (NULL, NULL, NULL, 0);
	s_list(any) const*   var_0871 = List_Find(any)                (NULL, NULL);
	s_list(any) const*   var_0872 = List_Find_F(any)              (NULL, NULL);
	t_sint               var_0873 = List_IndexOf(any)             (NULL, NULL);
	t_sint               var_0874 = List_IndexOf_F(any)           (NULL, NULL);
	t_uint               var_0875 = List_Count(any)               (NULL, NULL);
	t_bool               var_0876 = List_Contains(any)            (NULL, NULL);
	t_bool               var_0877 = List_Has(any)                 (NULL, NULL);
	t_bool               var_0878 = List_HasOnly(any)             (NULL, NULL);
	                                List_Iterate(any)             (NULL, NULL);
	                                List_Iterate_I(any)           (NULL, NULL);
	s_list(any)*         var_0881 = List_Map(any)                 (NULL, NULL);
	s_list(any)*         var_0882 = List_Map_I(any)               (NULL, NULL);
	s_list(any)*         var_0883 = List_Filter(any)              (NULL, NULL);
	s_list(any)*         var_0884 = List_Filter_I(any)            (NULL, NULL);
	void*                var_0885 = List_Reduce(any)              (NULL, NULL);
	void*                var_0886 = List_Reduce_I(any)            (NULL, NULL);
	void*                var_0887 = List_Fold(any)                (NULL, NULL, NULL);
	void*                var_0888 = List_Fold_I(any)              (NULL, NULL, NULL);
	t_char*              var_0889 = Size_ToString                 (0);
	t_char*              var_0890 = Size_ToString_Hex             (0);
	t_char*              var_0891 = Size_ToString_Pretty          (0);
	t_char*              var_0892 = Pointer_ToString              (NULL);
	t_char*              var_0893 = Pointer_ToString_Hex          (NULL);
	t_size               var_0894 = Size_Parse                    (NULL, NULL);
	t_size               var_0895 = Size_FromString               (NULL);
	t_size               var_0896 = PtrDiff_Parse                 (NULL, NULL);
	t_ptrdiff            var_0897 = PtrDiff_FromString            (NULL);
	t_size               var_0898 = UIntMax_Parse                 (NULL, NULL);
	t_uintmax            var_0899 = UIntMax_FromString            (NULL);
	t_size               var_0900 = SIntMax_Parse                 (NULL, NULL);
	t_sintmax            var_0901 = SIntMax_FromString            (NULL);
	t_size               var_0902 = UIntPtr_Parse                 (NULL, NULL);
	t_uintptr            var_0903 = UIntPtr_FromString            (NULL);
	t_size               var_0904 = SIntPtr_Parse                 (NULL, NULL);
	t_sintptr            var_0905 = SIntPtr_FromString            (NULL);
	t_uint               var_0906 = PointerArray_Length           (NULL);
	void**               var_0907 = PointerArray_New              (0, NULL);
	void**               var_0908 = PointerArray_Create           (0);
	void**               var_0909 = PointerArray_Duplicate        (NULL);
	void**               var_0910 = PointerArray_Sub              (NULL, 0, 0);
	void**               var_0911 = PointerArray_Copy             (NULL, 0, NULL, 0, 0);
	                                PointerArray_Free             (NULL);
	                                PointerArray_Free_F           (NULL, NULL);
	                                PointerArray_Delete           (NULL);
	                                PointerArray_Delete_F         (NULL, NULL);
	void**               var_0916 = PointerArray_Add              (NULL, NULL);
	void**               var_0917 = PointerArray_Insert           (NULL, NULL, 0);
	void**               var_0918 = PointerArray_Wedge            (NULL, NULL, 0);
	                                PointerArray_RemoveAt         (NULL, 0);
	                                PointerArray_RemoveAt_F       (NULL, 0, NULL);
	                                PointerArray_Remove           (NULL, NULL);
	                                PointerArray_Remove_F         (NULL, NULL, NULL);
	                                PointerArray_RemoveAll        (NULL, NULL);
	                                PointerArray_RemoveAll_F      (NULL, NULL, NULL);
	void**               var_0925 = PointerArray_Replace          (NULL, NULL, NULL);
	void**               var_0926 = PointerArray_ReplaceFirst     (NULL, NULL, NULL, 0);
	void**               var_0927 = PointerArray_ReplaceLast      (NULL, NULL, NULL, 0);
	void**               var_0928 = PointerArray_Reverse          (NULL);
	void**               var_0929 = PointerArray_Concat           (NULL, NULL);
	void**               var_0930 = PointerArray_Append           (NULL, NULL);
	void**               var_0931 = PointerArray_Prepend          (NULL, NULL);
	void**               var_0932 = PointerArray_Merge            (NULL, NULL);
	void**               var_0933 = PointerArray_Join             (NULL, NULL);
	t_bool               var_0934 = PointerArray_Equals           (NULL, NULL);
	t_bool               var_0935 = PointerArray_Equals_N         (NULL, NULL, 0);
	t_sint               var_0936 = PointerArray_Compare          (NULL, NULL, NULL);
	t_sint               var_0937 = PointerArray_Compare_N        (NULL, NULL, NULL, 0);
	void* const*         var_0938 = PointerArray_Find             (NULL, NULL);
	void* const*         var_0939 = PointerArray_Find_F           (NULL, NULL);
	t_sint               var_0940 = PointerArray_IndexOf          (NULL, NULL);
	t_sint               var_0941 = PointerArray_IndexOf_F        (NULL, NULL);
	t_uint               var_0942 = PointerArray_Count            (NULL, NULL);
	t_bool               var_0943 = PointerArray_Contains         (NULL, NULL);
	t_bool               var_0944 = PointerArray_Has              (NULL, NULL);
	t_bool               var_0945 = PointerArray_HasOnly          (NULL, NULL);
	                                PointerArray_Iterate          (NULL, NULL);
	                                PointerArray_Iterate_I        (NULL, NULL);
	void**               var_0948 = PointerArray_Map              (NULL, NULL);
	void**               var_0949 = PointerArray_Map_I            (NULL, NULL);
	void**               var_0950 = PointerArray_Filter           (NULL, NULL);
	void**               var_0951 = PointerArray_Filter_I         (NULL, NULL);
	void*                var_0952 = PointerArray_Reduce           (NULL, NULL);
	void*                var_0953 = PointerArray_Reduce_I         (NULL, NULL);
	void*                var_0954 = PointerArray_Fold             (NULL, NULL, NULL);
	void*                var_0955 = PointerArray_Fold_I           (NULL, NULL, NULL);
	t_csprng*            var_0956 = CSPRNG_New                    ();
	                                CSPRNG_Delete                 (NULL);
	e_cccerror           var_0958 = CSPRNG_Next                   (NULL, NULL, 0);
	t_uint               var_0959 = CSPRNG_UInt                   (NULL);
	t_uint               var_0960 = CSPRNG_UInt_Range             (NULL, 0, 0);
	t_sint               var_0961 = CSPRNG_SInt                   (NULL);
	t_sint               var_0962 = CSPRNG_SInt_Range             (NULL, 0, 0);
	t_fixed              var_0963 = CSPRNG_Fixed                  (NULL);
	t_fixed              var_0964 = CSPRNG_Fixed_Range            (NULL, 0, 0);
	t_float              var_0965 = CSPRNG_Float                  (NULL);
	t_float              var_0966 = CSPRNG_Float_Range            (NULL, 0, 0);
	void*                var_0967 = CSPRNG_Get                    (NULL, 0);
	t_uint               var_0968 = CSPRNG_UInt_Get               ();
	t_uint               var_0969 = CSPRNG_UInt_Get_Range         (0, 0);
	t_sint               var_0970 = CSPRNG_SInt_Get               ();
	t_sint               var_0971 = CSPRNG_SInt_Get_Range         (0, 0);
	t_fixed              var_0972 = CSPRNG_Fixed_Get              ();
	t_fixed              var_0973 = CSPRNG_Fixed_Get_Range        (0, 0);
	t_float              var_0974 = CSPRNG_Float_Get              ();
	t_float              var_0975 = CSPRNG_Float_Get_Range        (0, 0);
	                                PRNG_SetSeed                  (NULL, 0);
	                                PRNG_NewSeed                  (NULL);
	t_prng*              var_0978 = PRNG_New                      ();
	                                PRNG_Delete                   (NULL);
	e_cccerror           var_0980 = PRNG_Next                     (NULL, NULL, 0);
	t_uint               var_0981 = PRNG_UInt                     (NULL);
	t_uint               var_0982 = PRNG_UInt_Range               (NULL, 0, 0);
	t_sint               var_0983 = PRNG_SInt                     (NULL);
	t_sint               var_0984 = PRNG_SInt_Range               (NULL, 0, 0);
	t_fixed              var_0985 = PRNG_Fixed                    (NULL);
	t_fixed              var_0986 = PRNG_Fixed_Range              (NULL, 0, 0);
	t_float              var_0987 = PRNG_Float                    (NULL);
	t_float              var_0988 = PRNG_Float_Range              (NULL, 0, 0);
	void*                var_0989 = PRNG_Get                      (NULL, 0);
	t_uint               var_0990 = PRNG_UInt_Get                 ();
	t_uint               var_0991 = PRNG_UInt_Get_Range           (0, 0);
	t_sint               var_0992 = PRNG_SInt_Get                 ();
	t_sint               var_0993 = PRNG_SInt_Get_Range           (0, 0);
	t_fixed              var_0994 = PRNG_Fixed_Get                ();
	t_fixed              var_0995 = PRNG_Fixed_Get_Range          (0, 0);
	t_float              var_0996 = PRNG_Float_Get                ();
	t_float              var_0997 = PRNG_Float_Get_Range          (0, 0);
	t_char*              var_0998 = String_New                    (0);
	t_char*              var_0999 = String_New_C                  (0, 0);
	                                String_Free                   (NULL);
	                                String_Delete                 (NULL);
	t_char*              var_1002 = String_Duplicate              (NULL);
	t_char*              var_1003 = String_Duplicate_N            (NULL, 0);
	t_char*              var_1004 = String_Duplicate_Char         (NULL, 0);
	t_char*              var_1005 = String_Duplicate_Charset      (NULL, NULL);
	t_char*              var_1006 = String_Duplicate_String       (NULL, NULL);
	                                String_Clear                  (NULL);
	                                String_Set                    (NULL, 0);
	t_char*              var_1009 = String_Copy                   (NULL, NULL);
	t_char*              var_1010 = String_Copy_N                 (NULL, NULL, 0);
	t_size               var_1011 = String_Copy_L                 (NULL, NULL, 0);
	t_char*              var_1012 = String_Add                    (NULL, NULL);
	t_char*              var_1013 = String_Add_N                  (NULL, NULL, 0);
	t_size               var_1014 = String_Add_L                  (NULL, NULL, 0);
	t_size               var_1015 = String_Length                 (NULL);
	t_bool               var_1016 = String_Equals                 (NULL, NULL);
	t_bool               var_1017 = String_Equals_N               (NULL, NULL, 0);
	t_bool               var_1018 = String_Equals_IgnoreCase      (NULL, NULL);
	t_bool               var_1019 = String_Equals_N_IgnoreCase    (NULL, NULL, 0);
	t_sint               var_1020 = String_Compare                (NULL, NULL);
	t_sint               var_1021 = String_Compare_N              (NULL, NULL, 0);
	t_sint               var_1022 = String_Compare_IgnoreCase     (NULL, NULL);
	t_sint               var_1023 = String_Compare_N_IgnoreCase   (NULL, NULL, 0);
	t_bool               var_1024 = String_Has                    (NULL, NULL);
	t_bool               var_1025 = String_HasOnly                (NULL, NULL);
	t_size               var_1026 = String_Count_Char             (NULL, 0);
	t_size               var_1027 = String_Count_Charset          (NULL, NULL);
	t_size               var_1028 = String_Count_String           (NULL, NULL);
	t_char*              var_1029 = String_Find_Char              (NULL, 0);
	t_char*              var_1030 = String_Find_Charset           (NULL, NULL);
	t_char*              var_1031 = String_Find_String            (NULL, NULL);
	t_char*              var_1032 = String_Find_R_Char            (NULL, 0);
	t_char*              var_1033 = String_Find_R_Charset         (NULL, NULL);
	t_char*              var_1034 = String_Find_R_String          (NULL, NULL);
	t_char*              var_1035 = String_Find_N_Char            (NULL, 0, 0);
	t_char*              var_1036 = String_Find_N_Charset         (NULL, NULL, 0);
	t_char*              var_1037 = String_Find_N_String          (NULL, NULL, 0);
	t_sintmax            var_1038 = String_IndexOf_Char           (NULL, 0);
	t_sintmax            var_1039 = String_IndexOf_Charset        (NULL, NULL);
	t_sintmax            var_1040 = String_IndexOf_String         (NULL, NULL);
	t_sintmax            var_1041 = String_IndexOf_R_Char         (NULL, 0);
	t_sintmax            var_1042 = String_IndexOf_R_Charset      (NULL, NULL);
	t_sintmax            var_1043 = String_IndexOf_R_String       (NULL, NULL);
	t_sintmax            var_1044 = String_IndexOf_N_Char         (NULL, 0, 0);
	t_sintmax            var_1045 = String_IndexOf_N_Charset      (NULL, NULL, 0);
	t_sintmax            var_1046 = String_IndexOf_N_String       (NULL, NULL, 0);
	t_char*              var_1047 = String_Remove                 (NULL, NULL);
	t_char*              var_1048 = String_Replace_String         (NULL, NULL, NULL);
	t_char*              var_1049 = String_Concat                 (NULL, NULL);
	t_char*              var_1050 = String_Append                 (NULL, NULL);
	t_char*              var_1051 = String_Prepend                (NULL, NULL);
	t_char*              var_1052 = String_Merge                  (NULL, NULL);
	t_char*              var_1053 = String_Join                   (NULL, NULL);
	t_char*              var_1054 = String_Insert_InPlace         (NULL, NULL, 0);
	                                String_Replace_Char_InPlace   (NULL, 0, 0);
	                                String_Replace_Charset_InPlace(NULL, NULL, NULL);
	                                String_Replace_String_InPlace (NULL, NULL, NULL);
	t_char*              var_1058 = String_Map_InPlace            (NULL, NULL);
	t_char*              var_1059 = String_Trim                   (NULL, NULL);
	t_char*              var_1060 = String_Trim_L                 (NULL, NULL);
	t_char*              var_1061 = String_Trim_R                 (NULL, NULL);
	t_char*              var_1062 = String_Pad                    (NULL, 0, 0);
	t_char*              var_1063 = String_Pad_L                  (NULL, 0, 0);
	t_char*              var_1064 = String_Pad_R                  (NULL, 0, 0);
	t_size               var_1065 = String_Print                  (NULL, NULL, 0, NULL);
	t_char*              var_1066 = String_ToEscape               (NULL, NULL);
	t_size               var_1067 = String_Parse                  (NULL, NULL, 0, 0);
	t_char*              var_1068 = String_FromEscape             (NULL, 0);
	t_char*              var_1069 = String_Reverse                (NULL);
	t_char*              var_1070 = String_Insert                 (NULL, NULL, 0);
	t_char*              var_1071 = String_Sub                    (NULL, 0, 0);
	                                String_Iterate                (NULL, NULL);
	                                String_Iterate_I              (NULL, NULL);
	t_char*              var_1074 = String_Map                    (NULL, NULL);
	t_char*              var_1075 = String_Map_I                  (NULL, NULL);
	t_char**             var_1076 = String_Split_Char             (NULL, 0);
	t_char**             var_1077 = String_Split_Charset          (NULL, NULL);
	t_char**             var_1078 = String_Split_String           (NULL, NULL);
	t_char**             var_1079 = String_Divide                 (NULL, 0);
	t_uint               var_1080 = StringArray_Length            (NULL);
	t_size               var_1081 = StringArray_TotalLength       (NULL, 0);
	t_char**             var_1082 = StringArray_New               (0);
	t_char**             var_1083 = StringArray_New_C             (0, 0, 0);
	t_char**             var_1084 = StringArray_Create            (0);
	t_char**             var_1085 = StringArray_Duplicate         (NULL);
	t_char**             var_1086 = StringArray_Sub               (NULL, 0, 0);
	t_char**             var_1087 = StringArray_Copy              (NULL, 0, NULL, 0, 0);
	                                StringArray_Free              (NULL);
	                                StringArray_Delete            (NULL);
	t_char**             var_1090 = StringArray_Add               (NULL, NULL);
	t_char**             var_1091 = StringArray_Insert            (NULL, NULL, 0);
	t_char**             var_1092 = StringArray_Wedge             (NULL, NULL, 0);
	                                StringArray_RemoveAt          (NULL, 0);
	                                StringArray_RemoveAt_F        (NULL, 0, NULL);
	                                StringArray_Remove            (NULL, NULL);
	                                StringArray_Remove_F          (NULL, NULL, NULL);
	                                StringArray_RemoveAll         (NULL, NULL);
	                                StringArray_RemoveAll_F       (NULL, NULL, NULL);
	t_char**             var_1099 = StringArray_Replace           (NULL, NULL, NULL);
	t_char**             var_1100 = StringArray_ReplaceFirst      (NULL, NULL, NULL, 0);
	t_char**             var_1101 = StringArray_ReplaceLast       (NULL, NULL, NULL, 0);
	t_char**             var_1102 = StringArray_Reverse           (NULL);
	t_char**             var_1103 = StringArray_Pad_L             (NULL, 0, 0);
	t_char**             var_1104 = StringArray_Concat            (NULL, NULL);
	t_char**             var_1105 = StringArray_Append            (NULL, NULL);
	t_char**             var_1106 = StringArray_Prepend           (NULL, NULL);
	t_char**             var_1107 = StringArray_Merge             (NULL, NULL);
	t_char**             var_1108 = StringArray_Join              (NULL, NULL);
	t_bool               var_1109 = StringArray_Equals            (NULL, NULL);
	t_bool               var_1110 = StringArray_Equals_N          (NULL, NULL, 0);
	t_sint               var_1111 = StringArray_Compare           (NULL, NULL, NULL);
	t_sint               var_1112 = StringArray_Compare_N         (NULL, NULL, NULL, 0);
	t_uint               var_1113 = StringArray_Count_Char        (NULL, 0);
	t_uint               var_1114 = StringArray_Count_Charset     (NULL, NULL);
	t_uint               var_1115 = StringArray_Count_String      (NULL, NULL);
	                                StringArray_Iterate           (NULL, NULL);
	                                StringArray_Iterate_I         (NULL, NULL);
	t_char**             var_1118 = StringArray_Map               (NULL, NULL);
	t_char**             var_1119 = StringArray_Map_I             (NULL, NULL);
	t_char**             var_1120 = StringArray_Filter            (NULL, NULL);
	t_char**             var_1121 = StringArray_Filter_I          (NULL, NULL);
	void*                var_1122 = StringArray_Reduce            (NULL, NULL);
	void*                var_1123 = StringArray_Reduce_I          (NULL, NULL);
	void*                var_1124 = StringArray_Fold              (NULL, NULL, NULL);
	void*                var_1125 = StringArray_Fold_I            (NULL, NULL, NULL);
	t_u8                 var_1126 = IO_GetColor                   (0);
	t_bool               var_1127 = IO_IsTerminal                 (0);
	t_fd                 var_1128 = IO_Open                       (NULL, 0, 0);
	e_cccerror           var_1129 = IO_Close                      (0);
	e_cccerror           var_1130 = IO_ChangeMode                 (NULL, 0);
	t_io_mode            var_1131 = IO_GetMode                    (NULL);
	t_sintmax            var_1132 = IO_Read_File                  (0, NULL, 0);
	t_sintmax            var_1133 = IO_Read_Filepath              (NULL, NULL);
	char*                var_1134 = IO_Read_Filepath_Text         (NULL);
	t_sintmax            var_1135 = IO_Read_Lines                 (0, NULL);
	int                  var_1136 = IO_Read_NextLine              (0, NULL);
	t_size               var_1137 = IO_Write_Char                 (0, 0);
	t_size               var_1138 = IO_Write_String               (0, NULL);
	t_size               var_1139 = IO_Write_Data                 (0, NULL, 0);
	t_size               var_1140 = IO_Write_Line                 (0, NULL);
	t_size               var_1141 = IO_Write_Lines                (0, NULL);
	t_size               var_1142 = IO_Write_Memory               (0, NULL, 0, 0);
	t_size               var_1143 = IO_Write_Format               (0, NULL);
	t_size               var_1144 = IO_Output_Char                (0);
	t_size               var_1145 = IO_Output_String              (NULL);
	t_size               var_1146 = IO_Output_Line                (NULL);
	t_size               var_1147 = IO_Output_Lines               (NULL);
	t_size               var_1148 = IO_Output_Memory              (NULL, 0, 0);
	t_size               var_1149 = IO_Output_Format              (NULL);
	                                Logger_Init                   (NULL);
	                                Logger_Exit                   (NULL);
	                                Logger_DeleteMemory           (NULL);
	t_char*              var_1153 = Logger_GetSettings            (NULL);
	e_cccerror           var_1154 = Logger_LogSettings            (NULL);
	t_char*              var_1155 = Logger_GetTimestamp           (0);
	                                Program_Abort                 ();
	                                Program_Exit                  (0);
	e_cccerror           var_1158 = Program_OnExit                (NULL);
	int                  var_1159 = Program_Run                   (NULL);
	t_char*              var_1160 = Program_GetEnv                (NULL);
	int                  var_1161 = Program_SetEnv                (NULL, NULL, 0);
	t_char*              var_1162 = Program_GetCWD                ();
	t_time               var_1163 = Time_Now                      ();
	s_date               var_1164 = Time_ToDate_UTC               (0);
	s_date               var_1165 = Time_ToDate_LocalTime         (0);
	struct timespec      var_1166 = NanoTime_ToSTDC               (NULL);
	s_nanotime           var_1167 = NanoTime_FromSTDC             (NULL);
	s_date               var_1168 = Date_Now                      ();
	t_time               var_1169 = Date_ToTime_UTC               (NULL);
	t_time               var_1170 = Date_ToTime_LocalTime         (NULL);
	struct tm            var_1171 = Date_ToSTDC                   (NULL);
	s_date               var_1172 = Date_FromSTDC                 (NULL);
	t_size               var_1173 = Date_Parse                    (NULL, NULL, NULL);
	t_size               var_1174 = Date_Parse_Min                (NULL, NULL, NULL);
	s_date               var_1175 = Date_FromString               (NULL, NULL);
	s_date               var_1176 = Date_FromString_Min           (NULL, NULL);
	t_char*              var_1177 = Date_ToString                 (NULL, NULL);
	t_size               var_1178 = Date_ToString_N               (NULL, 0, NULL, NULL);
	t_char*              var_1179 = Date_ToString_Unix            (NULL);
	t_char*              var_1180 = DateNow_ToString_Unix         ();
	t_bool               var_1181 = Date_IsValid                  (NULL);
	                                Date_MakeValid                (NULL);
	t_uint               var_1183 = Date_DaysInMonth              (0, 0);
	e_weekday            var_1184 = Date_DayOfTheWeek             (NULL);
	t_bool               var_1185 = Date_IsLeapYear               (0);
	t_bool               var_1186 = Date_HasLeapSecond            (0, 0);
	t_bool               var_1187 = ASCII_IsLetter                (0);
	t_bool               var_1188 = ASCII_IsUppercase             (0);
	t_bool               var_1189 = ASCII_IsLowercase             (0);
	t_bool               var_1190 = ASCII_IsAlphaNumeric          (0);
	t_bool               var_1191 = ASCII_IsDigit_Decimal         (0);
	t_bool               var_1192 = ASCII_IsDigit_Hexadecimal     (0);
	t_bool               var_1193 = ASCII_IsDigit_Octal           (0);
	t_bool               var_1194 = ASCII_IsDigit_Binary          (0);
	t_bool               var_1195 = ASCII_IsWhiteSpace            (0);
	t_bool               var_1196 = ASCII_IsPunctuation           (0);
	t_bool               var_1197 = ASCII_IsPrintable             (0);
	t_bool               var_1198 = ASCII_IsValid                 (0);
	t_bool               var_1199 = ASCII_IsInCharset             (0, NULL);
	t_ascii              var_1200 = ASCII_ToUppercase             (0);
	t_ascii              var_1201 = ASCII_ToLowercase             (0);
	t_bool               var_1202 = UTF32_IsLetter                (0);
	t_bool               var_1203 = UTF32_IsUppercase             (0);
	t_bool               var_1204 = UTF32_IsLowercase             (0);
	t_bool               var_1205 = UTF32_IsAlphaNumeric          (0);
	t_bool               var_1206 = UTF32_IsDigit_Decimal         (0);
	t_bool               var_1207 = UTF32_IsDigit_Hexadecimal     (0);
	t_bool               var_1208 = UTF32_IsDigit_Octal           (0);
	t_bool               var_1209 = UTF32_IsDigit_Binary          (0);
	t_bool               var_1210 = UTF32_IsWhiteSpace            (0);
	t_bool               var_1211 = UTF32_IsPunctuation           (0);
	t_bool               var_1212 = UTF32_IsPrintable             (0);
	t_bool               var_1213 = UTF32_IsASCII                 (0);
	t_bool               var_1214 = UTF32_IsValid                 (0);
	t_bool               var_1215 = UTF32_IsInCharset             (0, NULL);
	t_utf32              var_1216 = UTF32_ToUppercase             (0);
	t_utf32              var_1217 = UTF32_ToLowercase             (0);
	t_size               var_1218 = UTF32_ToUTF8                  (NULL, 0);
	t_size               var_1219 = UTF32_ToUTF16                 (NULL, 0);
	t_utf32              var_1220 = UTF32_FromUTF8                (NULL);
	t_utf32              var_1221 = UTF32_FromUTF16               (NULL);
	t_utf32              var_1222 = UTF32_FromEscape              (NULL);
	t_size               var_1223 = UTF32_Parse                   (NULL, NULL, 0);
	t_sint               var_1224 = UTF8_ByteOrderMark            (NULL);
	t_sint               var_1225 = UTF16_ByteOrderMark           (NULL);
	t_sint               var_1226 = UTF32_ByteOrderMark           (NULL);
}
