// This is a generated source file: see ./mkfile/rules/test-simple.mk for more info

#include <libccc.h>
#include <libccc/bool.h>
#include <libccc/char.h>
#include <libccc/encode/common.h>
#include <libccc/encode/json.h>
#include <libccc/encode/toml.h>
#include <libccc/fixed.h>
#include <libccc/float.h>
#include <libccc/format.h>
#include <libccc/image/color.h>
#include <libccc/int.h>
#include <libccc/math.h>
#include <libccc/math/algebra.h>
#include <libccc/math/algebra/interval.h>
#include <libccc/math/algebra/matrix.h>
#include <libccc/math/algebra/vector.h>
#include <libccc/math/complex.h>
#include <libccc/math/constants.h>
#include <libccc/math/fixed.h>
#include <libccc/math/float.h>
#include <libccc/math/int.h>
#include <libccc/math/sort.h>
#include <libccc/math/stat.h>
#include <libccc/math/vlq.h>
#include <libccc/memory.h>
#include <libccc/monad/array.c>
#include <libccc/monad/dict.c>
#include <libccc/monad/hashmap.c>
#include <libccc/monad/list.c>
#include <libccc/monad/queue.c>
#include <libccc/monad/stack.c>
#include <libccc/monad/tree.c>
#include <libccc/pointer.h>
#include <libccc/pointerarray.h>
#include <libccc/random/csprng.h>
#include <libccc/random/prng.h>
#include <libccc/random/random.h>
#include <libccc/string.h>
#include <libccc/stringarray.h>
#include <libccc/sys/ansi.h>
#include <libccc/sys/error.h>
#include <libccc/sys/io.h>
#include <libccc/sys/logger.h>
#include <libccc/sys/program.h>
#include <libccc/sys/time.h>
#include <libccc/text/ascii.h>
#include <libccc/text/regex.h>
#include <libccc/text/unicode.h>
#include <libccc_config.h>
#include <libccc_define.h>
#include <libccc_errors.h>
#include <libccc_naming.h>
#define T_TYPE	t_sint
#define T_NAME	int
#define T_NULL	0
#include <libccc/monad/array.c>
#define T_TYPE	t_float
#define T_NAME	float
#define T_NULL	0.0
#include <libccc/monad/array.c>

int main()
{
	t_char*              var_0001 = Bool_ToString                 (0, 0);
	t_size               var_0002 = Bool_Parse                    (NULL, NULL);
	t_bool               var_0003 = Bool_FromString               (NULL);
	                                KVT_Print_UpdateOffset        (NULL);
	t_utf8*              var_0005 = KVT_Print_EnsureBuffer        (NULL, 0);
	s_kvt*               var_0006 = KVT_Item                      ();
	s_kvt*               var_0007 = KVT_Duplicate                 (NULL, 0);
	t_bool               var_0008 = KVT_Equals                    (NULL, NULL, 0);
	s_kvt*               var_0009 = KVT_CreateNull                ();
	s_kvt*               var_0010 = KVT_CreateBoolean             (0);
	s_kvt*               var_0011 = KVT_CreateInteger             (0);
	s_kvt*               var_0012 = KVT_CreateFloat               (0);
	s_kvt*               var_0013 = KVT_CreateString              (NULL);
	s_kvt*               var_0014 = KVT_CreateArray               ();
	s_kvt*               var_0015 = KVT_CreateObject              ();
	s_kvt*               var_0016 = KVT_CreateRaw                 (NULL);
	s_kvt*               var_0017 = KVT_CreateStringReference     (NULL);
	s_kvt*               var_0018 = KVT_CreateArrayReference      (NULL);
	s_kvt*               var_0019 = KVT_CreateObjectReference     (NULL);
	s_kvt*               var_0020 = KVT_CreateArray_Boolean       (NULL, 0);
	s_kvt*               var_0021 = KVT_CreateArray_UInt          (NULL, 0);
	s_kvt*               var_0022 = KVT_CreateArray_U8            (NULL, 0);
	s_kvt*               var_0023 = KVT_CreateArray_U16           (NULL, 0);
	s_kvt*               var_0024 = KVT_CreateArray_U32           (NULL, 0);
	s_kvt*               var_0025 = KVT_CreateArray_U64           (NULL, 0);
	s_kvt*               var_0026 = KVT_CreateArray_SInt          (NULL, 0);
	s_kvt*               var_0027 = KVT_CreateArray_S8            (NULL, 0);
	s_kvt*               var_0028 = KVT_CreateArray_S16           (NULL, 0);
	s_kvt*               var_0029 = KVT_CreateArray_S32           (NULL, 0);
	s_kvt*               var_0030 = KVT_CreateArray_S64           (NULL, 0);
	s_kvt*               var_0031 = KVT_CreateArray_Float         (NULL, 0);
	s_kvt*               var_0032 = KVT_CreateArray_F32           (NULL, 0);
	s_kvt*               var_0033 = KVT_CreateArray_F64           (NULL, 0);
	s_kvt*               var_0034 = KVT_CreateArray_String        (NULL, 0);
	t_sint               var_0035 = KVT_GetArrayLength            (NULL);
	s_kvt*               var_0036 = KVT_GetArrayItem              (NULL, 0);
	t_bool               var_0037 = KVT_GetValue_Boolean          (NULL);
	t_s64                var_0038 = KVT_GetValue_Integer          (NULL);
	t_f64                var_0039 = KVT_GetValue_Float            (NULL);
	t_char*              var_0040 = KVT_GetValue_String           (NULL);
	e_cccerror           var_0041 = KVT_SetValue_Boolean          (NULL, 0);
	e_cccerror           var_0042 = KVT_SetValue_Integer          (NULL, 0);
	e_cccerror           var_0043 = KVT_SetValue_Float            (NULL, 0);
	e_cccerror           var_0044 = KVT_SetValue_String           (NULL, NULL);
	e_cccerror           var_0045 = KVT_AddToArray_Item           (NULL, NULL);
	e_cccerror           var_0046 = KVT_AddToArray_ItemReference  (NULL, NULL);
	e_cccerror           var_0047 = KVT_AddToObject_Item          (NULL, NULL, NULL);
	e_cccerror           var_0048 = KVT_AddToObject_ItemReference (NULL, NULL, NULL);
	s_kvt*               var_0049 = KVT_AddToObject_Null          (NULL, NULL);
	s_kvt*               var_0050 = KVT_AddToObject_Boolean       (NULL, NULL, 0);
	s_kvt*               var_0051 = KVT_AddToObject_Integer       (NULL, NULL, 0);
	s_kvt*               var_0052 = KVT_AddToObject_Float         (NULL, NULL, 0);
	s_kvt*               var_0053 = KVT_AddToObject_String        (NULL, NULL, NULL);
	s_kvt*               var_0054 = KVT_AddToObject_Object        (NULL, NULL);
	s_kvt*               var_0055 = KVT_AddToObject_Array         (NULL, NULL);
	s_kvt*               var_0056 = KVT_AddToObject_Raw           (NULL, NULL, NULL);
	t_bool               var_0057 = KVT_IsInvalid                 (NULL);
	t_bool               var_0058 = KVT_IsNull                    (NULL);
	t_bool               var_0059 = KVT_IsBoolean                 (NULL);
	t_bool               var_0060 = KVT_IsInteger                 (NULL);
	t_bool               var_0061 = KVT_IsFloat                   (NULL);
	t_bool               var_0062 = KVT_IsString                  (NULL);
	t_bool               var_0063 = KVT_IsArray                   (NULL);
	t_bool               var_0064 = KVT_IsObject                  (NULL);
	t_bool               var_0065 = KVT_IsRaw                     (NULL);
	e_cccerror           var_0066 = KVT_Delete                    (NULL);
	s_kvt*               var_0067 = KVT_Detach                    (NULL, NULL);
	e_cccerror           var_0068 = KVT_Replace                   (NULL, NULL, NULL);
	e_cccerror           var_0069 = KVT_Delete_FromArray          (NULL, 0);
	s_kvt*               var_0070 = KVT_Detach_FromArray          (NULL, 0);
	e_cccerror           var_0071 = KVT_Replace_InArray           (NULL, 0, NULL);
	e_cccerror           var_0072 = KVT_Insert_InArray            (NULL, 0, NULL);
	s_kvt*               var_0073 = KVT_Concat                    (NULL, NULL);
	s_kvt*               var_0074 = KVT_Concat_Array              (NULL, NULL);
	s_kvt*               var_0075 = KVT_Concat_Object             (NULL, NULL);
	s_kvt*               var_0076 = KVT_Merge                     (NULL, NULL, 0);
	t_size               var_0077 = JSON_Parse_Lenient            (NULL, NULL, 0);
	s_json*              var_0078 = JSON_FromString_Lenient       (NULL);
	t_size               var_0079 = JSON_Parse_Strict             (NULL, NULL, 0);
	s_json*              var_0080 = JSON_FromString_Strict        (NULL);
	t_size               var_0081 = JSON_Print_Pretty             (NULL, NULL, 0);
	t_utf8*              var_0082 = JSON_ToString_Pretty          (NULL);
	t_size               var_0083 = JSON_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0084 = JSON_ToString_Minify          (NULL);
	t_size               var_0085 = TOML_Parse_Lenient            (NULL, NULL, 0);
	s_toml*              var_0086 = TOML_FromString_Lenient       (NULL);
	t_size               var_0087 = TOML_Parse_Strict             (NULL, NULL, 0);
	s_toml*              var_0088 = TOML_FromString_Strict        (NULL);
	t_size               var_0089 = TOML_Print_Pretty             (NULL, NULL, 0);
	t_size               var_0090 = TOML_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0091 = TOML_ToString_Pretty          (NULL);
	t_utf8*              var_0092 = TOML_ToString_Minify          (NULL);
	t_q16                var_0093 = Q16_FromInt                   (0);
	t_q32                var_0094 = Q32_FromInt                   (0);
	t_q64                var_0095 = Q64_FromInt                   (0);
	t_q16                var_0096 = Q16_FromFixed                 (0);
	t_q32                var_0097 = Q32_FromFixed                 (0);
	t_q64                var_0098 = Q64_FromFixed                 (0);
	t_q16                var_0099 = Q16_FromFloat                 (0);
	t_q32                var_0100 = Q32_FromFloat                 (0);
	t_q64                var_0101 = Q64_FromFloat                 (0);
	t_q16                var_0102 = Q16_From                      (0, 0);
	t_q32                var_0103 = Q32_From                      (0, 0);
	t_q64                var_0104 = Q64_From                      (0, 0);
	t_s16                var_0105 = Q16_IntegerPart               (0);
	t_s32                var_0106 = Q32_IntegerPart               (0);
	t_s64                var_0107 = Q64_IntegerPart               (0);
	t_s16                var_0108 = Q16_FractionPart              (0);
	t_s32                var_0109 = Q32_FractionPart              (0);
	t_s64                var_0110 = Q64_FractionPart              (0);
	t_size               var_0111 = Q16_Parse                     (NULL, NULL, 0);
	t_size               var_0112 = Q32_Parse                     (NULL, NULL, 0);
	t_size               var_0113 = Q64_Parse                     (NULL, NULL, 0);
	t_size               var_0114 = Q16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0115 = Q32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0116 = Q64_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0117 = Q16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0118 = Q32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0119 = Q64_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0120 = Q16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0121 = Q32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0122 = Q64_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0123 = Q16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0124 = Q32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0125 = Q64_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0126 = Q16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0127 = Q32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0128 = Q64_Parse_Base                (NULL, NULL, NULL, 0);
	t_f32                var_0129 = F32_FromInt                   (0);
	t_f64                var_0130 = F64_FromInt                   (0);
	t_f32                var_0131 = F32_FromFixed                 (0);
	t_f64                var_0132 = F64_FromFixed                 (0);
	t_f32                var_0133 = F32_FromFloat                 (0);
	t_f64                var_0134 = F64_FromFloat                 (0);
	t_f32                var_0135 = F32_From                      (0, 0);
	t_f64                var_0136 = F64_From                      (0, 0);
	t_sint               var_0137 = F32_GetExp2                   (0);
	t_sint               var_0138 = F64_GetExp2                   (0);
	t_sint               var_0139 = F32_GetExp10                  (0);
	t_sint               var_0140 = F64_GetExp10                  (0);
	t_char*              var_0141 = F32_ToString                  (0, 0);
	t_char*              var_0142 = F64_ToString                  (0, 0);
	t_char*              var_0143 = F32_ToString_Exp              (0, 0);
	t_char*              var_0144 = F64_ToString_Exp              (0, 0);
	t_char*              var_0145 = F32_ToString_Dec              (0, 0);
	t_char*              var_0146 = F64_ToString_Dec              (0, 0);
	t_char*              var_0147 = F32_ToString_Hex              (0, 0);
	t_char*              var_0148 = F64_ToString_Hex              (0, 0);
	t_char*              var_0149 = F32_ToString_Bin              (0, 0);
	t_char*              var_0150 = F64_ToString_Bin              (0, 0);
	t_size               var_0151 = F32_Parse                     (NULL, NULL, 0);
	t_size               var_0152 = F64_Parse                     (NULL, NULL, 0);
	t_f32                var_0153 = F32_FromString                (NULL);
	t_f64                var_0154 = F64_FromString                (NULL);
	t_size               var_0155 = F32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0156 = F64_Parse_Dec                 (NULL, NULL, 0);
	t_f32                var_0157 = F32_FromString_Dec            (NULL);
	t_f64                var_0158 = F64_FromString_Dec            (NULL);
	t_size               var_0159 = F32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0160 = F64_Parse_Hex                 (NULL, NULL, 0);
	t_f32                var_0161 = F32_FromString_Hex            (NULL);
	t_f64                var_0162 = F64_FromString_Hex            (NULL);
	t_size               var_0163 = F32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0164 = F64_Parse_Oct                 (NULL, NULL, 0);
	t_f32                var_0165 = F32_FromString_Oct            (NULL);
	t_f64                var_0166 = F64_FromString_Oct            (NULL);
	t_size               var_0167 = F32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0168 = F64_Parse_Bin                 (NULL, NULL, 0);
	t_f32                var_0169 = F32_FromString_Bin            (NULL);
	t_f64                var_0170 = F64_FromString_Bin            (NULL);
	t_char*              var_0171 = String_Format                 (NULL);
	t_char*              var_0172 = String_Format_VA              (NULL, 0);
	t_size               var_0173 = String_Format_N               (NULL, 0, NULL);
	t_size               var_0174 = String_Format_N_VA            (NULL, 0, NULL, 0);
	t_u8                 var_0175 = Color_ARGB16_Get_A            (0);
	t_u8                 var_0176 = Color_ARGB16_Get_R            (0);
	t_u8                 var_0177 = Color_ARGB16_Get_G            (0);
	t_u8                 var_0178 = Color_ARGB16_Get_B            (0);
	t_argb16             var_0179 = Color_ARGB16_Set              (0, 0, 0, 0);
	t_argb16             var_0180 = Color_ARGB16_Set_A            (0, 0);
	t_argb16             var_0181 = Color_ARGB16_Set_R            (0, 0);
	t_argb16             var_0182 = Color_ARGB16_Set_G            (0, 0);
	t_argb16             var_0183 = Color_ARGB16_Set_B            (0, 0);
	t_argb32             var_0184 = Color_ARGB16_To_ARGB32        (0);
	s_argb               var_0185 = Color_ARGB16_To_ARGB          (0);
	t_u16                var_0186 = Color_ARGB16_Difference       (0, 0);
	t_argb16 const*      var_0187 = Color_ARGB16_GetNearest       (0, NULL, 0);
	t_u8                 var_0188 = Color_ARGB32_Get_A            (0);
	t_u8                 var_0189 = Color_ARGB32_Get_R            (0);
	t_u8                 var_0190 = Color_ARGB32_Get_G            (0);
	t_u8                 var_0191 = Color_ARGB32_Get_B            (0);
	t_argb32             var_0192 = Color_ARGB32_Set              (0, 0, 0, 0);
	t_argb32             var_0193 = Color_ARGB32_Set_A            (0, 0);
	t_argb32             var_0194 = Color_ARGB32_Set_R            (0, 0);
	t_argb32             var_0195 = Color_ARGB32_Set_G            (0, 0);
	t_argb32             var_0196 = Color_ARGB32_Set_B            (0, 0);
	t_argb16             var_0197 = Color_ARGB32_To_ARGB16        (0);
	s_argb               var_0198 = Color_ARGB32_To_ARGB          (0);
	t_u32                var_0199 = Color_ARGB32_Difference       (0, 0);
	t_argb32 const*      var_0200 = Color_ARGB32_GetNearest       (0, NULL, 0);
	s_argb               var_0201 = Color_ARGB_Set                (0, 0, 0, 0);
	                                Color_ARGB_Set_A              (NULL, 0);
	                                Color_ARGB_Set_R              (NULL, 0);
	                                Color_ARGB_Set_G              (NULL, 0);
	                                Color_ARGB_Set_B              (NULL, 0);
	t_argb16             var_0206 = Color_ARGB_To_ARGB16          (NULL);
	t_argb32             var_0207 = Color_ARGB_To_ARGB32          (NULL);
	s_ahsl               var_0208 = Color_ARGB_To_AHSL            (NULL);
	s_argb const*        var_0209 = Color_ARGB_GetNearest         ((s_argb){0}, NULL, 0);
	s_ahsl               var_0210 = Color_AHSL_Set                (0, 0, 0, 0);
	                                Color_AHSL_Set_A              (NULL, 0);
	                                Color_AHSL_Set_H              (NULL, 0);
	                                Color_AHSL_Set_S              (NULL, 0);
	                                Color_AHSL_Set_L              (NULL, 0);
	s_argb               var_0215 = Color_AHSL_To_ARGB            (NULL);
	s_ahsl const*        var_0216 = Color_AHSL_GetNearest         ((s_ahsl){0}, NULL, 0);
	t_char*              var_0217 = U8_ToString                   (0);
	t_char*              var_0218 = U16_ToString                  (0);
	t_char*              var_0219 = U32_ToString                  (0);
	t_char*              var_0220 = U64_ToString                  (0);
	t_char*              var_0221 = S8_ToString                   (0);
	t_char*              var_0222 = S16_ToString                  (0);
	t_char*              var_0223 = S32_ToString                  (0);
	t_char*              var_0224 = S64_ToString                  (0);
	t_char*              var_0225 = U8_ToString_Dec               (0);
	t_char*              var_0226 = U16_ToString_Dec              (0);
	t_char*              var_0227 = U32_ToString_Dec              (0);
	t_char*              var_0228 = U64_ToString_Dec              (0);
	t_char*              var_0229 = S8_ToString_Dec               (0);
	t_char*              var_0230 = S16_ToString_Dec              (0);
	t_char*              var_0231 = S32_ToString_Dec              (0);
	t_char*              var_0232 = S64_ToString_Dec              (0);
	t_char*              var_0233 = U8_ToString_Hex               (0, 0);
	t_char*              var_0234 = U16_ToString_Hex              (0, 0);
	t_char*              var_0235 = U32_ToString_Hex              (0, 0);
	t_char*              var_0236 = U64_ToString_Hex              (0, 0);
	t_char*              var_0237 = S8_ToString_Hex               (0, 0);
	t_char*              var_0238 = S16_ToString_Hex              (0, 0);
	t_char*              var_0239 = S32_ToString_Hex              (0, 0);
	t_char*              var_0240 = S64_ToString_Hex              (0, 0);
	t_char*              var_0241 = U8_ToString_Oct               (0, 0);
	t_char*              var_0242 = U16_ToString_Oct              (0, 0);
	t_char*              var_0243 = U32_ToString_Oct              (0, 0);
	t_char*              var_0244 = U64_ToString_Oct              (0, 0);
	t_char*              var_0245 = S8_ToString_Oct               (0, 0);
	t_char*              var_0246 = S16_ToString_Oct              (0, 0);
	t_char*              var_0247 = S32_ToString_Oct              (0, 0);
	t_char*              var_0248 = S64_ToString_Oct              (0, 0);
	t_char*              var_0249 = U8_ToString_Bin               (0, 0);
	t_char*              var_0250 = U16_ToString_Bin              (0, 0);
	t_char*              var_0251 = U32_ToString_Bin              (0, 0);
	t_char*              var_0252 = U64_ToString_Bin              (0, 0);
	t_char*              var_0253 = S8_ToString_Bin               (0, 0);
	t_char*              var_0254 = S16_ToString_Bin              (0, 0);
	t_char*              var_0255 = S32_ToString_Bin              (0, 0);
	t_char*              var_0256 = S64_ToString_Bin              (0, 0);
	t_char*              var_0257 = U8_ToString_Base              (0, NULL);
	t_char*              var_0258 = U16_ToString_Base             (0, NULL);
	t_char*              var_0259 = U32_ToString_Base             (0, NULL);
	t_char*              var_0260 = U64_ToString_Base             (0, NULL);
	t_char*              var_0261 = S8_ToString_Base              (0, NULL);
	t_char*              var_0262 = S16_ToString_Base             (0, NULL);
	t_char*              var_0263 = S32_ToString_Base             (0, NULL);
	t_char*              var_0264 = S64_ToString_Base             (0, NULL);
	t_size               var_0265 = U8_Parse                      (NULL, NULL, 0);
	t_size               var_0266 = U16_Parse                     (NULL, NULL, 0);
	t_size               var_0267 = U32_Parse                     (NULL, NULL, 0);
	t_size               var_0268 = U64_Parse                     (NULL, NULL, 0);
	t_u8                 var_0269 = U8_FromString                 (NULL);
	t_u16                var_0270 = U16_FromString                (NULL);
	t_u32                var_0271 = U32_FromString                (NULL);
	t_u64                var_0272 = U64_FromString                (NULL);
	t_size               var_0273 = S8_Parse                      (NULL, NULL, 0);
	t_size               var_0274 = S16_Parse                     (NULL, NULL, 0);
	t_size               var_0275 = S32_Parse                     (NULL, NULL, 0);
	t_size               var_0276 = S64_Parse                     (NULL, NULL, 0);
	t_s8                 var_0277 = S8_FromString                 (NULL);
	t_s16                var_0278 = S16_FromString                (NULL);
	t_s32                var_0279 = S32_FromString                (NULL);
	t_s64                var_0280 = S64_FromString                (NULL);
	t_size               var_0281 = U8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0282 = U16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0283 = U32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0284 = U64_Parse_Dec                 (NULL, NULL, 0);
	t_u8                 var_0285 = U8_FromString_Dec             (NULL);
	t_u16                var_0286 = U16_FromString_Dec            (NULL);
	t_u32                var_0287 = U32_FromString_Dec            (NULL);
	t_u64                var_0288 = U64_FromString_Dec            (NULL);
	t_size               var_0289 = S8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0290 = S16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0291 = S32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0292 = S64_Parse_Dec                 (NULL, NULL, 0);
	t_s8                 var_0293 = S8_FromString_Dec             (NULL);
	t_s16                var_0294 = S16_FromString_Dec            (NULL);
	t_s32                var_0295 = S32_FromString_Dec            (NULL);
	t_s64                var_0296 = S64_FromString_Dec            (NULL);
	t_size               var_0297 = U8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0298 = U16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0299 = U32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0300 = U64_Parse_Hex                 (NULL, NULL, 0);
	t_u8                 var_0301 = U8_FromString_Hex             (NULL);
	t_u16                var_0302 = U16_FromString_Hex            (NULL);
	t_u32                var_0303 = U32_FromString_Hex            (NULL);
	t_u64                var_0304 = U64_FromString_Hex            (NULL);
	t_size               var_0305 = S8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0306 = S16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0307 = S32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0308 = S64_Parse_Hex                 (NULL, NULL, 0);
	t_s8                 var_0309 = S8_FromString_Hex             (NULL);
	t_s16                var_0310 = S16_FromString_Hex            (NULL);
	t_s32                var_0311 = S32_FromString_Hex            (NULL);
	t_s64                var_0312 = S64_FromString_Hex            (NULL);
	t_size               var_0313 = U8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0314 = U16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0315 = U32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0316 = U64_Parse_Oct                 (NULL, NULL, 0);
	t_u8                 var_0317 = U8_FromString_Oct             (NULL);
	t_u16                var_0318 = U16_FromString_Oct            (NULL);
	t_u32                var_0319 = U32_FromString_Oct            (NULL);
	t_u64                var_0320 = U64_FromString_Oct            (NULL);
	t_size               var_0321 = S8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0322 = S16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0323 = S32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0324 = S64_Parse_Oct                 (NULL, NULL, 0);
	t_s8                 var_0325 = S8_FromString_Oct             (NULL);
	t_s16                var_0326 = S16_FromString_Oct            (NULL);
	t_s32                var_0327 = S32_FromString_Oct            (NULL);
	t_s64                var_0328 = S64_FromString_Oct            (NULL);
	t_size               var_0329 = U8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0330 = U16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0331 = U32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0332 = U64_Parse_Bin                 (NULL, NULL, 0);
	t_u8                 var_0333 = U8_FromString_Bin             (NULL);
	t_u16                var_0334 = U16_FromString_Bin            (NULL);
	t_u32                var_0335 = U32_FromString_Bin            (NULL);
	t_u64                var_0336 = U64_FromString_Bin            (NULL);
	t_size               var_0337 = S8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0338 = S16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0339 = S32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0340 = S64_Parse_Bin                 (NULL, NULL, 0);
	t_s8                 var_0341 = S8_FromString_Bin             (NULL);
	t_s16                var_0342 = S16_FromString_Bin            (NULL);
	t_s32                var_0343 = S32_FromString_Bin            (NULL);
	t_s64                var_0344 = S64_FromString_Bin            (NULL);
	t_size               var_0345 = U8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0346 = U16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0347 = U32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0348 = U64_Parse_Base                (NULL, NULL, NULL, 0);
	t_u8                 var_0349 = U8_FromString_Base            (NULL, NULL);
	t_u16                var_0350 = U16_FromString_Base           (NULL, NULL);
	t_u32                var_0351 = U32_FromString_Base           (NULL, NULL);
	t_u64                var_0352 = U64_FromString_Base           (NULL, NULL);
	t_size               var_0353 = S8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0354 = S16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0355 = S32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0356 = S64_Parse_Base                (NULL, NULL, NULL, 0);
	t_s8                 var_0357 = S8_FromString_Base            (NULL, NULL);
	t_s16                var_0358 = S16_FromString_Base           (NULL, NULL);
	t_s32                var_0359 = S32_FromString_Base           (NULL, NULL);
	t_s64                var_0360 = S64_FromString_Base           (NULL, NULL);
	t_float              var_0361 = c_integrate                   (0, (s_interval){0}, 0);
	t_float              var_0362 = c_mc_integrate_1d             (0, (s_box1d){0});
	t_float              var_0363 = c_mc_integrate_2d             (0, (s_box2d){0});
	t_float              var_0364 = c_mc_integrate_3d             (0, (s_box3d){0});
	t_float              var_0365 = c_mc_integrate_4d             (0, (s_box4d){0});
	t_float              var_0366 = c_distance_float              (0, 0);
	t_f32                var_0367 = c_distance_f32                (0, 0);
	t_f64                var_0368 = c_distance_f64                (0, 0);
	t_uint               var_0369 = c_distance_uint               (0, 0);
	t_u8                 var_0370 = c_distance_u8                 (0, 0);
	t_u16                var_0371 = c_distance_u16                (0, 0);
	t_u32                var_0372 = c_distance_u32                (0, 0);
	t_u64                var_0373 = c_distance_u64                (0, 0);
	t_sint               var_0374 = c_distance_int                (0, 0);
	t_s8                 var_0375 = c_distance_s8                 (0, 0);
	t_s16                var_0376 = c_distance_s16                (0, 0);
	t_s32                var_0377 = c_distance_s32                (0, 0);
	t_s64                var_0378 = c_distance_s64                (0, 0);
	s_matrix2d           var_0379 = Matrix2D                      (NULL, NULL);
	s_matrix2d*          var_0380 = Matrix2D_New                  (NULL, NULL);
	t_bool               var_0381 = Matrix2D_Equals               (NULL, NULL);
	s_vector2d           var_0382 = Matrix2D_Apply                (NULL, NULL);
	t_float              var_0383 = Matrix2D_Determinant          (NULL);
	s_matrix2d           var_0384 = Matrix2D_Inverse              (NULL);
	s_matrix2d           var_0385 = Matrix2D_Transpose            (NULL);
	s_matrix2d           var_0386 = Matrix2D_Multiply             (NULL, NULL);
	s_matrix3d           var_0387 = Matrix3D                      (NULL, NULL, NULL);
	s_matrix3d*          var_0388 = Matrix3D_New                  (NULL, NULL, NULL);
	t_bool               var_0389 = Matrix3D_Equals               (NULL, NULL);
	s_vector3d           var_0390 = Matrix3D_Apply                (NULL, NULL);
	t_float              var_0391 = Matrix3D_Determinant          (NULL);
	s_matrix3d           var_0392 = Matrix3D_Inverse              (NULL);
	s_matrix3d           var_0393 = Matrix3D_Transpose            (NULL);
	s_matrix3d           var_0394 = Matrix3D_Multiply             (NULL, NULL);
	s_vector2d           var_0395 = Vector2D                      (0, 0);
	s_vector2d*          var_0396 = Vector2D_New                  (0, 0);
	t_bool               var_0397 = Vector2D_Equals               (NULL, NULL);
	s_vector2d           var_0398 = Vector2D_Scale                (NULL, 0);
	s_vector2d           var_0399 = Vector2D_Invert               (NULL);
	t_float              var_0400 = Vector2D_Norm                 (NULL);
	s_vector2d           var_0401 = Vector2D_Normalize            (NULL);
	s_vector2d           var_0402 = Vector2D_Add                  (NULL, NULL);
	t_float              var_0403 = Vector2D_Dot                  (NULL, NULL);
	s_vector3d           var_0404 = Vector3D                      (0, 0, 0);
	s_vector3d*          var_0405 = Vector3D_New                  (0, 0, 0);
	t_bool               var_0406 = Vector3D_Equals               (NULL, NULL);
	s_vector3d           var_0407 = Vector3D_Scale                (NULL, 0);
	s_vector3d           var_0408 = Vector3D_Invert               (NULL);
	t_float              var_0409 = Vector3D_Norm                 (NULL);
	s_vector3d           var_0410 = Vector3D_Normalize            (NULL);
	s_vector3d           var_0411 = Vector3D_Add                  (NULL, NULL);
	t_float              var_0412 = Vector3D_Dot                  (NULL, NULL);
	s_vector3d           var_0413 = Vector3D_Cross                (NULL, NULL);
	s_complex            var_0414 = Complex                       (0, 0);
	s_complex*           var_0415 = Complex_New                   (0, 0);
	t_bool               var_0416 = Complex_Equals                (NULL, NULL);
	t_float              var_0417 = Complex_Abs                   (NULL);
	s_complex            var_0418 = Complex_Conjugate             (NULL);
	s_complex            var_0419 = Complex_Add                   (NULL, NULL);
	s_complex            var_0420 = Complex_Sub                   (NULL, NULL);
	s_complex            var_0421 = Complex_Mul                   (NULL, NULL);
	s_complex            var_0422 = Complex_Div                   (NULL, NULL);
	s_complex            var_0423 = Complex_Pow                   (NULL, 0);
	t_q16                var_0424 = Q16_Abs                       (0);
	t_q32                var_0425 = Q32_Abs                       (0);
	t_q64                var_0426 = Q64_Abs                       (0);
	t_q16                var_0427 = Q16_Round                     (0);
	t_q32                var_0428 = Q32_Round                     (0);
	t_q64                var_0429 = Q64_Round                     (0);
	t_q16                var_0430 = Q16_Trunc                     (0);
	t_q32                var_0431 = Q32_Trunc                     (0);
	t_q64                var_0432 = Q64_Trunc                     (0);
	t_q16                var_0433 = Q16_Floor                     (0);
	t_q32                var_0434 = Q32_Floor                     (0);
	t_q64                var_0435 = Q64_Floor                     (0);
	t_q16                var_0436 = Q16_Ceil                      (0);
	t_q32                var_0437 = Q32_Ceil                      (0);
	t_q64                var_0438 = Q64_Ceil                      (0);
	t_bool               var_0439 = Q16_Equals                    (0, 0);
	t_bool               var_0440 = Q32_Equals                    (0, 0);
	t_bool               var_0441 = Q64_Equals                    (0, 0);
	t_bool               var_0442 = Q16_EqualsApprox              (0, 0);
	t_bool               var_0443 = Q32_EqualsApprox              (0, 0);
	t_bool               var_0444 = Q64_EqualsApprox              (0, 0);
	t_q16                var_0445 = Q16_Add                       (0, 0);
	t_q32                var_0446 = Q32_Add                       (0, 0);
	t_q64                var_0447 = Q64_Add                       (0, 0);
	t_q16                var_0448 = Q16_Sub                       (0, 0);
	t_q32                var_0449 = Q32_Sub                       (0, 0);
	t_q64                var_0450 = Q64_Sub                       (0, 0);
	t_q16                var_0451 = Q16_Mul                       (0, 0);
	t_q32                var_0452 = Q32_Mul                       (0, 0);
	t_q64                var_0453 = Q64_Mul                       (0, 0);
	t_q16                var_0454 = Q16_Div                       (0, 0);
	t_q32                var_0455 = Q32_Div                       (0, 0);
	t_q64                var_0456 = Q64_Div                       (0, 0);
	t_q16                var_0457 = Q16_Mod                       (0, 0);
	t_q32                var_0458 = Q32_Mod                       (0, 0);
	t_q64                var_0459 = Q64_Mod                       (0, 0);
	t_q16                var_0460 = Q16_Pow                       (0, 0);
	t_q32                var_0461 = Q32_Pow                       (0, 0);
	t_q64                var_0462 = Q64_Pow                       (0, 0);
	t_q16                var_0463 = Q16_IntPow                    (0, 0);
	t_q32                var_0464 = Q32_IntPow                    (0, 0);
	t_q64                var_0465 = Q64_IntPow                    (0, 0);
	t_q16                var_0466 = Q16_Root2                     (0);
	t_q32                var_0467 = Q32_Root2                     (0);
	t_q64                var_0468 = Q64_Root2                     (0);
	t_q16                var_0469 = Q16_Root3                     (0);
	t_q32                var_0470 = Q32_Root3                     (0);
	t_q64                var_0471 = Q64_Root3                     (0);
	t_q16                var_0472 = Q16_RootN                     (0, 0);
	t_q32                var_0473 = Q32_RootN                     (0, 0);
	t_q64                var_0474 = Q64_RootN                     (0, 0);
	t_q16                var_0475 = Q16_Exp                       (0);
	t_q32                var_0476 = Q32_Exp                       (0);
	t_q64                var_0477 = Q64_Exp                       (0);
	t_q16                var_0478 = Q16_Ln                        (0);
	t_q32                var_0479 = Q32_Ln                        (0);
	t_q64                var_0480 = Q64_Ln                        (0);
	t_q16                var_0481 = Q16_Log2                      (0);
	t_q32                var_0482 = Q32_Log2                      (0);
	t_q64                var_0483 = Q64_Log2                      (0);
	t_q16                var_0484 = Q16_Log10                     (0);
	t_q32                var_0485 = Q32_Log10                     (0);
	t_q64                var_0486 = Q64_Log10                     (0);
	t_q16                var_0487 = Q16_LogN                      (0, 0);
	t_q32                var_0488 = Q32_LogN                      (0, 0);
	t_q64                var_0489 = Q64_LogN                      (0, 0);
	t_q16                var_0490 = Q16_Cos                       (0);
	t_q32                var_0491 = Q32_Cos                       (0);
	t_q64                var_0492 = Q64_Cos                       (0);
	t_q16                var_0493 = Q16_Sin                       (0);
	t_q32                var_0494 = Q32_Sin                       (0);
	t_q64                var_0495 = Q64_Sin                       (0);
	t_q16                var_0496 = Q16_Tan                       (0);
	t_q32                var_0497 = Q32_Tan                       (0);
	t_q64                var_0498 = Q64_Tan                       (0);
	t_q16                var_0499 = Q16_ArcCos                    (0);
	t_q32                var_0500 = Q32_ArcCos                    (0);
	t_q64                var_0501 = Q64_ArcCos                    (0);
	t_q16                var_0502 = Q16_ArcSin                    (0);
	t_q32                var_0503 = Q32_ArcSin                    (0);
	t_q64                var_0504 = Q64_ArcSin                    (0);
	t_q16                var_0505 = Q16_ArcTan                    (0);
	t_q32                var_0506 = Q32_ArcTan                    (0);
	t_q64                var_0507 = Q64_ArcTan                    (0);
	t_q16                var_0508 = Q16_                          (0, 0);
	t_q32                var_0509 = Q32_                          (0, 0);
	t_q64                var_0510 = Q64_                          (0, 0);
	t_q16                var_0511 = Q16_CosH                      (0);
	t_q32                var_0512 = Q32_CosH                      (0);
	t_q64                var_0513 = Q64_CosH                      (0);
	t_q16                var_0514 = Q16_SinH                      (0);
	t_q32                var_0515 = Q32_SinH                      (0);
	t_q64                var_0516 = Q64_SinH                      (0);
	t_q16                var_0517 = Q16_TanH                      (0);
	t_q32                var_0518 = Q32_TanH                      (0);
	t_q64                var_0519 = Q64_TanH                      (0);
	t_q16                var_0520 = Q16_InvCosH                   (0);
	t_q32                var_0521 = Q32_InvCosH                   (0);
	t_q64                var_0522 = Q64_InvCosH                   (0);
	t_q16                var_0523 = Q16_InvSinH                   (0);
	t_q32                var_0524 = Q32_InvSinH                   (0);
	t_q64                var_0525 = Q64_InvSinH                   (0);
	t_q16                var_0526 = Q16_InvTanH                   (0);
	t_q32                var_0527 = Q32_InvTanH                   (0);
	t_q64                var_0528 = Q64_InvTanH                   (0);
	t_f32                var_0529 = F32_Abs                       (0);
	t_f64                var_0530 = F64_Abs                       (0);
	t_f32                var_0531 = F32_Round                     (0);
	t_f64                var_0532 = F64_Round                     (0);
	t_f32                var_0533 = F32_Trunc                     (0);
	t_f64                var_0534 = F64_Trunc                     (0);
	t_f32                var_0535 = F32_Floor                     (0);
	t_f64                var_0536 = F64_Floor                     (0);
	t_f32                var_0537 = F32_Ceil                      (0);
	t_f64                var_0538 = F64_Ceil                      (0);
	t_bool               var_0539 = F32_Equals                    (0, 0);
	t_bool               var_0540 = F64_Equals                    (0, 0);
	t_bool               var_0541 = F32_EqualsApprox              (0, 0);
	t_bool               var_0542 = F64_EqualsApprox              (0, 0);
	t_f32                var_0543 = F32_Add                       (0, 0);
	t_f64                var_0544 = F64_Add                       (0, 0);
	t_f32                var_0545 = F32_Sub                       (0, 0);
	t_f64                var_0546 = F64_Sub                       (0, 0);
	t_f32                var_0547 = F32_Mul                       (0, 0);
	t_f64                var_0548 = F64_Mul                       (0, 0);
	t_f32                var_0549 = F32_Div                       (0, 0);
	t_f64                var_0550 = F64_Div                       (0, 0);
	t_f32                var_0551 = F32_Mod                       (0, 0);
	t_f64                var_0552 = F64_Mod                       (0, 0);
	t_f32                var_0553 = F32_Pow                       (0, 0);
	t_f64                var_0554 = F64_Pow                       (0, 0);
	t_f32                var_0555 = F32_IntPow                    (0, 0);
	t_f64                var_0556 = F64_IntPow                    (0, 0);
	t_f32                var_0557 = F32_Root2                     (0);
	t_f64                var_0558 = F64_Root2                     (0);
	t_f32                var_0559 = F32_Root3                     (0);
	t_f64                var_0560 = F64_Root3                     (0);
	t_f32                var_0561 = F32_RootN                     (0, 0);
	t_f64                var_0562 = F64_RootN                     (0, 0);
	t_f32                var_0563 = F32_Exp                       (0);
	t_f64                var_0564 = F64_Exp                       (0);
	t_f32                var_0565 = F32_Ln                        (0);
	t_f64                var_0566 = F64_Ln                        (0);
	t_f32                var_0567 = F32_Log2                      (0);
	t_f64                var_0568 = F64_Log2                      (0);
	t_f32                var_0569 = F32_Log10                     (0);
	t_f64                var_0570 = F64_Log10                     (0);
	t_f32                var_0571 = F32_LogN                      (0, 0);
	t_f64                var_0572 = F64_LogN                      (0, 0);
	t_f32                var_0573 = F32_Cos                       (0);
	t_f64                var_0574 = F64_Cos                       (0);
	t_f32                var_0575 = F32_Sin                       (0);
	t_f64                var_0576 = F64_Sin                       (0);
	t_f32                var_0577 = F32_Tan                       (0);
	t_f64                var_0578 = F64_Tan                       (0);
	t_f32                var_0579 = F32_ArcCos                    (0);
	t_f64                var_0580 = F64_ArcCos                    (0);
	t_f32                var_0581 = F32_ArcSin                    (0);
	t_f64                var_0582 = F64_ArcSin                    (0);
	t_f32                var_0583 = F32_ArcTan                    (0);
	t_f64                var_0584 = F64_ArcTan                    (0);
	t_f32                var_0585 = F32_ArcTan2                   (0, 0);
	t_f64                var_0586 = F64_ArcTan2                   (0, 0);
	t_f32                var_0587 = F32_CosH                      (0);
	t_f64                var_0588 = F64_CosH                      (0);
	t_f32                var_0589 = F32_SinH                      (0);
	t_f64                var_0590 = F64_SinH                      (0);
	t_f32                var_0591 = F32_TanH                      (0);
	t_f64                var_0592 = F64_TanH                      (0);
	t_f32                var_0593 = F32_InvCosH                   (0);
	t_f64                var_0594 = F64_InvCosH                   (0);
	t_f32                var_0595 = F32_InvSinH                   (0);
	t_f64                var_0596 = F64_InvSinH                   (0);
	t_f32                var_0597 = F32_InvTanH                   (0);
	t_f64                var_0598 = F64_InvTanH                   (0);
	t_s8                 var_0599 = S8_Abs                        (0);
	t_s16                var_0600 = S16_Abs                       (0);
	t_s32                var_0601 = S32_Abs                       (0);
	t_s64                var_0602 = S64_Abs                       (0);
	t_bool               var_0603 = S8_Equals                     (0, 0);
	t_bool               var_0604 = S16_Equals                    (0, 0);
	t_bool               var_0605 = S32_Equals                    (0, 0);
	t_bool               var_0606 = S64_Equals                    (0, 0);
	t_bool               var_0607 = S8_EqualsApprox               (0, 0);
	t_bool               var_0608 = S16_EqualsApprox              (0, 0);
	t_bool               var_0609 = S32_EqualsApprox              (0, 0);
	t_bool               var_0610 = S64_EqualsApprox              (0, 0);
	t_u8                 var_0611 = U8_Add                        (0, 0);
	t_u16                var_0612 = U16_Add                       (0, 0);
	t_u32                var_0613 = U32_Add                       (0, 0);
	t_u64                var_0614 = U64_Add                       (0, 0);
	t_s8                 var_0615 = S8_Add                        (0, 0);
	t_s16                var_0616 = S16_Add                       (0, 0);
	t_s32                var_0617 = S32_Add                       (0, 0);
	t_s64                var_0618 = S64_Add                       (0, 0);
	t_u8                 var_0619 = U8_Sub                        (0, 0);
	t_u16                var_0620 = U16_Sub                       (0, 0);
	t_u32                var_0621 = U32_Sub                       (0, 0);
	t_u64                var_0622 = U64_Sub                       (0, 0);
	t_s8                 var_0623 = S8_Sub                        (0, 0);
	t_s16                var_0624 = S16_Sub                       (0, 0);
	t_s32                var_0625 = S32_Sub                       (0, 0);
	t_s64                var_0626 = S64_Sub                       (0, 0);
	t_u8                 var_0627 = U8_Mul                        (0, 0);
	t_u16                var_0628 = U16_Mul                       (0, 0);
	t_u32                var_0629 = U32_Mul                       (0, 0);
	t_u64                var_0630 = U64_Mul                       (0, 0);
	t_s8                 var_0631 = S8_Mul                        (0, 0);
	t_s16                var_0632 = S16_Mul                       (0, 0);
	t_s32                var_0633 = S32_Mul                       (0, 0);
	t_s64                var_0634 = S64_Mul                       (0, 0);
	t_u8                 var_0635 = U8_Div                        (0, 0);
	t_u16                var_0636 = U16_Div                       (0, 0);
	t_u32                var_0637 = U32_Div                       (0, 0);
	t_u64                var_0638 = U64_Div                       (0, 0);
	t_s8                 var_0639 = S8_Div                        (0, 0);
	t_s16                var_0640 = S16_Div                       (0, 0);
	t_s32                var_0641 = S32_Div                       (0, 0);
	t_s64                var_0642 = S64_Div                       (0, 0);
	t_u8                 var_0643 = U8_Mod                        (0, 0);
	t_u16                var_0644 = U16_Mod                       (0, 0);
	t_u32                var_0645 = U32_Mod                       (0, 0);
	t_u64                var_0646 = U64_Mod                       (0, 0);
	t_s8                 var_0647 = S8_Mod                        (0, 0);
	t_s16                var_0648 = S16_Mod                       (0, 0);
	t_s32                var_0649 = S32_Mod                       (0, 0);
	t_s64                var_0650 = S64_Mod                       (0, 0);
	t_u8                 var_0651 = U8_Pow                        (0, 0);
	t_u16                var_0652 = U16_Pow                       (0, 0);
	t_u32                var_0653 = U32_Pow                       (0, 0);
	t_u64                var_0654 = U64_Pow                       (0, 0);
	t_s8                 var_0655 = S8_Pow                        (0, 0);
	t_s16                var_0656 = S16_Pow                       (0, 0);
	t_s32                var_0657 = S32_Pow                       (0, 0);
	t_s64                var_0658 = S64_Pow                       (0, 0);
	t_u8                 var_0659 = U8_Root2                      (0);
	t_u16                var_0660 = U16_Root2                     (0);
	t_u32                var_0661 = U32_Root2                     (0);
	t_u64                var_0662 = U64_Root2                     (0);
	t_s8                 var_0663 = S8_Root2                      (0);
	t_s16                var_0664 = S16_Root2                     (0);
	t_s32                var_0665 = S32_Root2                     (0);
	t_s64                var_0666 = S64_Root2                     (0);
	s_array_int          var_0667 = Stat_Int_NewList              (0);
	                                Stat_Int_FreeList             (NULL);
	s_array_int          var_0669 = Stat_Int_MergeList            (NULL, NULL);
	s_array_int          var_0670 = Stat_Int_Quicksort            ((s_array_int){0});
	                                Stat_Int_Quicksort_InPlace    ((s_array_int){0});
	t_float              var_0672 = Stat_Int_Median               ((s_sorted_int){0});
	t_float              var_0673 = Stat_Int_Average              ((s_array_int){0});
	t_float              var_0674 = Stat_Int_Variance             ((s_array_int){0});
	t_float              var_0675 = Stat_Int_StandardDeviation    ((s_array_int){0});
	                                Stat_Int_Decile               ((s_array_int){0});
	s_array_float        var_0677 = Stat_Float_NewList            (0);
	                                Stat_Float_FreeList           (NULL);
	s_array_float        var_0679 = Stat_Float_MergeList          (NULL, NULL);
	s_array_float        var_0680 = Stat_Float_Quicksort          ((s_array_float){0});
	                                Stat_Float_Quicksort_InPlace  ((s_array_float){0});
	t_float              var_0682 = Stat_Float_Median             ((s_sorted_float){0});
	t_float              var_0683 = Stat_Float_Average            ((s_array_float){0});
	t_float              var_0684 = Stat_Float_Variance           ((s_array_float){0});
	t_float              var_0685 = Stat_Float_StandardDeviation  ((s_array_float){0});
	                                Stat_Float_Decile             ((s_array_float){0});
	s_prob_mass          var_0687 = Stat_NewPMF                   (0);
	                                Stat_FreePMF                  (NULL);
	s_array_int          var_0689 = Stat_IntList_To_Set           ((s_array_int){0});
	t_uint               var_0690 = Stat_IntList_Count            ((s_array_int){0}, 0);
	s_prob_mass          var_0691 = Stat_IntList_To_PMF           ((s_array_int){0});
	void*                var_0692 = Memory_New                    (0);
	void*                var_0693 = Memory_New_C                  (0, 0);
	void*                var_0694 = Memory_Allocate               (0);
	void*                var_0695 = Memory_Reallocate             (NULL, 0);
	                                Memory_Deallocate             (NULL);
	                                Memory_Delete                 (NULL);
	                                Memory_Set                    (NULL, 0, 0);
	                                Memory_Clear                  (NULL, 0);
	void*                var_0700 = Memory_Copy                   (NULL, NULL, 0);
	void*                var_0701 = Memory_Copy_C                 (NULL, NULL, 0, 0);
	void*                var_0702 = Memory_Move                   (NULL, NULL, 0);
	void*                var_0703 = Memory_Duplicate              (NULL, 0);
	void*                var_0704 = Memory_Join                   (NULL, 0, NULL, 0);
	void*                var_0705 = Memory_Append                 (NULL, 0, NULL, 0);
	void*                var_0706 = Memory_Prepend                (NULL, 0, NULL, 0);
	void*                var_0707 = Memory_Merge                  (NULL, 0, NULL, 0);
	void*                var_0708 = Memory_Find                   (NULL, 0, 0);
	                                Memory_Replace                (NULL, 0, 0, 0);
	t_sint               var_0710 = Memory_Compare                (NULL, NULL, 0);
	t_bool               var_0711 = Memory_Equals                 (NULL, NULL, 0);
	t_size               var_0712 = Memory_Print                  (NULL, NULL, 0);
	t_char*              var_0713 = Memory_ToString               (NULL, 0);
	t_uintmax            var_0714 = Memory_GetBits                (NULL, 0, 0);
	                                Memory_SetBits                (NULL, 0, 0, 0);
	t_uintmax            var_0716 = Memory_BitRegion              (0, 0, 0);
	t_u8                 var_0717 = Memory_CountBits              (0);
	t_s8                 var_0718 = Memory_GetMostSignificantBit  (0);
	t_s8                 var_0719 = Memory_GetLeastSignificantBit (0);
	s_array(any)         var_0720 = Array_Item(any)               (NULL);
	void**               var_0721 = Array_Get(any)                (NULL, 0);
	void**               var_0722 = Array_Set(any)                (NULL, 0, NULL);
	s_array(any)*        var_0723 = Array_New(any)                (NULL, NULL);
	s_array(any)*        var_0724 = Array_Create(any)             (NULL);
	s_array(any)*        var_0725 = Array_Duplicate(any)          (NULL);
	s_array(any)*        var_0726 = Array_Sub(any)                (NULL, 0, 0);
	s_array(any)*        var_0727 = Array_Copy(any)               (NULL, 0, NULL, 0, 0);
	                                Array_Free(any)               (NULL);
	                                Array_Free_F(any)             (NULL, NULL);
	                                Array_Delete(any)             (NULL);
	                                Array_Delete_F(any)           (NULL, NULL);
	s_array(any)*        var_0732 = Array_Add(any)                (NULL, NULL);
	s_array(any)*        var_0733 = Array_Insert(any)             (NULL, NULL, 0);
	s_array(any)*        var_0734 = Array_Wedge(any)              (NULL, NULL, 0);
	                                Array_RemoveAt(any)           (NULL, 0);
	                                Array_RemoveAt_F(any)         (NULL, 0, NULL);
	                                Array_Remove(any)             (NULL, NULL);
	                                Array_Remove_F(any)           (NULL, NULL, NULL);
	                                Array_RemoveAll(any)          (NULL, NULL);
	                                Array_RemoveAll_F(any)        (NULL, NULL, NULL);
	s_array(any)*        var_0741 = Array_Replace(any)            (NULL, NULL, NULL);
	s_array(any)*        var_0742 = Array_ReplaceFirst(any)       (NULL, NULL, NULL, 0);
	s_array(any)*        var_0743 = Array_ReplaceLast(any)        (NULL, NULL, NULL, 0);
	s_array(any)*        var_0744 = Array_Reverse(any)            (NULL);
	s_array(any)*        var_0745 = Array_Concat(any)             (NULL, NULL);
	s_array(any)*        var_0746 = Array_Append(any)             (NULL, NULL);
	s_array(any)*        var_0747 = Array_Prepend(any)            (NULL, NULL);
	s_array(any)*        var_0748 = Array_Merge(any)              (NULL, NULL);
	t_bool               var_0749 = Array_Equals(any)             (NULL, NULL);
	t_bool               var_0750 = Array_Equals_N(any)           (NULL, NULL, 0);
	t_sint               var_0751 = Array_Compare(any)            (NULL, NULL, NULL);
	t_sint               var_0752 = Array_Compare_N(any)          (NULL, NULL, NULL, 0);
	void**               var_0753 = Array_Find(any)               (NULL, NULL);
	void**               var_0754 = Array_Find_F(any)             (NULL, NULL);
	t_sint               var_0755 = Array_IndexOf(any)            (NULL, NULL);
	t_sint               var_0756 = Array_IndexOf_F(any)          (NULL, NULL);
	t_uint               var_0757 = Array_Count(any)              (NULL, NULL);
	t_bool               var_0758 = Array_Contains(any)           (NULL, NULL);
	t_bool               var_0759 = Array_Has(any)                (NULL, NULL);
	t_bool               var_0760 = Array_HasOnly(any)            (NULL, NULL);
	                                Array_Iterate(any)            (NULL, NULL);
	                                Array_Iterate_I(any)          (NULL, NULL);
	s_array(any)*        var_0763 = Array_Map(any)                (NULL, NULL);
	s_array(any)*        var_0764 = Array_Map_I(any)              (NULL, NULL);
	s_array(any)*        var_0765 = Array_Filter(any)             (NULL, NULL);
	s_array(any)*        var_0766 = Array_Filter_I(any)           (NULL, NULL);
	void*                var_0767 = Array_Reduce(any)             (NULL, NULL);
	void*                var_0768 = Array_Reduce_I(any)           (NULL, NULL);
	void*                var_0769 = Array_Fold(any)               (NULL, NULL, NULL);
	void*                var_0770 = Array_Fold_I(any)             (NULL, NULL, NULL);
	s_array(any)*        var_0771 = List_ToArray                  (NULL);
	void**               var_0772 = List_ToPointerArray           (NULL);
	s_list(any)*         var_0773 = List_Item(any)                (NULL);
	t_uint               var_0774 = List_Length(any)              (NULL);
	void**               var_0775 = List_Get(any)                 (NULL, 0);
	void**               var_0776 = List_Set(any)                 (NULL, 0, NULL);
	s_list(any)*         var_0777 = List_New(any)                 (NULL, NULL);
	s_list(any)*         var_0778 = List_Create(any)              (NULL);
	s_list(any)*         var_0779 = List_Duplicate(any)           (NULL);
	s_list(any)*         var_0780 = List_Sub(any)                 (NULL, 0, 0);
	s_list(any)*         var_0781 = List_Copy(any)                (NULL, 0, NULL, 0, 0);
	                                List_Free(any)                (NULL);
	                                List_Free_F(any)              (NULL, NULL);
	                                List_Delete(any)              (NULL);
	                                List_Delete_F(any)            (NULL, NULL);
	s_list(any)*         var_0786 = List_Add(any)                 (NULL, NULL);
	s_list(any)*         var_0787 = List_Insert(any)              (NULL, NULL, 0);
	s_list(any)*         var_0788 = List_Wedge(any)               (NULL, NULL, 0);
	s_list(any)*         var_0789 = List_RemoveAt(any)            (NULL, 0);
	s_list(any)*         var_0790 = List_RemoveAt_F(any)          (NULL, 0, NULL);
	s_list(any)*         var_0791 = List_Remove(any)              (NULL, NULL);
	s_list(any)*         var_0792 = List_Remove_F(any)            (NULL, NULL, NULL);
	s_list(any)*         var_0793 = List_RemoveAll(any)           (NULL, NULL);
	s_list(any)*         var_0794 = List_RemoveAll_F(any)         (NULL, NULL, NULL);
	s_list(any)*         var_0795 = List_Replace(any)             (NULL, NULL, NULL);
	s_list(any)*         var_0796 = List_ReplaceFirst(any)        (NULL, NULL, NULL, 0);
	s_list(any)*         var_0797 = List_ReplaceLast(any)         (NULL, NULL, NULL, 0);
	s_list(any)*         var_0798 = List_Reverse(any)             (NULL);
	s_list(any)*         var_0799 = List_Concat(any)              (NULL, NULL);
	s_list(any)*         var_0800 = List_Append(any)              (NULL, NULL);
	s_list(any)*         var_0801 = List_Prepend(any)             (NULL, NULL);
	s_list(any)*         var_0802 = List_Merge(any)               (NULL, NULL);
	t_bool               var_0803 = List_Equals(any)              (NULL, NULL);
	t_bool               var_0804 = List_Equals_N(any)            (NULL, NULL, 0);
	t_sint               var_0805 = List_Compare(any)             (NULL, NULL, NULL);
	t_sint               var_0806 = List_Compare_N(any)           (NULL, NULL, NULL, 0);
	s_list(any) const*   var_0807 = List_Find(any)                (NULL, NULL);
	s_list(any) const*   var_0808 = List_Find_F(any)              (NULL, NULL);
	t_sint               var_0809 = List_IndexOf(any)             (NULL, NULL);
	t_sint               var_0810 = List_IndexOf_F(any)           (NULL, NULL);
	t_uint               var_0811 = List_Count(any)               (NULL, NULL);
	t_bool               var_0812 = List_Contains(any)            (NULL, NULL);
	t_bool               var_0813 = List_Has(any)                 (NULL, NULL);
	t_bool               var_0814 = List_HasOnly(any)             (NULL, NULL);
	                                List_Iterate(any)             (NULL, NULL);
	                                List_Iterate_I(any)           (NULL, NULL);
	s_list(any)*         var_0817 = List_Map(any)                 (NULL, NULL);
	s_list(any)*         var_0818 = List_Map_I(any)               (NULL, NULL);
	s_list(any)*         var_0819 = List_Filter(any)              (NULL, NULL);
	s_list(any)*         var_0820 = List_Filter_I(any)            (NULL, NULL);
	void*                var_0821 = List_Reduce(any)              (NULL, NULL);
	void*                var_0822 = List_Reduce_I(any)            (NULL, NULL);
	void*                var_0823 = List_Fold(any)                (NULL, NULL, NULL);
	void*                var_0824 = List_Fold_I(any)              (NULL, NULL, NULL);
	t_char*              var_0825 = Size_ToString                 (0);
	t_char*              var_0826 = Size_ToString_Hex             (0);
	t_char*              var_0827 = Size_ToString_Pretty          (0);
	t_char*              var_0828 = Pointer_ToString              (NULL);
	t_char*              var_0829 = Pointer_ToString_Hex          (NULL);
	t_size               var_0830 = Size_Parse                    (NULL, NULL);
	t_size               var_0831 = Size_FromString               (NULL);
	t_size               var_0832 = PtrDiff_Parse                 (NULL, NULL);
	t_ptrdiff            var_0833 = PtrDiff_FromString            (NULL);
	t_size               var_0834 = UIntMax_Parse                 (NULL, NULL);
	t_uintmax            var_0835 = UIntMax_FromString            (NULL);
	t_size               var_0836 = SIntMax_Parse                 (NULL, NULL);
	t_sintmax            var_0837 = SIntMax_FromString            (NULL);
	t_size               var_0838 = UIntPtr_Parse                 (NULL, NULL);
	t_uintptr            var_0839 = UIntPtr_FromString            (NULL);
	t_size               var_0840 = SIntPtr_Parse                 (NULL, NULL);
	t_sintptr            var_0841 = SIntPtr_FromString            (NULL);
	t_uint               var_0842 = PointerArray_Length           (NULL);
	void**               var_0843 = PointerArray_New              (0, NULL);
	void**               var_0844 = PointerArray_Create           (0);
	void**               var_0845 = PointerArray_Duplicate        (NULL);
	void**               var_0846 = PointerArray_Sub              (NULL, 0, 0);
	void**               var_0847 = PointerArray_Copy             (NULL, 0, NULL, 0, 0);
	                                PointerArray_Free             (NULL);
	                                PointerArray_Free_F           (NULL, NULL);
	                                PointerArray_Delete           (NULL);
	                                PointerArray_Delete_F         (NULL, NULL);
	void**               var_0852 = PointerArray_Add              (NULL, NULL);
	void**               var_0853 = PointerArray_Insert           (NULL, NULL, 0);
	void**               var_0854 = PointerArray_Wedge            (NULL, NULL, 0);
	                                PointerArray_RemoveAt         (NULL, 0);
	                                PointerArray_RemoveAt_F       (NULL, 0, NULL);
	                                PointerArray_Remove           (NULL, NULL);
	                                PointerArray_Remove_F         (NULL, NULL, NULL);
	                                PointerArray_RemoveAll        (NULL, NULL);
	                                PointerArray_RemoveAll_F      (NULL, NULL, NULL);
	void**               var_0861 = PointerArray_Replace          (NULL, NULL, NULL);
	void**               var_0862 = PointerArray_ReplaceFirst     (NULL, NULL, NULL, 0);
	void**               var_0863 = PointerArray_ReplaceLast      (NULL, NULL, NULL, 0);
	void**               var_0864 = PointerArray_Reverse          (NULL);
	void**               var_0865 = PointerArray_Concat           (NULL, NULL);
	void**               var_0866 = PointerArray_Append           (NULL, NULL);
	void**               var_0867 = PointerArray_Prepend          (NULL, NULL);
	void**               var_0868 = PointerArray_Merge            (NULL, NULL);
	void**               var_0869 = PointerArray_Join             (NULL, NULL);
	t_bool               var_0870 = PointerArray_Equals           (NULL, NULL);
	t_bool               var_0871 = PointerArray_Equals_N         (NULL, NULL, 0);
	t_sint               var_0872 = PointerArray_Compare          (NULL, NULL, NULL);
	t_sint               var_0873 = PointerArray_Compare_N        (NULL, NULL, NULL, 0);
	void* const*         var_0874 = PointerArray_Find             (NULL, NULL);
	void* const*         var_0875 = PointerArray_Find_F           (NULL, NULL);
	t_sint               var_0876 = PointerArray_IndexOf          (NULL, NULL);
	t_sint               var_0877 = PointerArray_IndexOf_F        (NULL, NULL);
	t_uint               var_0878 = PointerArray_Count            (NULL, NULL);
	t_bool               var_0879 = PointerArray_Contains         (NULL, NULL);
	t_bool               var_0880 = PointerArray_Has              (NULL, NULL);
	t_bool               var_0881 = PointerArray_HasOnly          (NULL, NULL);
	                                PointerArray_Iterate          (NULL, NULL);
	                                PointerArray_Iterate_I        (NULL, NULL);
	void**               var_0884 = PointerArray_Map              (NULL, NULL);
	void**               var_0885 = PointerArray_Map_I            (NULL, NULL);
	void**               var_0886 = PointerArray_Filter           (NULL, NULL);
	void**               var_0887 = PointerArray_Filter_I         (NULL, NULL);
	void*                var_0888 = PointerArray_Reduce           (NULL, NULL);
	void*                var_0889 = PointerArray_Reduce_I         (NULL, NULL);
	void*                var_0890 = PointerArray_Fold             (NULL, NULL, NULL);
	void*                var_0891 = PointerArray_Fold_I           (NULL, NULL, NULL);
	t_csprng*            var_0892 = CSPRNG_New                    ();
	                                CSPRNG_Delete                 (NULL);
	e_cccerror           var_0894 = CSPRNG_Next                   (NULL, NULL, 0);
	t_uint               var_0895 = CSPRNG_UInt                   (NULL);
	t_uint               var_0896 = CSPRNG_UInt_Range             (NULL, 0, 0);
	t_sint               var_0897 = CSPRNG_SInt                   (NULL);
	t_sint               var_0898 = CSPRNG_SInt_Range             (NULL, 0, 0);
	t_fixed              var_0899 = CSPRNG_Fixed                  (NULL);
	t_fixed              var_0900 = CSPRNG_Fixed_Range            (NULL, 0, 0);
	t_float              var_0901 = CSPRNG_Float                  (NULL);
	t_float              var_0902 = CSPRNG_Float_Range            (NULL, 0, 0);
	void*                var_0903 = CSPRNG_Get                    (NULL, 0);
	t_uint               var_0904 = CSPRNG_UInt_Get               ();
	t_uint               var_0905 = CSPRNG_UInt_Get_Range         (0, 0);
	t_sint               var_0906 = CSPRNG_SInt_Get               ();
	t_sint               var_0907 = CSPRNG_SInt_Get_Range         (0, 0);
	t_fixed              var_0908 = CSPRNG_Fixed_Get              ();
	t_fixed              var_0909 = CSPRNG_Fixed_Get_Range        (0, 0);
	t_float              var_0910 = CSPRNG_Float_Get              ();
	t_float              var_0911 = CSPRNG_Float_Get_Range        (0, 0);
	                                PRNG_SetSeed                  (NULL, 0);
	                                PRNG_NewSeed                  (NULL);
	t_prng*              var_0914 = PRNG_New                      ();
	                                PRNG_Delete                   (NULL);
	e_cccerror           var_0916 = PRNG_Next                     (NULL, NULL, 0);
	t_uint               var_0917 = PRNG_UInt                     (NULL);
	t_uint               var_0918 = PRNG_UInt_Range               (NULL, 0, 0);
	t_sint               var_0919 = PRNG_SInt                     (NULL);
	t_sint               var_0920 = PRNG_SInt_Range               (NULL, 0, 0);
	t_fixed              var_0921 = PRNG_Fixed                    (NULL);
	t_fixed              var_0922 = PRNG_Fixed_Range              (NULL, 0, 0);
	t_float              var_0923 = PRNG_Float                    (NULL);
	t_float              var_0924 = PRNG_Float_Range              (NULL, 0, 0);
	void*                var_0925 = PRNG_Get                      (NULL, 0);
	t_uint               var_0926 = PRNG_UInt_Get                 ();
	t_uint               var_0927 = PRNG_UInt_Get_Range           (0, 0);
	t_sint               var_0928 = PRNG_SInt_Get                 ();
	t_sint               var_0929 = PRNG_SInt_Get_Range           (0, 0);
	t_fixed              var_0930 = PRNG_Fixed_Get                ();
	t_fixed              var_0931 = PRNG_Fixed_Get_Range          (0, 0);
	t_float              var_0932 = PRNG_Float_Get                ();
	t_float              var_0933 = PRNG_Float_Get_Range          (0, 0);
	t_char*              var_0934 = String_New                    (0);
	t_char*              var_0935 = String_New_C                  (0, 0);
	                                String_Free                   (NULL);
	                                String_Delete                 (NULL);
	t_char*              var_0938 = String_Duplicate              (NULL);
	t_char*              var_0939 = String_Duplicate_N            (NULL, 0);
	t_char*              var_0940 = String_Duplicate_Char         (NULL, 0);
	t_char*              var_0941 = String_Duplicate_Charset      (NULL, NULL);
	t_char*              var_0942 = String_Duplicate_String       (NULL, NULL);
	                                String_Clear                  (NULL);
	                                String_Set                    (NULL, 0);
	t_char*              var_0945 = String_Copy                   (NULL, NULL);
	t_char*              var_0946 = String_Copy_N                 (NULL, NULL, 0);
	t_size               var_0947 = String_Copy_L                 (NULL, NULL, 0);
	t_char*              var_0948 = String_Add                    (NULL, NULL);
	t_char*              var_0949 = String_Add_N                  (NULL, NULL, 0);
	t_size               var_0950 = String_Add_L                  (NULL, NULL, 0);
	t_size               var_0951 = String_Length                 (NULL);
	t_bool               var_0952 = String_Equals                 (NULL, NULL);
	t_bool               var_0953 = String_Equals_N               (NULL, NULL, 0);
	t_bool               var_0954 = String_Equals_IgnoreCase      (NULL, NULL);
	t_bool               var_0955 = String_Equals_N_IgnoreCase    (NULL, NULL, 0);
	t_sint               var_0956 = String_Compare                (NULL, NULL);
	t_sint               var_0957 = String_Compare_N              (NULL, NULL, 0);
	t_sint               var_0958 = String_Compare_IgnoreCase     (NULL, NULL);
	t_sint               var_0959 = String_Compare_N_IgnoreCase   (NULL, NULL, 0);
	t_bool               var_0960 = String_Has                    (NULL, NULL);
	t_bool               var_0961 = String_HasOnly                (NULL, NULL);
	t_size               var_0962 = String_Count_Char             (NULL, 0);
	t_size               var_0963 = String_Count_Charset          (NULL, NULL);
	t_size               var_0964 = String_Count_String           (NULL, NULL);
	t_char*              var_0965 = String_Find_Char              (NULL, 0);
	t_char*              var_0966 = String_Find_Charset           (NULL, NULL);
	t_char*              var_0967 = String_Find_String            (NULL, NULL);
	t_char*              var_0968 = String_Find_R_Char            (NULL, 0);
	t_char*              var_0969 = String_Find_R_Charset         (NULL, NULL);
	t_char*              var_0970 = String_Find_R_String          (NULL, NULL);
	t_char*              var_0971 = String_Find_N_Char            (NULL, 0, 0);
	t_char*              var_0972 = String_Find_N_Charset         (NULL, NULL, 0);
	t_char*              var_0973 = String_Find_N_String          (NULL, NULL, 0);
	t_sintmax            var_0974 = String_IndexOf_Char           (NULL, 0);
	t_sintmax            var_0975 = String_IndexOf_Charset        (NULL, NULL);
	t_sintmax            var_0976 = String_IndexOf_String         (NULL, NULL);
	t_sintmax            var_0977 = String_IndexOf_R_Char         (NULL, 0);
	t_sintmax            var_0978 = String_IndexOf_R_Charset      (NULL, NULL);
	t_sintmax            var_0979 = String_IndexOf_R_String       (NULL, NULL);
	t_sintmax            var_0980 = String_IndexOf_N_Char         (NULL, 0, 0);
	t_sintmax            var_0981 = String_IndexOf_N_Charset      (NULL, NULL, 0);
	t_sintmax            var_0982 = String_IndexOf_N_String       (NULL, NULL, 0);
	t_char*              var_0983 = String_Remove                 (NULL, NULL);
	t_char*              var_0984 = String_Replace_Char           (NULL, 0, 0);
	t_char*              var_0985 = String_Replace_Charset        (NULL, NULL, NULL);
	t_char*              var_0986 = String_Replace_String         (NULL, NULL, NULL);
	t_char*              var_0987 = String_Concat                 (NULL, NULL);
	t_char*              var_0988 = String_Append                 (NULL, NULL);
	t_char*              var_0989 = String_Prepend                (NULL, NULL);
	t_char*              var_0990 = String_Merge                  (NULL, NULL);
	t_char*              var_0991 = String_Join                   (NULL, NULL);
	t_char*              var_0992 = String_Insert_InPlace         (NULL, NULL, 0);
	                                String_Replace_Char_InPlace   (NULL, 0, 0);
	                                String_Replace_Charset_InPlace(NULL, NULL, NULL);
	                                String_Replace_String_InPlace (NULL, NULL, NULL);
	t_char*              var_0996 = String_Map_InPlace            (NULL, NULL);
	t_char*              var_0997 = String_Trim                   (NULL, NULL);
	t_char*              var_0998 = String_Trim_L                 (NULL, NULL);
	t_char*              var_0999 = String_Trim_R                 (NULL, NULL);
	t_char*              var_1000 = String_Pad                    (NULL, 0, 0);
	t_char*              var_1001 = String_Pad_L                  (NULL, 0, 0);
	t_char*              var_1002 = String_Pad_R                  (NULL, 0, 0);
	t_size               var_1003 = String_Print                  (NULL, NULL, 0, NULL);
	t_char*              var_1004 = String_ToEscape               (NULL, NULL);
	t_size               var_1005 = String_Parse                  (NULL, NULL, 0, 0);
	t_char*              var_1006 = String_FromEscape             (NULL, 0);
	t_char*              var_1007 = String_Reverse                (NULL);
	t_char*              var_1008 = String_Insert                 (NULL, NULL, 0);
	t_char*              var_1009 = String_Sub                    (NULL, 0, 0);
	                                String_Iterate                (NULL, NULL);
	                                String_Iterate_I              (NULL, NULL);
	t_char*              var_1012 = String_Map                    (NULL, NULL);
	t_char*              var_1013 = String_Map_I                  (NULL, NULL);
	t_char*              var_1014 = String_Filter                 (NULL, NULL);
	t_char*              var_1015 = String_Filter_I               (NULL, NULL);
	t_char**             var_1016 = String_Split_Char             (NULL, 0);
	t_char**             var_1017 = String_Split_Charset          (NULL, NULL);
	t_char**             var_1018 = String_Split_String           (NULL, NULL);
	t_char**             var_1019 = String_Divide                 (NULL, 0);
	t_uint               var_1020 = StringArray_Length            (NULL);
	t_size               var_1021 = StringArray_TotalLength       (NULL, 0);
	t_char**             var_1022 = StringArray_New               (0);
	t_char**             var_1023 = StringArray_New_C             (0, 0, 0);
	t_char**             var_1024 = StringArray_Create            (0);
	t_char**             var_1025 = StringArray_Duplicate         (NULL);
	t_char**             var_1026 = StringArray_Sub               (NULL, 0, 0);
	t_char**             var_1027 = StringArray_Copy              (NULL, 0, NULL, 0, 0);
	                                StringArray_Free              (NULL);
	                                StringArray_Delete            (NULL);
	t_char**             var_1030 = StringArray_Add               (NULL, NULL);
	t_char**             var_1031 = StringArray_Insert            (NULL, NULL, 0);
	t_char**             var_1032 = StringArray_Wedge             (NULL, NULL, 0);
	                                StringArray_RemoveAt          (NULL, 0);
	                                StringArray_RemoveAt_F        (NULL, 0, NULL);
	                                StringArray_Remove            (NULL, NULL);
	                                StringArray_Remove_F          (NULL, NULL, NULL);
	                                StringArray_RemoveAll         (NULL, NULL);
	                                StringArray_RemoveAll_F       (NULL, NULL, NULL);
	t_char**             var_1039 = StringArray_Replace           (NULL, NULL, NULL);
	t_char**             var_1040 = StringArray_ReplaceFirst      (NULL, NULL, NULL, 0);
	t_char**             var_1041 = StringArray_ReplaceLast       (NULL, NULL, NULL, 0);
	t_char**             var_1042 = StringArray_Reverse           (NULL);
	t_char**             var_1043 = StringArray_Pad_L             (NULL, 0, 0);
	t_char**             var_1044 = StringArray_Concat            (NULL, NULL);
	t_char**             var_1045 = StringArray_Append            (NULL, NULL);
	t_char**             var_1046 = StringArray_Prepend           (NULL, NULL);
	t_char**             var_1047 = StringArray_Merge             (NULL, NULL);
	t_char**             var_1048 = StringArray_Join              (NULL, NULL);
	t_bool               var_1049 = StringArray_Equals            (NULL, NULL);
	t_bool               var_1050 = StringArray_Equals_N          (NULL, NULL, 0);
	t_sint               var_1051 = StringArray_Compare           (NULL, NULL, NULL);
	t_sint               var_1052 = StringArray_Compare_N         (NULL, NULL, NULL, 0);
	t_char* const*       var_1053 = StringArray_Find              (NULL, NULL);
	t_char* const*       var_1054 = StringArray_Find_F            (NULL, NULL);
	t_sint               var_1055 = StringArray_IndexOf           (NULL, NULL);
	t_sint               var_1056 = StringArray_IndexOf_F         (NULL, NULL);
	t_uint               var_1057 = StringArray_Count_Char        (NULL, 0);
	t_uint               var_1058 = StringArray_Count_Charset     (NULL, NULL);
	t_uint               var_1059 = StringArray_Count_String      (NULL, NULL);
	                                StringArray_Iterate           (NULL, NULL);
	                                StringArray_Iterate_I         (NULL, NULL);
	t_char**             var_1062 = StringArray_Map               (NULL, NULL);
	t_char**             var_1063 = StringArray_Map_I             (NULL, NULL);
	t_char**             var_1064 = StringArray_Filter            (NULL, NULL);
	t_char**             var_1065 = StringArray_Filter_I          (NULL, NULL);
	void*                var_1066 = StringArray_Reduce            (NULL, NULL);
	void*                var_1067 = StringArray_Reduce_I          (NULL, NULL);
	void*                var_1068 = StringArray_Fold              (NULL, NULL, NULL);
	void*                var_1069 = StringArray_Fold_I            (NULL, NULL, NULL);
	                                Error_Handle                  (0, NULL, NULL);
	                                Error_Handler                 (0, NULL, NULL);
	f_ccchandler         var_1072 = Error_GetHandler              (0);
	                                Error_SetHandler              (0, 0);
	                                Error_SetAllHandlers          (0);
	t_char const*        var_1075 = Error_CCC_Message             (0);
	t_char*              var_1076 = Error_CCC_GetMessage          (0);
	t_char const*        var_1077 = Error_CCC_Name                (0);
	t_char*              var_1078 = Error_CCC_GetName             (0);
	e_cccerror           var_1079 = Error_CCC_Code                (NULL);
	e_cccerror           var_1080 = Error_CCC_Get                 ();
	e_cccerror           var_1081 = Error_CCC_Set                 (0);
	t_char const*        var_1082 = Error_STD_Message             (0);
	t_char*              var_1083 = Error_STD_GetMessage          (0);
	t_char const*        var_1084 = Error_STD_Name                (0);
	t_char*              var_1085 = Error_STD_GetName             (0);
	t_errno              var_1086 = Error_STD_Code                (NULL);
	t_errno              var_1087 = Error_STD_Get                 ();
	t_errno              var_1088 = Error_STD_Set                 (0);
	t_u8                 var_1089 = IO_GetColor                   (0);
	t_bool               var_1090 = IO_IsTerminal                 (0);
	t_fd                 var_1091 = IO_Open                       (NULL, 0, 0);
	e_cccerror           var_1092 = IO_Close                      (0);
	e_cccerror           var_1093 = IO_ChangeMode                 (NULL, 0);
	t_io_mode            var_1094 = IO_GetMode                    (NULL);
	t_sintmax            var_1095 = IO_Read_File                  (0, NULL, 0);
	t_sintmax            var_1096 = IO_Read_Filepath              (NULL, NULL);
	char*                var_1097 = IO_Read_Filepath_Text         (NULL);
	t_sintmax            var_1098 = IO_Read_Lines                 (0, NULL);
	int                  var_1099 = IO_Read_NextLine              (0, NULL);
	t_size               var_1100 = IO_Write_Char                 (0, 0);
	t_size               var_1101 = IO_Write_String               (0, NULL);
	t_size               var_1102 = IO_Write_Data                 (0, NULL, 0);
	t_size               var_1103 = IO_Write_Line                 (0, NULL);
	t_size               var_1104 = IO_Write_Lines                (0, NULL);
	t_size               var_1105 = IO_Write_Memory               (0, NULL, 0, 0);
	t_size               var_1106 = IO_Write_Format               (0, NULL);
	t_size               var_1107 = IO_Output_Char                (0);
	t_size               var_1108 = IO_Output_String              (NULL);
	t_size               var_1109 = IO_Output_Line                (NULL);
	t_size               var_1110 = IO_Output_Lines               (NULL);
	t_size               var_1111 = IO_Output_Memory              (NULL, 0, 0);
	t_size               var_1112 = IO_Output_Format              (NULL);
	                                Logger_Init                   (NULL);
	                                Logger_Exit                   (NULL);
	                                Logger_DeleteMemory           (NULL);
	t_char*              var_1116 = Logger_GetSettings            (NULL);
	e_cccerror           var_1117 = Logger_LogSettings            (NULL);
	t_char*              var_1118 = Logger_GetTimestamp           (0);
	e_cccerror           var_1119 = Log_Fatal                     (NULL, NULL);
	e_cccerror           var_1120 = Log_Error                     (NULL, NULL, NULL);
	e_cccerror           var_1121 = LogAll_Error                  (0, NULL, NULL);
	e_cccerror           var_1122 = Log_Error_STD                 (NULL, 0, NULL);
	e_cccerror           var_1123 = LogAll_Error_STD              (0, 0, NULL);
	e_cccerror           var_1124 = Log_Error_CCC                 (NULL, 0, NULL);
	e_cccerror           var_1125 = LogAll_Error_CCC              (0, 0, NULL);
	e_cccerror           var_1126 = Log_Failure                   (NULL, NULL);
	e_cccerror           var_1127 = LogAll_Failure                (0, NULL);
	e_cccerror           var_1128 = Log_Warning                   (NULL, NULL);
	e_cccerror           var_1129 = LogAll_Warning                (0, NULL);
	e_cccerror           var_1130 = Log_Success                   (NULL, NULL);
	e_cccerror           var_1131 = LogAll_Success                (0, NULL);
	e_cccerror           var_1132 = Log_Message                   (NULL, NULL);
	e_cccerror           var_1133 = LogAll_Message                (0, NULL);
	e_cccerror           var_1134 = Log_Verbose                   (NULL, NULL);
	e_cccerror           var_1135 = LogAll_Verbose                (0, NULL);
	                                Program_Abort                 ();
	                                Program_Exit                  (0);
	e_cccerror           var_1138 = Program_OnExit                (NULL);
	int                  var_1139 = Program_Run                   (NULL);
	t_char*              var_1140 = Program_GetEnv                (NULL);
	int                  var_1141 = Program_SetEnv                (NULL, NULL, 0);
	t_char*              var_1142 = Program_GetCWD                ();
	t_time               var_1143 = Time_Now                      ();
	s_date               var_1144 = Time_ToDate_UTC               (0);
	s_date               var_1145 = Time_ToDate_LocalTime         (0);
	struct timespec      var_1146 = NanoTime_ToSTDC               (NULL);
	s_nanotime           var_1147 = NanoTime_FromSTDC             (NULL);
	s_date               var_1148 = Date_Now                      ();
	t_time               var_1149 = Date_ToTime_UTC               (NULL);
	t_time               var_1150 = Date_ToTime_LocalTime         (NULL);
	struct tm            var_1151 = Date_ToSTDC                   (NULL);
	s_date               var_1152 = Date_FromSTDC                 (NULL);
	t_size               var_1153 = Date_Parse                    (NULL, NULL, NULL);
	s_date               var_1154 = Date_FromString               (NULL, NULL);
	t_size               var_1155 = Date_Parse_Min                (NULL, NULL, NULL);
	s_date               var_1156 = Date_FromString_Min           (NULL, NULL);
	t_char*              var_1157 = Date_ToString                 (NULL, NULL);
	t_size               var_1158 = Date_ToString_N               (NULL, 0, NULL, NULL);
	t_char*              var_1159 = Date_ToString_Unix            (NULL);
	t_char*              var_1160 = DateNow_ToString_Unix         ();
	t_bool               var_1161 = Date_IsValid                  (NULL);
	                                Date_MakeValid                (NULL);
	t_uint               var_1163 = Date_DaysInMonth              (0, 0);
	e_weekday            var_1164 = Date_DayOfTheWeek             (NULL);
	t_bool               var_1165 = Date_IsLeapYear               (0);
	t_bool               var_1166 = Date_HasLeapSecond            (0, 0);
	t_bool               var_1167 = ASCII_IsLetter                (0);
	t_bool               var_1168 = ASCII_IsUppercase             (0);
	t_bool               var_1169 = ASCII_IsLowercase             (0);
	t_bool               var_1170 = ASCII_IsAlphaNumeric          (0);
	t_bool               var_1171 = ASCII_IsDigit_Decimal         (0);
	t_bool               var_1172 = ASCII_IsDigit_Hexadecimal     (0);
	t_bool               var_1173 = ASCII_IsDigit_Octal           (0);
	t_bool               var_1174 = ASCII_IsDigit_Binary          (0);
	t_bool               var_1175 = ASCII_IsWhiteSpace            (0);
	t_bool               var_1176 = ASCII_IsPunctuation           (0);
	t_bool               var_1177 = ASCII_IsPrintable             (0);
	t_bool               var_1178 = ASCII_IsValid                 (0);
	t_bool               var_1179 = ASCII_IsInCharset             (0, NULL);
	t_ascii              var_1180 = ASCII_ToUppercase             (0);
	t_ascii              var_1181 = ASCII_ToLowercase             (0);
	t_bool               var_1182 = UTF32_IsLetter                (0);
	t_bool               var_1183 = UTF32_IsUppercase             (0);
	t_bool               var_1184 = UTF32_IsLowercase             (0);
	t_bool               var_1185 = UTF32_IsAlphaNumeric          (0);
	t_bool               var_1186 = UTF32_IsDigit_Decimal         (0);
	t_bool               var_1187 = UTF32_IsDigit_Hexadecimal     (0);
	t_bool               var_1188 = UTF32_IsDigit_Octal           (0);
	t_bool               var_1189 = UTF32_IsDigit_Binary          (0);
	t_bool               var_1190 = UTF32_IsWhiteSpace            (0);
	t_bool               var_1191 = UTF32_IsPunctuation           (0);
	t_bool               var_1192 = UTF32_IsPrintable             (0);
	t_bool               var_1193 = UTF32_IsASCII                 (0);
	t_bool               var_1194 = UTF32_IsValid                 (0);
	t_bool               var_1195 = UTF32_IsInCharset             (0, NULL);
	t_utf32              var_1196 = UTF32_ToUppercase             (0);
	t_utf32              var_1197 = UTF32_ToLowercase             (0);
	t_size               var_1198 = UTF32_ToUTF8                  (NULL, 0);
	t_size               var_1199 = UTF32_ToUTF16                 (NULL, 0);
	t_utf32              var_1200 = UTF32_FromUTF8                (NULL);
	t_utf32              var_1201 = UTF32_FromUTF16               (NULL);
	t_utf32              var_1202 = UTF32_FromEscape              (NULL);
	t_size               var_1203 = UTF32_Parse                   (NULL, NULL, 0);
	t_sint               var_1204 = UTF8_ByteOrderMark            (NULL);
	t_sint               var_1205 = UTF16_ByteOrderMark           (NULL);
	t_sint               var_1206 = UTF32_ByteOrderMark           (NULL);
}
