// This is a generated source file: see ./make/rules/test-simple.mk for more info

#include <libccc.h>
#include <libccc/bool.h>
#include <libccc/char.h>
#include <libccc/image/color.h>
#include <libccc/encode/common.h>
#include <libccc/encode/json.h>
#include <libccc/encode/toml.h>
#include <libccc/fixed.h>
#include <libccc/float.h>
#include <libccc/format.h>
#include <libccc/int.h>
#include <libccc/math/algebra.h>
#include <libccc/math/algebra/interval.h>
#include <libccc/math/algebra/matrix.h>
#include <libccc/math/algebra/vector.h>
#include <libccc/math/complex.h>
#include <libccc/math/constants.h>
#include <libccc/math/fixed.h>
#include <libccc/math/float.h>
#include <libccc/math/int.h>
#include <libccc/math.h>
#include <libccc/math/sort.h>
#include <libccc/math/stat.h>
#include <libccc/math/vlq.h>
#include <libccc/memory.h>
#include <libccc/monad/array.c>
#include <libccc/monad/dict.c>
#include <libccc/monad/hashmap.c>
#include <libccc/monad/list.c>
#include <libccc/monad/queue.c>
#include <libccc/monad/stack.c>
#include <libccc/monad/tree.c>
#include <libccc/pointer.h>
#include <libccc/pointerarray.h>
#include <libccc/random/csprng.h>
#include <libccc/random/prng.h>
#include <libccc/random/random.h>
#include <libccc/string.h>
#include <libccc/stringarray.h>
#include <libccc/sys/ansi.h>
#include <libccc/sys/error.h>
#include <libccc/sys/io.h>
#include <libccc/sys/logger.h>
#include <libccc/sys/program.h>
#include <libccc/sys/time.h>
#include <libccc/text/ascii.h>
#include <libccc/text/regex.h>
#include <libccc/text/unicode.h>
#include <libccc_config.h>
#include <libccc_define.h>
#include <libccc_errors.h>
#include <libccc_naming.h>
#define T_TYPE	t_sint
#define T_NAME	int
#define T_NULL	0
#include <libccc/monad/array.c>
#define T_TYPE	t_float
#define T_NAME	float
#define T_NULL	0.0
#include <libccc/monad/array.c>

int main()
{
	t_char*              var_0001 = Bool_ToString                 (0, 0);
	t_size               var_0002 = Bool_Parse                    (NULL, NULL);
	t_bool               var_0003 = Bool_FromString               (NULL);
	t_u8                 var_0004 = Color_ARGB16_Get_A            (0);
	t_u8                 var_0005 = Color_ARGB16_Get_R            (0);
	t_u8                 var_0006 = Color_ARGB16_Get_G            (0);
	t_u8                 var_0007 = Color_ARGB16_Get_B            (0);
	t_argb16             var_0008 = Color_ARGB16_Set              (0, 0, 0, 0);
	t_argb16             var_0009 = Color_ARGB16_Set_A            (0, 0);
	t_argb16             var_0010 = Color_ARGB16_Set_R            (0, 0);
	t_argb16             var_0011 = Color_ARGB16_Set_G            (0, 0);
	t_argb16             var_0012 = Color_ARGB16_Set_B            (0, 0);
	t_argb32             var_0013 = Color_ARGB16_To_ARGB32        (0);
	s_argb               var_0014 = Color_ARGB16_To_ARGB          (0);
	t_u16                var_0015 = Color_ARGB16_Difference       (0, 0);
	t_argb16 const*      var_0016 = Color_ARGB16_GetNearest       (0, NULL, 0);
	t_u8                 var_0017 = Color_ARGB32_Get_A            (0);
	t_u8                 var_0018 = Color_ARGB32_Get_R            (0);
	t_u8                 var_0019 = Color_ARGB32_Get_G            (0);
	t_u8                 var_0020 = Color_ARGB32_Get_B            (0);
	t_argb32             var_0021 = Color_ARGB32_Set              (0, 0, 0, 0);
	t_argb32             var_0022 = Color_ARGB32_Set_A            (0, 0);
	t_argb32             var_0023 = Color_ARGB32_Set_R            (0, 0);
	t_argb32             var_0024 = Color_ARGB32_Set_G            (0, 0);
	t_argb32             var_0025 = Color_ARGB32_Set_B            (0, 0);
	t_argb16             var_0026 = Color_ARGB32_To_ARGB16        (0);
	s_argb               var_0027 = Color_ARGB32_To_ARGB          (0);
	t_u32                var_0028 = Color_ARGB32_Difference       (0, 0);
	t_argb32 const*      var_0029 = Color_ARGB32_GetNearest       (0, NULL, 0);
	s_argb               var_0030 = Color_ARGB_Set                (0, 0, 0, 0);
	                                Color_ARGB_Set_A              (NULL, 0);
	                                Color_ARGB_Set_R              (NULL, 0);
	                                Color_ARGB_Set_G              (NULL, 0);
	                                Color_ARGB_Set_B              (NULL, 0);
	t_argb16             var_0035 = Color_ARGB_To_ARGB16          (NULL);
	t_argb32             var_0036 = Color_ARGB_To_ARGB32          (NULL);
	s_ahsl               var_0037 = Color_ARGB_To_AHSL            (NULL);
	s_argb const*        var_0038 = Color_ARGB_GetNearest         ((s_argb){0}, NULL, 0);
	s_ahsl               var_0039 = Color_AHSL_Set                (0, 0, 0, 0);
	                                Color_AHSL_Set_A              (NULL, 0);
	                                Color_AHSL_Set_H              (NULL, 0);
	                                Color_AHSL_Set_S              (NULL, 0);
	                                Color_AHSL_Set_L              (NULL, 0);
	s_argb               var_0044 = Color_AHSL_To_ARGB            (NULL);
	s_ahsl const*        var_0045 = Color_AHSL_GetNearest         ((s_ahsl){0}, NULL, 0);
	                                KVT_Print_UpdateOffset        (NULL);
	t_utf8*              var_0047 = KVT_Print_EnsureBuffer        (NULL, 0);
	s_kvt*               var_0048 = KVT_Item                      ();
	s_kvt*               var_0049 = KVT_Duplicate                 (NULL, 0);
	t_bool               var_0050 = KVT_Equals                    (NULL, NULL, 0);
	s_kvt*               var_0051 = KVT_CreateNull                ();
	s_kvt*               var_0052 = KVT_CreateBoolean             (0);
	s_kvt*               var_0053 = KVT_CreateInteger             (0);
	s_kvt*               var_0054 = KVT_CreateFloat               (0);
	s_kvt*               var_0055 = KVT_CreateString              (NULL);
	s_kvt*               var_0056 = KVT_CreateArray               ();
	s_kvt*               var_0057 = KVT_CreateObject              ();
	s_kvt*               var_0058 = KVT_CreateRaw                 (NULL);
	s_kvt*               var_0059 = KVT_CreateStringReference     (NULL);
	s_kvt*               var_0060 = KVT_CreateArrayReference      (NULL);
	s_kvt*               var_0061 = KVT_CreateObjectReference     (NULL);
	s_kvt*               var_0062 = KVT_CreateArray_Boolean       (NULL, 0);
	s_kvt*               var_0063 = KVT_CreateArray_UInt          (NULL, 0);
	s_kvt*               var_0064 = KVT_CreateArray_U8            (NULL, 0);
	s_kvt*               var_0065 = KVT_CreateArray_U16           (NULL, 0);
	s_kvt*               var_0066 = KVT_CreateArray_U32           (NULL, 0);
	s_kvt*               var_0067 = KVT_CreateArray_U64           (NULL, 0);
	s_kvt*               var_0068 = KVT_CreateArray_SInt          (NULL, 0);
	s_kvt*               var_0069 = KVT_CreateArray_S8            (NULL, 0);
	s_kvt*               var_0070 = KVT_CreateArray_S16           (NULL, 0);
	s_kvt*               var_0071 = KVT_CreateArray_S32           (NULL, 0);
	s_kvt*               var_0072 = KVT_CreateArray_S64           (NULL, 0);
	s_kvt*               var_0073 = KVT_CreateArray_Float         (NULL, 0);
	s_kvt*               var_0074 = KVT_CreateArray_F32           (NULL, 0);
	s_kvt*               var_0075 = KVT_CreateArray_F64           (NULL, 0);
	s_kvt*               var_0076 = KVT_CreateArray_String        (NULL, 0);
	t_sint               var_0077 = KVT_GetArrayLength            (NULL);
	s_kvt*               var_0078 = KVT_GetArrayItem              (NULL, 0);
	t_bool               var_0079 = KVT_GetValue_Boolean          (NULL);
	t_s64                var_0080 = KVT_GetValue_Integer          (NULL);
	t_f64                var_0081 = KVT_GetValue_Float            (NULL);
	t_char*              var_0082 = KVT_GetValue_String           (NULL);
	e_cccerror           var_0083 = KVT_SetValue_Boolean          (NULL, 0);
	e_cccerror           var_0084 = KVT_SetValue_Integer          (NULL, 0);
	e_cccerror           var_0085 = KVT_SetValue_Float            (NULL, 0);
	e_cccerror           var_0086 = KVT_SetValue_String           (NULL, NULL);
	e_cccerror           var_0087 = KVT_AddToArray_Item           (NULL, NULL);
	e_cccerror           var_0088 = KVT_AddToArray_ItemReference  (NULL, NULL);
	e_cccerror           var_0089 = KVT_AddToObject_Item          (NULL, NULL, NULL);
	e_cccerror           var_0090 = KVT_AddToObject_ItemReference (NULL, NULL, NULL);
	s_kvt*               var_0091 = KVT_AddToObject_Null          (NULL, NULL);
	s_kvt*               var_0092 = KVT_AddToObject_Boolean       (NULL, NULL, 0);
	s_kvt*               var_0093 = KVT_AddToObject_Integer       (NULL, NULL, 0);
	s_kvt*               var_0094 = KVT_AddToObject_Float         (NULL, NULL, 0);
	s_kvt*               var_0095 = KVT_AddToObject_String        (NULL, NULL, NULL);
	s_kvt*               var_0096 = KVT_AddToObject_Object        (NULL, NULL);
	s_kvt*               var_0097 = KVT_AddToObject_Array         (NULL, NULL);
	s_kvt*               var_0098 = KVT_AddToObject_Raw           (NULL, NULL, NULL);
	t_bool               var_0099 = KVT_IsInvalid                 (NULL);
	t_bool               var_0100 = KVT_IsNull                    (NULL);
	t_bool               var_0101 = KVT_IsBoolean                 (NULL);
	t_bool               var_0102 = KVT_IsInteger                 (NULL);
	t_bool               var_0103 = KVT_IsFloat                   (NULL);
	t_bool               var_0104 = KVT_IsString                  (NULL);
	t_bool               var_0105 = KVT_IsArray                   (NULL);
	t_bool               var_0106 = KVT_IsObject                  (NULL);
	t_bool               var_0107 = KVT_IsRaw                     (NULL);
	e_cccerror           var_0108 = KVT_Delete                    (NULL);
	s_kvt*               var_0109 = KVT_Detach                    (NULL, NULL);
	e_cccerror           var_0110 = KVT_Replace                   (NULL, NULL, NULL);
	e_cccerror           var_0111 = KVT_Delete_FromArray          (NULL, 0);
	s_kvt*               var_0112 = KVT_Detach_FromArray          (NULL, 0);
	e_cccerror           var_0113 = KVT_Replace_InArray           (NULL, 0, NULL);
	e_cccerror           var_0114 = KVT_Insert_InArray            (NULL, 0, NULL);
	s_kvt*               var_0115 = KVT_Concat                    (NULL, NULL);
	s_kvt*               var_0116 = KVT_Concat_Array              (NULL, NULL);
	s_kvt*               var_0117 = KVT_Concat_Object             (NULL, NULL);
	s_kvt*               var_0118 = KVT_Merge                     (NULL, NULL, 0);
	t_size               var_0119 = JSON_Parse_Lenient            (NULL, NULL, 0);
	s_json*              var_0120 = JSON_FromString_Lenient       (NULL);
	t_size               var_0121 = JSON_Parse_Strict             (NULL, NULL, 0);
	s_json*              var_0122 = JSON_FromString_Strict        (NULL);
	t_size               var_0123 = JSON_Print_Pretty             (NULL, NULL, 0);
	t_utf8*              var_0124 = JSON_ToString_Pretty          (NULL);
	t_size               var_0125 = JSON_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0126 = JSON_ToString_Minify          (NULL);
	t_size               var_0127 = TOML_Parse_Lenient            (NULL, NULL, 0);
	s_toml*              var_0128 = TOML_FromString_Lenient       (NULL);
	t_size               var_0129 = TOML_Parse_Strict             (NULL, NULL, 0);
	s_toml*              var_0130 = TOML_FromString_Strict        (NULL);
	t_size               var_0131 = TOML_Print_Pretty             (NULL, NULL, 0);
	t_size               var_0132 = TOML_Print_Minify             (NULL, NULL, 0);
	t_utf8*              var_0133 = TOML_ToString_Pretty          (NULL);
	t_utf8*              var_0134 = TOML_ToString_Minify          (NULL);
	t_char*              var_0135 = Error_STDC                    (0);
	e_cccerror           var_0136 = Error_Get                     ();
	e_cccerror           var_0137 = Error_Set                     (0);
	t_char*              var_0138 = Error_GetMessage              (0);
	t_char*              var_0139 = Error_GetName                 (0);
	e_cccerror           var_0140 = Error_GetCode                 (NULL);
	                                Error_Handle                  (0, NULL, NULL);
	                                Error_Handler                 (0, NULL);
	f_ccchandler         var_0143 = Error_GetHandler              (0);
	                                Error_SetHandler              (0, 0);
	                                Error_SetAllHandlers          (0);
	t_q16                var_0146 = Q16_FromInt                   (0);
	t_q32                var_0147 = Q32_FromInt                   (0);
	t_q64                var_0148 = Q64_FromInt                   (0);
	t_q16                var_0149 = Q16_FromFixed                 (0);
	t_q32                var_0150 = Q32_FromFixed                 (0);
	t_q64                var_0151 = Q64_FromFixed                 (0);
	t_q16                var_0152 = Q16_FromFloat                 (0);
	t_q32                var_0153 = Q32_FromFloat                 (0);
	t_q64                var_0154 = Q64_FromFloat                 (0);
	t_q16                var_0155 = Q16_From                      (0, 0);
	t_q32                var_0156 = Q32_From                      (0, 0);
	t_q64                var_0157 = Q64_From                      (0, 0);
	t_s16                var_0158 = Q16_IntegerPart               (0);
	t_s32                var_0159 = Q32_IntegerPart               (0);
	t_s64                var_0160 = Q64_IntegerPart               (0);
	t_s16                var_0161 = Q16_FractionPart              (0);
	t_s32                var_0162 = Q32_FractionPart              (0);
	t_s64                var_0163 = Q64_FractionPart              (0);
	t_size               var_0164 = Q16_Parse                     (NULL, NULL, 0);
	t_size               var_0165 = Q32_Parse                     (NULL, NULL, 0);
	t_size               var_0166 = Q64_Parse                     (NULL, NULL, 0);
	t_size               var_0167 = Q16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0168 = Q32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0169 = Q64_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0170 = Q16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0171 = Q32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0172 = Q64_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0173 = Q16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0174 = Q32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0175 = Q64_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0176 = Q16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0177 = Q32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0178 = Q64_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0179 = Q16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0180 = Q32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0181 = Q64_Parse_Base                (NULL, NULL, NULL, 0);
	t_f32                var_0182 = F32_FromInt                   (0);
	t_f64                var_0183 = F64_FromInt                   (0);
	t_f32                var_0184 = F32_FromFixed                 (0);
	t_f64                var_0185 = F64_FromFixed                 (0);
	t_f32                var_0186 = F32_FromFloat                 (0);
	t_f64                var_0187 = F64_FromFloat                 (0);
	t_f32                var_0188 = F32_From                      (0, 0);
	t_f64                var_0189 = F64_From                      (0, 0);
	t_sint               var_0190 = F32_GetExp2                   (0);
	t_sint               var_0191 = F64_GetExp2                   (0);
	t_sint               var_0192 = F32_GetExp10                  (0);
	t_sint               var_0193 = F64_GetExp10                  (0);
	t_char*              var_0194 = F32_ToString                  (0, 0);
	t_char*              var_0195 = F64_ToString                  (0, 0);
	t_char*              var_0196 = F32_ToString_Exp              (0, 0);
	t_char*              var_0197 = F64_ToString_Exp              (0, 0);
	t_char*              var_0198 = F32_ToString_Dec              (0, 0);
	t_char*              var_0199 = F64_ToString_Dec              (0, 0);
	t_char*              var_0200 = F32_ToString_Hex              (0, 0);
	t_char*              var_0201 = F64_ToString_Hex              (0, 0);
	t_char*              var_0202 = F32_ToString_Bin              (0, 0);
	t_char*              var_0203 = F64_ToString_Bin              (0, 0);
	t_size               var_0204 = F32_Parse                     (NULL, NULL, 0);
	t_size               var_0205 = F64_Parse                     (NULL, NULL, 0);
	t_f32                var_0206 = F32_FromString                (NULL);
	t_f64                var_0207 = F64_FromString                (NULL);
	t_size               var_0208 = F32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0209 = F64_Parse_Dec                 (NULL, NULL, 0);
	t_f32                var_0210 = F32_FromString_Dec            (NULL);
	t_f64                var_0211 = F64_FromString_Dec            (NULL);
	t_size               var_0212 = F32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0213 = F64_Parse_Hex                 (NULL, NULL, 0);
	t_f32                var_0214 = F32_FromString_Hex            (NULL);
	t_f64                var_0215 = F64_FromString_Hex            (NULL);
	t_size               var_0216 = F32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0217 = F64_Parse_Oct                 (NULL, NULL, 0);
	t_f32                var_0218 = F32_FromString_Oct            (NULL);
	t_f64                var_0219 = F64_FromString_Oct            (NULL);
	t_size               var_0220 = F32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0221 = F64_Parse_Bin                 (NULL, NULL, 0);
	t_f32                var_0222 = F32_FromString_Bin            (NULL);
	t_f64                var_0223 = F64_FromString_Bin            (NULL);
	t_char*              var_0224 = String_Format                 (NULL);
	t_char*              var_0225 = String_Format_VA              (NULL, 0);
	t_size               var_0226 = String_Format_N               (NULL, 0, NULL);
	t_size               var_0227 = String_Format_N_VA            (NULL, 0, NULL, 0);
	t_char*              var_0228 = U8_ToString                   (0);
	t_char*              var_0229 = U16_ToString                  (0);
	t_char*              var_0230 = U32_ToString                  (0);
	t_char*              var_0231 = U64_ToString                  (0);
	t_char*              var_0232 = S8_ToString                   (0);
	t_char*              var_0233 = S16_ToString                  (0);
	t_char*              var_0234 = S32_ToString                  (0);
	t_char*              var_0235 = S64_ToString                  (0);
	t_char*              var_0236 = U8_ToString_Dec               (0);
	t_char*              var_0237 = U16_ToString_Dec              (0);
	t_char*              var_0238 = U32_ToString_Dec              (0);
	t_char*              var_0239 = U64_ToString_Dec              (0);
	t_char*              var_0240 = S8_ToString_Dec               (0);
	t_char*              var_0241 = S16_ToString_Dec              (0);
	t_char*              var_0242 = S32_ToString_Dec              (0);
	t_char*              var_0243 = S64_ToString_Dec              (0);
	t_char*              var_0244 = U8_ToString_Hex               (0, 0);
	t_char*              var_0245 = U16_ToString_Hex              (0, 0);
	t_char*              var_0246 = U32_ToString_Hex              (0, 0);
	t_char*              var_0247 = U64_ToString_Hex              (0, 0);
	t_char*              var_0248 = S8_ToString_Hex               (0, 0);
	t_char*              var_0249 = S16_ToString_Hex              (0, 0);
	t_char*              var_0250 = S32_ToString_Hex              (0, 0);
	t_char*              var_0251 = S64_ToString_Hex              (0, 0);
	t_char*              var_0252 = U8_ToString_Oct               (0, 0);
	t_char*              var_0253 = U16_ToString_Oct              (0, 0);
	t_char*              var_0254 = U32_ToString_Oct              (0, 0);
	t_char*              var_0255 = U64_ToString_Oct              (0, 0);
	t_char*              var_0256 = S8_ToString_Oct               (0, 0);
	t_char*              var_0257 = S16_ToString_Oct              (0, 0);
	t_char*              var_0258 = S32_ToString_Oct              (0, 0);
	t_char*              var_0259 = S64_ToString_Oct              (0, 0);
	t_char*              var_0260 = U8_ToString_Bin               (0, 0);
	t_char*              var_0261 = U16_ToString_Bin              (0, 0);
	t_char*              var_0262 = U32_ToString_Bin              (0, 0);
	t_char*              var_0263 = U64_ToString_Bin              (0, 0);
	t_char*              var_0264 = S8_ToString_Bin               (0, 0);
	t_char*              var_0265 = S16_ToString_Bin              (0, 0);
	t_char*              var_0266 = S32_ToString_Bin              (0, 0);
	t_char*              var_0267 = S64_ToString_Bin              (0, 0);
	t_char*              var_0268 = U8_ToString_Base              (0, NULL);
	t_char*              var_0269 = U16_ToString_Base             (0, NULL);
	t_char*              var_0270 = U32_ToString_Base             (0, NULL);
	t_char*              var_0271 = U64_ToString_Base             (0, NULL);
	t_char*              var_0272 = S8_ToString_Base              (0, NULL);
	t_char*              var_0273 = S16_ToString_Base             (0, NULL);
	t_char*              var_0274 = S32_ToString_Base             (0, NULL);
	t_char*              var_0275 = S64_ToString_Base             (0, NULL);
	t_size               var_0276 = U8_Parse                      (NULL, NULL, 0);
	t_size               var_0277 = U16_Parse                     (NULL, NULL, 0);
	t_size               var_0278 = U32_Parse                     (NULL, NULL, 0);
	t_size               var_0279 = U64_Parse                     (NULL, NULL, 0);
	t_u8                 var_0280 = U8_FromString                 (NULL);
	t_u16                var_0281 = U16_FromString                (NULL);
	t_u32                var_0282 = U32_FromString                (NULL);
	t_u64                var_0283 = U64_FromString                (NULL);
	t_size               var_0284 = S8_Parse                      (NULL, NULL, 0);
	t_size               var_0285 = S16_Parse                     (NULL, NULL, 0);
	t_size               var_0286 = S32_Parse                     (NULL, NULL, 0);
	t_size               var_0287 = S64_Parse                     (NULL, NULL, 0);
	t_s8                 var_0288 = S8_FromString                 (NULL);
	t_s16                var_0289 = S16_FromString                (NULL);
	t_s32                var_0290 = S32_FromString                (NULL);
	t_s64                var_0291 = S64_FromString                (NULL);
	t_size               var_0292 = U8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0293 = U16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0294 = U32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0295 = U64_Parse_Dec                 (NULL, NULL, 0);
	t_u8                 var_0296 = U8_FromString_Dec             (NULL);
	t_u16                var_0297 = U16_FromString_Dec            (NULL);
	t_u32                var_0298 = U32_FromString_Dec            (NULL);
	t_u64                var_0299 = U64_FromString_Dec            (NULL);
	t_size               var_0300 = S8_Parse_Dec                  (NULL, NULL, 0);
	t_size               var_0301 = S16_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0302 = S32_Parse_Dec                 (NULL, NULL, 0);
	t_size               var_0303 = S64_Parse_Dec                 (NULL, NULL, 0);
	t_s8                 var_0304 = S8_FromString_Dec             (NULL);
	t_s16                var_0305 = S16_FromString_Dec            (NULL);
	t_s32                var_0306 = S32_FromString_Dec            (NULL);
	t_s64                var_0307 = S64_FromString_Dec            (NULL);
	t_size               var_0308 = U8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0309 = U16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0310 = U32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0311 = U64_Parse_Hex                 (NULL, NULL, 0);
	t_u8                 var_0312 = U8_FromString_Hex             (NULL);
	t_u16                var_0313 = U16_FromString_Hex            (NULL);
	t_u32                var_0314 = U32_FromString_Hex            (NULL);
	t_u64                var_0315 = U64_FromString_Hex            (NULL);
	t_size               var_0316 = S8_Parse_Hex                  (NULL, NULL, 0);
	t_size               var_0317 = S16_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0318 = S32_Parse_Hex                 (NULL, NULL, 0);
	t_size               var_0319 = S64_Parse_Hex                 (NULL, NULL, 0);
	t_s8                 var_0320 = S8_FromString_Hex             (NULL);
	t_s16                var_0321 = S16_FromString_Hex            (NULL);
	t_s32                var_0322 = S32_FromString_Hex            (NULL);
	t_s64                var_0323 = S64_FromString_Hex            (NULL);
	t_size               var_0324 = U8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0325 = U16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0326 = U32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0327 = U64_Parse_Oct                 (NULL, NULL, 0);
	t_u8                 var_0328 = U8_FromString_Oct             (NULL);
	t_u16                var_0329 = U16_FromString_Oct            (NULL);
	t_u32                var_0330 = U32_FromString_Oct            (NULL);
	t_u64                var_0331 = U64_FromString_Oct            (NULL);
	t_size               var_0332 = S8_Parse_Oct                  (NULL, NULL, 0);
	t_size               var_0333 = S16_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0334 = S32_Parse_Oct                 (NULL, NULL, 0);
	t_size               var_0335 = S64_Parse_Oct                 (NULL, NULL, 0);
	t_s8                 var_0336 = S8_FromString_Oct             (NULL);
	t_s16                var_0337 = S16_FromString_Oct            (NULL);
	t_s32                var_0338 = S32_FromString_Oct            (NULL);
	t_s64                var_0339 = S64_FromString_Oct            (NULL);
	t_size               var_0340 = U8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0341 = U16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0342 = U32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0343 = U64_Parse_Bin                 (NULL, NULL, 0);
	t_u8                 var_0344 = U8_FromString_Bin             (NULL);
	t_u16                var_0345 = U16_FromString_Bin            (NULL);
	t_u32                var_0346 = U32_FromString_Bin            (NULL);
	t_u64                var_0347 = U64_FromString_Bin            (NULL);
	t_size               var_0348 = S8_Parse_Bin                  (NULL, NULL, 0);
	t_size               var_0349 = S16_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0350 = S32_Parse_Bin                 (NULL, NULL, 0);
	t_size               var_0351 = S64_Parse_Bin                 (NULL, NULL, 0);
	t_s8                 var_0352 = S8_FromString_Bin             (NULL);
	t_s16                var_0353 = S16_FromString_Bin            (NULL);
	t_s32                var_0354 = S32_FromString_Bin            (NULL);
	t_s64                var_0355 = S64_FromString_Bin            (NULL);
	t_size               var_0356 = U8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0357 = U16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0358 = U32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0359 = U64_Parse_Base                (NULL, NULL, NULL, 0);
	t_u8                 var_0360 = U8_FromString_Base            (NULL, NULL);
	t_u16                var_0361 = U16_FromString_Base           (NULL, NULL);
	t_u32                var_0362 = U32_FromString_Base           (NULL, NULL);
	t_u64                var_0363 = U64_FromString_Base           (NULL, NULL);
	t_size               var_0364 = S8_Parse_Base                 (NULL, NULL, NULL, 0);
	t_size               var_0365 = S16_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0366 = S32_Parse_Base                (NULL, NULL, NULL, 0);
	t_size               var_0367 = S64_Parse_Base                (NULL, NULL, NULL, 0);
	t_s8                 var_0368 = S8_FromString_Base            (NULL, NULL);
	t_s16                var_0369 = S16_FromString_Base           (NULL, NULL);
	t_s32                var_0370 = S32_FromString_Base           (NULL, NULL);
	t_s64                var_0371 = S64_FromString_Base           (NULL, NULL);
	t_float              var_0372 = c_integrate                   (0, (s_interval){0}, 0);
	t_float              var_0373 = c_mc_integrate_1d             (0, (s_box1d){0});
	t_float              var_0374 = c_mc_integrate_2d             (0, (s_box2d){0});
	t_float              var_0375 = c_mc_integrate_3d             (0, (s_box3d){0});
	t_float              var_0376 = c_mc_integrate_4d             (0, (s_box4d){0});
	t_float              var_0377 = c_distance_float              (0, 0);
	t_f32                var_0378 = c_distance_f32                (0, 0);
	t_f64                var_0379 = c_distance_f64                (0, 0);
	t_uint               var_0380 = c_distance_uint               (0, 0);
	t_u8                 var_0381 = c_distance_u8                 (0, 0);
	t_u16                var_0382 = c_distance_u16                (0, 0);
	t_u32                var_0383 = c_distance_u32                (0, 0);
	t_u64                var_0384 = c_distance_u64                (0, 0);
	t_sint               var_0385 = c_distance_int                (0, 0);
	t_s8                 var_0386 = c_distance_s8                 (0, 0);
	t_s16                var_0387 = c_distance_s16                (0, 0);
	t_s32                var_0388 = c_distance_s32                (0, 0);
	t_s64                var_0389 = c_distance_s64                (0, 0);
	s_matrix2d           var_0390 = Matrix2D                      (NULL, NULL);
	s_matrix2d*          var_0391 = Matrix2D_New                  (NULL, NULL);
	t_bool               var_0392 = Matrix2D_Equals               (NULL, NULL);
	s_vector2d           var_0393 = Matrix2D_Apply                (NULL, NULL);
	t_float              var_0394 = Matrix2D_Determinant          (NULL);
	s_matrix2d           var_0395 = Matrix2D_Inverse              (NULL);
	s_matrix2d           var_0396 = Matrix2D_Transpose            (NULL);
	s_matrix2d           var_0397 = Matrix2D_Multiply             (NULL, NULL);
	s_matrix3d           var_0398 = Matrix3D                      (NULL, NULL, NULL);
	s_matrix3d*          var_0399 = Matrix3D_New                  (NULL, NULL, NULL);
	t_bool               var_0400 = Matrix3D_Equals               (NULL, NULL);
	s_vector3d           var_0401 = Matrix3D_Apply                (NULL, NULL);
	t_float              var_0402 = Matrix3D_Determinant          (NULL);
	s_matrix3d           var_0403 = Matrix3D_Inverse              (NULL);
	s_matrix3d           var_0404 = Matrix3D_Transpose            (NULL);
	s_matrix3d           var_0405 = Matrix3D_Multiply             (NULL, NULL);
	s_vector2d           var_0406 = Vector2D                      (0, 0);
	s_vector2d*          var_0407 = Vector2D_New                  (0, 0);
	t_bool               var_0408 = Vector2D_Equals               (NULL, NULL);
	s_vector2d           var_0409 = Vector2D_Scale                (NULL, 0);
	s_vector2d           var_0410 = Vector2D_Invert               (NULL);
	t_float              var_0411 = Vector2D_Norm                 (NULL);
	s_vector2d           var_0412 = Vector2D_Normalize            (NULL);
	s_vector2d           var_0413 = Vector2D_Add                  (NULL, NULL);
	t_float              var_0414 = Vector2D_Dot                  (NULL, NULL);
	s_vector3d           var_0415 = Vector3D                      (0, 0, 0);
	s_vector3d*          var_0416 = Vector3D_New                  (0, 0, 0);
	t_bool               var_0417 = Vector3D_Equals               (NULL, NULL);
	s_vector3d           var_0418 = Vector3D_Scale                (NULL, 0);
	s_vector3d           var_0419 = Vector3D_Invert               (NULL);
	t_float              var_0420 = Vector3D_Norm                 (NULL);
	s_vector3d           var_0421 = Vector3D_Normalize            (NULL);
	s_vector3d           var_0422 = Vector3D_Add                  (NULL, NULL);
	t_float              var_0423 = Vector3D_Dot                  (NULL, NULL);
	s_vector3d           var_0424 = Vector3D_Cross                (NULL, NULL);
	s_complex            var_0425 = Complex                       (0, 0);
	s_complex*           var_0426 = Complex_New                   (0, 0);
	t_bool               var_0427 = Complex_Equals                (NULL, NULL);
	t_float              var_0428 = Complex_Abs                   (NULL);
	s_complex            var_0429 = Complex_Conjugate             (NULL);
	s_complex            var_0430 = Complex_Add                   (NULL, NULL);
	s_complex            var_0431 = Complex_Sub                   (NULL, NULL);
	s_complex            var_0432 = Complex_Mul                   (NULL, NULL);
	s_complex            var_0433 = Complex_Div                   (NULL, NULL);
	s_complex            var_0434 = Complex_Pow                   (NULL, 0);
	t_q16                var_0435 = Q16_Abs                       (0);
	t_q32                var_0436 = Q32_Abs                       (0);
	t_q64                var_0437 = Q64_Abs                       (0);
	t_q16                var_0438 = Q16_Round                     (0);
	t_q32                var_0439 = Q32_Round                     (0);
	t_q64                var_0440 = Q64_Round                     (0);
	t_q16                var_0441 = Q16_Trunc                     (0);
	t_q32                var_0442 = Q32_Trunc                     (0);
	t_q64                var_0443 = Q64_Trunc                     (0);
	t_q16                var_0444 = Q16_Floor                     (0);
	t_q32                var_0445 = Q32_Floor                     (0);
	t_q64                var_0446 = Q64_Floor                     (0);
	t_q16                var_0447 = Q16_Ceil                      (0);
	t_q32                var_0448 = Q32_Ceil                      (0);
	t_q64                var_0449 = Q64_Ceil                      (0);
	t_bool               var_0450 = Q16_Equals                    (0, 0);
	t_bool               var_0451 = Q32_Equals                    (0, 0);
	t_bool               var_0452 = Q64_Equals                    (0, 0);
	t_bool               var_0453 = Q16_EqualsApprox              (0, 0);
	t_bool               var_0454 = Q32_EqualsApprox              (0, 0);
	t_bool               var_0455 = Q64_EqualsApprox              (0, 0);
	t_q16                var_0456 = Q16_Add                       (0, 0);
	t_q32                var_0457 = Q32_Add                       (0, 0);
	t_q64                var_0458 = Q64_Add                       (0, 0);
	t_q16                var_0459 = Q16_Sub                       (0, 0);
	t_q32                var_0460 = Q32_Sub                       (0, 0);
	t_q64                var_0461 = Q64_Sub                       (0, 0);
	t_q16                var_0462 = Q16_Mul                       (0, 0);
	t_q32                var_0463 = Q32_Mul                       (0, 0);
	t_q64                var_0464 = Q64_Mul                       (0, 0);
	t_q16                var_0465 = Q16_Div                       (0, 0);
	t_q32                var_0466 = Q32_Div                       (0, 0);
	t_q64                var_0467 = Q64_Div                       (0, 0);
	t_q16                var_0468 = Q16_Mod                       (0, 0);
	t_q32                var_0469 = Q32_Mod                       (0, 0);
	t_q64                var_0470 = Q64_Mod                       (0, 0);
	t_q16                var_0471 = Q16_Pow                       (0, 0);
	t_q32                var_0472 = Q32_Pow                       (0, 0);
	t_q64                var_0473 = Q64_Pow                       (0, 0);
	t_q16                var_0474 = Q16_IntPow                    (0, 0);
	t_q32                var_0475 = Q32_IntPow                    (0, 0);
	t_q64                var_0476 = Q64_IntPow                    (0, 0);
	t_q16                var_0477 = Q16_Root2                     (0);
	t_q32                var_0478 = Q32_Root2                     (0);
	t_q64                var_0479 = Q64_Root2                     (0);
	t_q16                var_0480 = Q16_Root3                     (0);
	t_q32                var_0481 = Q32_Root3                     (0);
	t_q64                var_0482 = Q64_Root3                     (0);
	t_q16                var_0483 = Q16_RootN                     (0, 0);
	t_q32                var_0484 = Q32_RootN                     (0, 0);
	t_q64                var_0485 = Q64_RootN                     (0, 0);
	t_q16                var_0486 = Q16_Exp                       (0);
	t_q32                var_0487 = Q32_Exp                       (0);
	t_q64                var_0488 = Q64_Exp                       (0);
	t_q16                var_0489 = Q16_Ln                        (0);
	t_q32                var_0490 = Q32_Ln                        (0);
	t_q64                var_0491 = Q64_Ln                        (0);
	t_q16                var_0492 = Q16_Log2                      (0);
	t_q32                var_0493 = Q32_Log2                      (0);
	t_q64                var_0494 = Q64_Log2                      (0);
	t_q16                var_0495 = Q16_Log10                     (0);
	t_q32                var_0496 = Q32_Log10                     (0);
	t_q64                var_0497 = Q64_Log10                     (0);
	t_q16                var_0498 = Q16_LogN                      (0, 0);
	t_q32                var_0499 = Q32_LogN                      (0, 0);
	t_q64                var_0500 = Q64_LogN                      (0, 0);
	t_q16                var_0501 = Q16_Cos                       (0);
	t_q32                var_0502 = Q32_Cos                       (0);
	t_q64                var_0503 = Q64_Cos                       (0);
	t_q16                var_0504 = Q16_Sin                       (0);
	t_q32                var_0505 = Q32_Sin                       (0);
	t_q64                var_0506 = Q64_Sin                       (0);
	t_q16                var_0507 = Q16_Tan                       (0);
	t_q32                var_0508 = Q32_Tan                       (0);
	t_q64                var_0509 = Q64_Tan                       (0);
	t_q16                var_0510 = Q16_ArcCos                    (0);
	t_q32                var_0511 = Q32_ArcCos                    (0);
	t_q64                var_0512 = Q64_ArcCos                    (0);
	t_q16                var_0513 = Q16_ArcSin                    (0);
	t_q32                var_0514 = Q32_ArcSin                    (0);
	t_q64                var_0515 = Q64_ArcSin                    (0);
	t_q16                var_0516 = Q16_ArcTan                    (0);
	t_q32                var_0517 = Q32_ArcTan                    (0);
	t_q64                var_0518 = Q64_ArcTan                    (0);
	t_q16                var_0519 = Q16_                          (0, 0);
	t_q32                var_0520 = Q32_                          (0, 0);
	t_q64                var_0521 = Q64_                          (0, 0);
	t_q16                var_0522 = Q16_CosH                      (0);
	t_q32                var_0523 = Q32_CosH                      (0);
	t_q64                var_0524 = Q64_CosH                      (0);
	t_q16                var_0525 = Q16_SinH                      (0);
	t_q32                var_0526 = Q32_SinH                      (0);
	t_q64                var_0527 = Q64_SinH                      (0);
	t_q16                var_0528 = Q16_TanH                      (0);
	t_q32                var_0529 = Q32_TanH                      (0);
	t_q64                var_0530 = Q64_TanH                      (0);
	t_q16                var_0531 = Q16_InvCosH                   (0);
	t_q32                var_0532 = Q32_InvCosH                   (0);
	t_q64                var_0533 = Q64_InvCosH                   (0);
	t_q16                var_0534 = Q16_InvSinH                   (0);
	t_q32                var_0535 = Q32_InvSinH                   (0);
	t_q64                var_0536 = Q64_InvSinH                   (0);
	t_q16                var_0537 = Q16_InvTanH                   (0);
	t_q32                var_0538 = Q32_InvTanH                   (0);
	t_q64                var_0539 = Q64_InvTanH                   (0);
	t_f32                var_0540 = F32_Abs                       (0);
	t_f64                var_0541 = F64_Abs                       (0);
	t_f32                var_0542 = F32_Round                     (0);
	t_f64                var_0543 = F64_Round                     (0);
	t_f32                var_0544 = F32_Trunc                     (0);
	t_f64                var_0545 = F64_Trunc                     (0);
	t_f32                var_0546 = F32_Floor                     (0);
	t_f64                var_0547 = F64_Floor                     (0);
	t_f32                var_0548 = F32_Ceil                      (0);
	t_f64                var_0549 = F64_Ceil                      (0);
	t_bool               var_0550 = F32_Equals                    (0, 0);
	t_bool               var_0551 = F64_Equals                    (0, 0);
	t_bool               var_0552 = F32_EqualsApprox              (0, 0);
	t_bool               var_0553 = F64_EqualsApprox              (0, 0);
	t_f32                var_0554 = F32_Add                       (0, 0);
	t_f64                var_0555 = F64_Add                       (0, 0);
	t_f32                var_0556 = F32_Sub                       (0, 0);
	t_f64                var_0557 = F64_Sub                       (0, 0);
	t_f32                var_0558 = F32_Mul                       (0, 0);
	t_f64                var_0559 = F64_Mul                       (0, 0);
	t_f32                var_0560 = F32_Div                       (0, 0);
	t_f64                var_0561 = F64_Div                       (0, 0);
	t_f32                var_0562 = F32_Mod                       (0, 0);
	t_f64                var_0563 = F64_Mod                       (0, 0);
	t_f32                var_0564 = F32_Pow                       (0, 0);
	t_f64                var_0565 = F64_Pow                       (0, 0);
	t_f32                var_0566 = F32_IntPow                    (0, 0);
	t_f64                var_0567 = F64_IntPow                    (0, 0);
	t_f32                var_0568 = F32_Root2                     (0);
	t_f64                var_0569 = F64_Root2                     (0);
	t_f32                var_0570 = F32_Root3                     (0);
	t_f64                var_0571 = F64_Root3                     (0);
	t_f32                var_0572 = F32_RootN                     (0, 0);
	t_f64                var_0573 = F64_RootN                     (0, 0);
	t_f32                var_0574 = F32_Exp                       (0);
	t_f64                var_0575 = F64_Exp                       (0);
	t_f32                var_0576 = F32_Ln                        (0);
	t_f64                var_0577 = F64_Ln                        (0);
	t_f32                var_0578 = F32_Log2                      (0);
	t_f64                var_0579 = F64_Log2                      (0);
	t_f32                var_0580 = F32_Log10                     (0);
	t_f64                var_0581 = F64_Log10                     (0);
	t_f32                var_0582 = F32_LogN                      (0, 0);
	t_f64                var_0583 = F64_LogN                      (0, 0);
	t_f32                var_0584 = F32_Cos                       (0);
	t_f64                var_0585 = F64_Cos                       (0);
	t_f32                var_0586 = F32_Sin                       (0);
	t_f64                var_0587 = F64_Sin                       (0);
	t_f32                var_0588 = F32_Tan                       (0);
	t_f64                var_0589 = F64_Tan                       (0);
	t_f32                var_0590 = F32_ArcCos                    (0);
	t_f64                var_0591 = F64_ArcCos                    (0);
	t_f32                var_0592 = F32_ArcSin                    (0);
	t_f64                var_0593 = F64_ArcSin                    (0);
	t_f32                var_0594 = F32_ArcTan                    (0);
	t_f64                var_0595 = F64_ArcTan                    (0);
	t_f32                var_0596 = F32_ArcTan2                   (0, 0);
	t_f64                var_0597 = F64_ArcTan2                   (0, 0);
	t_f32                var_0598 = F32_CosH                      (0);
	t_f64                var_0599 = F64_CosH                      (0);
	t_f32                var_0600 = F32_SinH                      (0);
	t_f64                var_0601 = F64_SinH                      (0);
	t_f32                var_0602 = F32_TanH                      (0);
	t_f64                var_0603 = F64_TanH                      (0);
	t_f32                var_0604 = F32_InvCosH                   (0);
	t_f64                var_0605 = F64_InvCosH                   (0);
	t_f32                var_0606 = F32_InvSinH                   (0);
	t_f64                var_0607 = F64_InvSinH                   (0);
	t_f32                var_0608 = F32_InvTanH                   (0);
	t_f64                var_0609 = F64_InvTanH                   (0);
	t_s8                 var_0610 = S8_Abs                        (0);
	t_s16                var_0611 = S16_Abs                       (0);
	t_s32                var_0612 = S32_Abs                       (0);
	t_s64                var_0613 = S64_Abs                       (0);
	t_bool               var_0614 = S8_Equals                     (0, 0);
	t_bool               var_0615 = S16_Equals                    (0, 0);
	t_bool               var_0616 = S32_Equals                    (0, 0);
	t_bool               var_0617 = S64_Equals                    (0, 0);
	t_bool               var_0618 = S8_EqualsApprox               (0, 0);
	t_bool               var_0619 = S16_EqualsApprox              (0, 0);
	t_bool               var_0620 = S32_EqualsApprox              (0, 0);
	t_bool               var_0621 = S64_EqualsApprox              (0, 0);
	t_u8                 var_0622 = U8_Add                        (0, 0);
	t_u16                var_0623 = U16_Add                       (0, 0);
	t_u32                var_0624 = U32_Add                       (0, 0);
	t_u64                var_0625 = U64_Add                       (0, 0);
	t_s8                 var_0626 = S8_Add                        (0, 0);
	t_s16                var_0627 = S16_Add                       (0, 0);
	t_s32                var_0628 = S32_Add                       (0, 0);
	t_s64                var_0629 = S64_Add                       (0, 0);
	t_u8                 var_0630 = U8_Sub                        (0, 0);
	t_u16                var_0631 = U16_Sub                       (0, 0);
	t_u32                var_0632 = U32_Sub                       (0, 0);
	t_u64                var_0633 = U64_Sub                       (0, 0);
	t_s8                 var_0634 = S8_Sub                        (0, 0);
	t_s16                var_0635 = S16_Sub                       (0, 0);
	t_s32                var_0636 = S32_Sub                       (0, 0);
	t_s64                var_0637 = S64_Sub                       (0, 0);
	t_u8                 var_0638 = U8_Mul                        (0, 0);
	t_u16                var_0639 = U16_Mul                       (0, 0);
	t_u32                var_0640 = U32_Mul                       (0, 0);
	t_u64                var_0641 = U64_Mul                       (0, 0);
	t_s8                 var_0642 = S8_Mul                        (0, 0);
	t_s16                var_0643 = S16_Mul                       (0, 0);
	t_s32                var_0644 = S32_Mul                       (0, 0);
	t_s64                var_0645 = S64_Mul                       (0, 0);
	t_u8                 var_0646 = U8_Div                        (0, 0);
	t_u16                var_0647 = U16_Div                       (0, 0);
	t_u32                var_0648 = U32_Div                       (0, 0);
	t_u64                var_0649 = U64_Div                       (0, 0);
	t_s8                 var_0650 = S8_Div                        (0, 0);
	t_s16                var_0651 = S16_Div                       (0, 0);
	t_s32                var_0652 = S32_Div                       (0, 0);
	t_s64                var_0653 = S64_Div                       (0, 0);
	t_u8                 var_0654 = U8_Mod                        (0, 0);
	t_u16                var_0655 = U16_Mod                       (0, 0);
	t_u32                var_0656 = U32_Mod                       (0, 0);
	t_u64                var_0657 = U64_Mod                       (0, 0);
	t_s8                 var_0658 = S8_Mod                        (0, 0);
	t_s16                var_0659 = S16_Mod                       (0, 0);
	t_s32                var_0660 = S32_Mod                       (0, 0);
	t_s64                var_0661 = S64_Mod                       (0, 0);
	t_u8                 var_0662 = U8_Pow                        (0, 0);
	t_u16                var_0663 = U16_Pow                       (0, 0);
	t_u32                var_0664 = U32_Pow                       (0, 0);
	t_u64                var_0665 = U64_Pow                       (0, 0);
	t_s8                 var_0666 = S8_Pow                        (0, 0);
	t_s16                var_0667 = S16_Pow                       (0, 0);
	t_s32                var_0668 = S32_Pow                       (0, 0);
	t_s64                var_0669 = S64_Pow                       (0, 0);
	t_u8                 var_0670 = U8_Root2                      (0);
	t_u16                var_0671 = U16_Root2                     (0);
	t_u32                var_0672 = U32_Root2                     (0);
	t_u64                var_0673 = U64_Root2                     (0);
	t_s8                 var_0674 = S8_Root2                      (0);
	t_s16                var_0675 = S16_Root2                     (0);
	t_s32                var_0676 = S32_Root2                     (0);
	t_s64                var_0677 = S64_Root2                     (0);
	s_array_int          var_0678 = Stat_Int_NewList              (0);
	                                Stat_Int_FreeList             (NULL);
	s_array_int          var_0680 = Stat_Int_MergeList            (NULL, NULL);
	s_array_int          var_0681 = Stat_Int_Quicksort            ((s_array_int){0});
	                                Stat_Int_Quicksort_InPlace    ((s_array_int){0});
	t_float              var_0683 = Stat_Int_Median               ((s_sorted_int){0});
	t_float              var_0684 = Stat_Int_Average              ((s_array_int){0});
	t_float              var_0685 = Stat_Int_Variance             ((s_array_int){0});
	t_float              var_0686 = Stat_Int_StandardDeviation    ((s_array_int){0});
	                                Stat_Int_Decile               ((s_array_int){0});
	s_array_float        var_0688 = Stat_Float_NewList            (0);
	                                Stat_Float_FreeList           (NULL);
	s_array_float        var_0690 = Stat_Float_MergeList          (NULL, NULL);
	s_array_float        var_0691 = Stat_Float_Quicksort          ((s_array_float){0});
	                                Stat_Float_Quicksort_InPlace  ((s_array_float){0});
	t_float              var_0693 = Stat_Float_Median             ((s_sorted_float){0});
	t_float              var_0694 = Stat_Float_Average            ((s_array_float){0});
	t_float              var_0695 = Stat_Float_Variance           ((s_array_float){0});
	t_float              var_0696 = Stat_Float_StandardDeviation  ((s_array_float){0});
	                                Stat_Float_Decile             ((s_array_float){0});
	s_prob_mass          var_0698 = Stat_NewPMF                   (0);
	                                Stat_FreePMF                  (NULL);
	s_array_int          var_0700 = Stat_IntList_To_Set           ((s_array_int){0});
	t_uint               var_0701 = Stat_IntList_Count            ((s_array_int){0}, 0);
	s_prob_mass          var_0702 = Stat_IntList_To_PMF           ((s_array_int){0});
	void*                var_0703 = Memory_New                    (0);
	void*                var_0704 = Memory_New_C                  (0, 0);
	void*                var_0705 = Memory_Allocate               (0);
	void*                var_0706 = Memory_Reallocate             (NULL, 0);
	                                Memory_Deallocate             (NULL);
	                                Memory_Delete                 (NULL);
	                                Memory_Set                    (NULL, 0, 0);
	                                Memory_Clear                  (NULL, 0);
	void*                var_0711 = Memory_Copy                   (NULL, NULL, 0);
	void*                var_0712 = Memory_Copy_C                 (NULL, NULL, 0, 0);
	void*                var_0713 = Memory_Move                   (NULL, NULL, 0);
	void*                var_0714 = Memory_Duplicate              (NULL, 0);
	void*                var_0715 = Memory_Join                   (NULL, 0, NULL, 0);
	void*                var_0716 = Memory_Append                 (NULL, 0, NULL, 0);
	void*                var_0717 = Memory_Prepend                (NULL, 0, NULL, 0);
	void*                var_0718 = Memory_Merge                  (NULL, 0, NULL, 0);
	void*                var_0719 = Memory_Find                   (NULL, 0, 0);
	                                Memory_Replace                (NULL, 0, 0, 0);
	t_sint               var_0721 = Memory_Compare                (NULL, NULL, 0);
	t_bool               var_0722 = Memory_Equals                 (NULL, NULL, 0);
	t_size               var_0723 = Memory_Print                  (NULL, NULL, 0);
	t_char*              var_0724 = Memory_ToString               (NULL, 0);
	t_uintmax            var_0725 = Memory_GetBits                (NULL, 0, 0);
	                                Memory_SetBits                (NULL, 0, 0, 0);
	t_uintmax            var_0727 = Memory_BitRegion              (0, 0, 0);
	t_u8                 var_0728 = Memory_CountBits              (0);
	t_s8                 var_0729 = Memory_GetMostSignificantBit  (0);
	t_s8                 var_0730 = Memory_GetLeastSignificantBit (0);
	s_array(any)         var_0731 = Array_Item(any)               (NULL);
	void**               var_0732 = Array_Get(any)                (NULL, 0);
	void**               var_0733 = Array_Set(any)                (NULL, 0, NULL);
	s_array(any)*        var_0734 = Array_New(any)                (NULL, NULL);
	s_array(any)*        var_0735 = Array_Create(any)             (NULL);
	s_array(any)*        var_0736 = Array_Duplicate(any)          (NULL);
	s_array(any)*        var_0737 = Array_Sub(any)                (NULL, 0, 0);
	s_array(any)*        var_0738 = Array_Copy(any)               (NULL, 0, NULL, 0, 0);
	                                Array_Free(any)               (NULL);
	                                Array_Free_F(any)             (NULL, NULL);
	                                Array_Delete(any)             (NULL);
	                                Array_Delete_F(any)           (NULL, NULL);
	s_array(any)*        var_0743 = Array_Add(any)                (NULL, NULL);
	s_array(any)*        var_0744 = Array_Insert(any)             (NULL, NULL, 0);
	s_array(any)*        var_0745 = Array_Wedge(any)              (NULL, NULL, 0);
	                                Array_RemoveAt(any)           (NULL, 0);
	                                Array_RemoveAt_F(any)         (NULL, 0, NULL);
	                                Array_Remove(any)             (NULL, NULL);
	                                Array_Remove_F(any)           (NULL, NULL, NULL);
	                                Array_RemoveAll(any)          (NULL, NULL);
	                                Array_RemoveAll_F(any)        (NULL, NULL, NULL);
	s_array(any)*        var_0752 = Array_Replace(any)            (NULL, NULL, NULL);
	s_array(any)*        var_0753 = Array_ReplaceFirst(any)       (NULL, NULL, NULL, 0);
	s_array(any)*        var_0754 = Array_ReplaceLast(any)        (NULL, NULL, NULL, 0);
	s_array(any)*        var_0755 = Array_Reverse(any)            (NULL);
	s_array(any)*        var_0756 = Array_Concat(any)             (NULL, NULL);
	s_array(any)*        var_0757 = Array_Append(any)             (NULL, NULL);
	s_array(any)*        var_0758 = Array_Prepend(any)            (NULL, NULL);
	s_array(any)*        var_0759 = Array_Merge(any)              (NULL, NULL);
	t_bool               var_0760 = Array_Equals(any)             (NULL, NULL);
	t_bool               var_0761 = Array_Equals_N(any)           (NULL, NULL, 0);
	t_sint               var_0762 = Array_Compare(any)            (NULL, NULL, NULL);
	t_sint               var_0763 = Array_Compare_N(any)          (NULL, NULL, NULL, 0);
	void**               var_0764 = Array_Find(any)               (NULL, NULL);
	void**               var_0765 = Array_Find_F(any)             (NULL, NULL);
	t_sint               var_0766 = Array_IndexOf(any)            (NULL, NULL);
	t_sint               var_0767 = Array_IndexOf_F(any)          (NULL, NULL);
	t_uint               var_0768 = Array_Count(any)              (NULL, NULL);
	t_bool               var_0769 = Array_Contains(any)           (NULL, NULL);
	t_bool               var_0770 = Array_Has(any)                (NULL, NULL);
	t_bool               var_0771 = Array_HasOnly(any)            (NULL, NULL);
	                                Array_Iterate(any)            (NULL, NULL);
	                                Array_Iterate_I(any)          (NULL, NULL);
	s_array(any)*        var_0774 = Array_Map(any)                (NULL, NULL);
	s_array(any)*        var_0775 = Array_Map_I(any)              (NULL, NULL);
	s_array(any)*        var_0776 = Array_Filter(any)             (NULL, NULL);
	s_array(any)*        var_0777 = Array_Filter_I(any)           (NULL, NULL);
	void*                var_0778 = Array_Reduce(any)             (NULL, NULL);
	void*                var_0779 = Array_Reduce_I(any)           (NULL, NULL);
	void*                var_0780 = Array_Fold(any)               (NULL, NULL, NULL);
	void*                var_0781 = Array_Fold_I(any)             (NULL, NULL, NULL);
	s_array(any)*        var_0782 = List_ToArray                  (NULL);
	void**               var_0783 = List_ToPointerArray           (NULL);
	s_list(any)*         var_0784 = List_Item(any)                (NULL);
	t_uint               var_0785 = List_Length(any)              (NULL);
	void**               var_0786 = List_Get(any)                 (NULL, 0);
	void**               var_0787 = List_Set(any)                 (NULL, 0, NULL);
	s_list(any)*         var_0788 = List_New(any)                 (NULL, NULL);
	s_list(any)*         var_0789 = List_Create(any)              (NULL);
	s_list(any)*         var_0790 = List_Duplicate(any)           (NULL);
	s_list(any)*         var_0791 = List_Sub(any)                 (NULL, 0, 0);
	s_list(any)*         var_0792 = List_Copy(any)                (NULL, 0, NULL, 0, 0);
	                                List_Free(any)                (NULL);
	                                List_Free_F(any)              (NULL, NULL);
	                                List_Delete(any)              (NULL);
	                                List_Delete_F(any)            (NULL, NULL);
	s_list(any)*         var_0797 = List_Add(any)                 (NULL, NULL);
	s_list(any)*         var_0798 = List_Insert(any)              (NULL, NULL, 0);
	s_list(any)*         var_0799 = List_Wedge(any)               (NULL, NULL, 0);
	s_list(any)*         var_0800 = List_RemoveAt(any)            (NULL, 0);
	s_list(any)*         var_0801 = List_RemoveAt_F(any)          (NULL, 0, NULL);
	s_list(any)*         var_0802 = List_Remove(any)              (NULL, NULL);
	s_list(any)*         var_0803 = List_Remove_F(any)            (NULL, NULL, NULL);
	s_list(any)*         var_0804 = List_RemoveAll(any)           (NULL, NULL);
	s_list(any)*         var_0805 = List_RemoveAll_F(any)         (NULL, NULL, NULL);
	s_list(any)*         var_0806 = List_Replace(any)             (NULL, NULL, NULL);
	s_list(any)*         var_0807 = List_ReplaceFirst(any)        (NULL, NULL, NULL, 0);
	s_list(any)*         var_0808 = List_ReplaceLast(any)         (NULL, NULL, NULL, 0);
	s_list(any)*         var_0809 = List_Reverse(any)             (NULL);
	s_list(any)*         var_0810 = List_Concat(any)              (NULL, NULL);
	s_list(any)*         var_0811 = List_Append(any)              (NULL, NULL);
	s_list(any)*         var_0812 = List_Prepend(any)             (NULL, NULL);
	s_list(any)*         var_0813 = List_Merge(any)               (NULL, NULL);
	t_bool               var_0814 = List_Equals(any)              (NULL, NULL);
	t_bool               var_0815 = List_Equals_N(any)            (NULL, NULL, 0);
	t_sint               var_0816 = List_Compare(any)             (NULL, NULL, NULL);
	t_sint               var_0817 = List_Compare_N(any)           (NULL, NULL, NULL, 0);
	s_list(any) const*   var_0818 = List_Find(any)                (NULL, NULL);
	s_list(any) const*   var_0819 = List_Find_F(any)              (NULL, NULL);
	t_sint               var_0820 = List_IndexOf(any)             (NULL, NULL);
	t_sint               var_0821 = List_IndexOf_F(any)           (NULL, NULL);
	t_uint               var_0822 = List_Count(any)               (NULL, NULL);
	t_bool               var_0823 = List_Contains(any)            (NULL, NULL);
	t_bool               var_0824 = List_Has(any)                 (NULL, NULL);
	t_bool               var_0825 = List_HasOnly(any)             (NULL, NULL);
	                                List_Iterate(any)             (NULL, NULL);
	                                List_Iterate_I(any)           (NULL, NULL);
	s_list(any)*         var_0828 = List_Map(any)                 (NULL, NULL);
	s_list(any)*         var_0829 = List_Map_I(any)               (NULL, NULL);
	s_list(any)*         var_0830 = List_Filter(any)              (NULL, NULL);
	s_list(any)*         var_0831 = List_Filter_I(any)            (NULL, NULL);
	void*                var_0832 = List_Reduce(any)              (NULL, NULL);
	void*                var_0833 = List_Reduce_I(any)            (NULL, NULL);
	void*                var_0834 = List_Fold(any)                (NULL, NULL, NULL);
	void*                var_0835 = List_Fold_I(any)              (NULL, NULL, NULL);
	t_char*              var_0836 = Size_ToString                 (0);
	t_char*              var_0837 = Size_ToString_Hex             (0);
	t_char*              var_0838 = Size_ToString_Pretty          (0);
	t_char*              var_0839 = Pointer_ToString              (NULL);
	t_char*              var_0840 = Pointer_ToString_Hex          (NULL);
	t_size               var_0841 = Size_Parse                    (NULL, NULL);
	t_size               var_0842 = Size_FromString               (NULL);
	t_size               var_0843 = PtrDiff_Parse                 (NULL, NULL);
	t_ptrdiff            var_0844 = PtrDiff_FromString            (NULL);
	t_size               var_0845 = UIntMax_Parse                 (NULL, NULL);
	t_uintmax            var_0846 = UIntMax_FromString            (NULL);
	t_size               var_0847 = SIntMax_Parse                 (NULL, NULL);
	t_sintmax            var_0848 = SIntMax_FromString            (NULL);
	t_size               var_0849 = UIntPtr_Parse                 (NULL, NULL);
	t_uintptr            var_0850 = UIntPtr_FromString            (NULL);
	t_size               var_0851 = SIntPtr_Parse                 (NULL, NULL);
	t_sintptr            var_0852 = SIntPtr_FromString            (NULL);
	t_uint               var_0853 = PointerArray_Length           (NULL);
	void**               var_0854 = PointerArray_New              (0, NULL);
	void**               var_0855 = PointerArray_Create           (0);
	void**               var_0856 = PointerArray_Duplicate        (NULL);
	void**               var_0857 = PointerArray_Sub              (NULL, 0, 0);
	void**               var_0858 = PointerArray_Copy             (NULL, 0, NULL, 0, 0);
	                                PointerArray_Free             (NULL);
	                                PointerArray_Free_F           (NULL, NULL);
	                                PointerArray_Delete           (NULL);
	                                PointerArray_Delete_F         (NULL, NULL);
	void**               var_0863 = PointerArray_Add              (NULL, NULL);
	void**               var_0864 = PointerArray_Insert           (NULL, NULL, 0);
	void**               var_0865 = PointerArray_Wedge            (NULL, NULL, 0);
	                                PointerArray_RemoveAt         (NULL, 0);
	                                PointerArray_RemoveAt_F       (NULL, 0, NULL);
	                                PointerArray_Remove           (NULL, NULL);
	                                PointerArray_Remove_F         (NULL, NULL, NULL);
	                                PointerArray_RemoveAll        (NULL, NULL);
	                                PointerArray_RemoveAll_F      (NULL, NULL, NULL);
	void**               var_0872 = PointerArray_Replace          (NULL, NULL, NULL);
	void**               var_0873 = PointerArray_ReplaceFirst     (NULL, NULL, NULL, 0);
	void**               var_0874 = PointerArray_ReplaceLast      (NULL, NULL, NULL, 0);
	void**               var_0875 = PointerArray_Reverse          (NULL);
	void**               var_0876 = PointerArray_Concat           (NULL, NULL);
	void**               var_0877 = PointerArray_Append           (NULL, NULL);
	void**               var_0878 = PointerArray_Prepend          (NULL, NULL);
	void**               var_0879 = PointerArray_Merge            (NULL, NULL);
	void**               var_0880 = PointerArray_Join             (NULL, NULL);
	t_bool               var_0881 = PointerArray_Equals           (NULL, NULL);
	t_bool               var_0882 = PointerArray_Equals_N         (NULL, NULL, 0);
	t_sint               var_0883 = PointerArray_Compare          (NULL, NULL, NULL);
	t_sint               var_0884 = PointerArray_Compare_N        (NULL, NULL, NULL, 0);
	void* const*         var_0885 = PointerArray_Find             (NULL, NULL);
	void* const*         var_0886 = PointerArray_Find_F           (NULL, NULL);
	t_sint               var_0887 = PointerArray_IndexOf          (NULL, NULL);
	t_sint               var_0888 = PointerArray_IndexOf_F        (NULL, NULL);
	t_uint               var_0889 = PointerArray_Count            (NULL, NULL);
	t_bool               var_0890 = PointerArray_Contains         (NULL, NULL);
	t_bool               var_0891 = PointerArray_Has              (NULL, NULL);
	t_bool               var_0892 = PointerArray_HasOnly          (NULL, NULL);
	                                PointerArray_Iterate          (NULL, NULL);
	                                PointerArray_Iterate_I        (NULL, NULL);
	void**               var_0895 = PointerArray_Map              (NULL, NULL);
	void**               var_0896 = PointerArray_Map_I            (NULL, NULL);
	void**               var_0897 = PointerArray_Filter           (NULL, NULL);
	void**               var_0898 = PointerArray_Filter_I         (NULL, NULL);
	void*                var_0899 = PointerArray_Reduce           (NULL, NULL);
	void*                var_0900 = PointerArray_Reduce_I         (NULL, NULL);
	void*                var_0901 = PointerArray_Fold             (NULL, NULL, NULL);
	void*                var_0902 = PointerArray_Fold_I           (NULL, NULL, NULL);
	t_csprng*            var_0903 = CSPRNG_New                    ();
	                                CSPRNG_Delete                 (NULL);
	e_cccerror           var_0905 = CSPRNG_Next                   (NULL, NULL, 0);
	t_uint               var_0906 = CSPRNG_UInt                   (NULL);
	t_uint               var_0907 = CSPRNG_UInt_Range             (NULL, 0, 0);
	t_sint               var_0908 = CSPRNG_SInt                   (NULL);
	t_sint               var_0909 = CSPRNG_SInt_Range             (NULL, 0, 0);
	t_fixed              var_0910 = CSPRNG_Fixed                  (NULL);
	t_fixed              var_0911 = CSPRNG_Fixed_Range            (NULL, 0, 0);
	t_float              var_0912 = CSPRNG_Float                  (NULL);
	t_float              var_0913 = CSPRNG_Float_Range            (NULL, 0, 0);
	void*                var_0914 = CSPRNG_Get                    (NULL, 0);
	t_uint               var_0915 = CSPRNG_UInt_Get               ();
	t_uint               var_0916 = CSPRNG_UInt_Get_Range         (0, 0);
	t_sint               var_0917 = CSPRNG_SInt_Get               ();
	t_sint               var_0918 = CSPRNG_SInt_Get_Range         (0, 0);
	t_fixed              var_0919 = CSPRNG_Fixed_Get              ();
	t_fixed              var_0920 = CSPRNG_Fixed_Get_Range        (0, 0);
	t_float              var_0921 = CSPRNG_Float_Get              ();
	t_float              var_0922 = CSPRNG_Float_Get_Range        (0, 0);
	                                PRNG_SetSeed                  (NULL, 0);
	                                PRNG_NewSeed                  (NULL);
	t_prng*              var_0925 = PRNG_New                      ();
	                                PRNG_Delete                   (NULL);
	e_cccerror           var_0927 = PRNG_Next                     (NULL, NULL, 0);
	t_uint               var_0928 = PRNG_UInt                     (NULL);
	t_uint               var_0929 = PRNG_UInt_Range               (NULL, 0, 0);
	t_sint               var_0930 = PRNG_SInt                     (NULL);
	t_sint               var_0931 = PRNG_SInt_Range               (NULL, 0, 0);
	t_fixed              var_0932 = PRNG_Fixed                    (NULL);
	t_fixed              var_0933 = PRNG_Fixed_Range              (NULL, 0, 0);
	t_float              var_0934 = PRNG_Float                    (NULL);
	t_float              var_0935 = PRNG_Float_Range              (NULL, 0, 0);
	void*                var_0936 = PRNG_Get                      (NULL, 0);
	t_uint               var_0937 = PRNG_UInt_Get                 ();
	t_uint               var_0938 = PRNG_UInt_Get_Range           (0, 0);
	t_sint               var_0939 = PRNG_SInt_Get                 ();
	t_sint               var_0940 = PRNG_SInt_Get_Range           (0, 0);
	t_fixed              var_0941 = PRNG_Fixed_Get                ();
	t_fixed              var_0942 = PRNG_Fixed_Get_Range          (0, 0);
	t_float              var_0943 = PRNG_Float_Get                ();
	t_float              var_0944 = PRNG_Float_Get_Range          (0, 0);
	t_char*              var_0945 = String_New                    (0);
	t_char*              var_0946 = String_New_C                  (0, 0);
	                                String_Free                   (NULL);
	                                String_Delete                 (NULL);
	t_char*              var_0949 = String_Duplicate              (NULL);
	t_char*              var_0950 = String_Duplicate_N            (NULL, 0);
	t_char*              var_0951 = String_Duplicate_Char         (NULL, 0);
	t_char*              var_0952 = String_Duplicate_Charset      (NULL, NULL);
	t_char*              var_0953 = String_Duplicate_String       (NULL, NULL);
	                                String_Clear                  (NULL);
	                                String_Set                    (NULL, 0);
	t_char*              var_0956 = String_Copy                   (NULL, NULL);
	t_char*              var_0957 = String_Copy_N                 (NULL, NULL, 0);
	t_size               var_0958 = String_Copy_L                 (NULL, NULL, 0);
	t_char*              var_0959 = String_Add                    (NULL, NULL);
	t_char*              var_0960 = String_Add_N                  (NULL, NULL, 0);
	t_size               var_0961 = String_Add_L                  (NULL, NULL, 0);
	t_size               var_0962 = String_Length                 (NULL);
	t_bool               var_0963 = String_Equals                 (NULL, NULL);
	t_bool               var_0964 = String_Equals_N               (NULL, NULL, 0);
	t_bool               var_0965 = String_Equals_IgnoreCase      (NULL, NULL);
	t_bool               var_0966 = String_Equals_N_IgnoreCase    (NULL, NULL, 0);
	t_sint               var_0967 = String_Compare                (NULL, NULL);
	t_sint               var_0968 = String_Compare_N              (NULL, NULL, 0);
	t_sint               var_0969 = String_Compare_IgnoreCase     (NULL, NULL);
	t_sint               var_0970 = String_Compare_N_IgnoreCase   (NULL, NULL, 0);
	t_bool               var_0971 = String_Has                    (NULL, NULL);
	t_bool               var_0972 = String_HasOnly                (NULL, NULL);
	t_size               var_0973 = String_Count_Char             (NULL, 0);
	t_size               var_0974 = String_Count_Charset          (NULL, NULL);
	t_size               var_0975 = String_Count_String           (NULL, NULL);
	t_char*              var_0976 = String_Find_Char              (NULL, 0);
	t_char*              var_0977 = String_Find_Charset           (NULL, NULL);
	t_char*              var_0978 = String_Find_String            (NULL, NULL);
	t_char*              var_0979 = String_Find_R_Char            (NULL, 0);
	t_char*              var_0980 = String_Find_R_Charset         (NULL, NULL);
	t_char*              var_0981 = String_Find_R_String          (NULL, NULL);
	t_char*              var_0982 = String_Find_N_Char            (NULL, 0, 0);
	t_char*              var_0983 = String_Find_N_Charset         (NULL, NULL, 0);
	t_char*              var_0984 = String_Find_N_String          (NULL, NULL, 0);
	t_sintmax            var_0985 = String_IndexOf_Char           (NULL, 0);
	t_sintmax            var_0986 = String_IndexOf_Charset        (NULL, NULL);
	t_sintmax            var_0987 = String_IndexOf_String         (NULL, NULL);
	t_sintmax            var_0988 = String_IndexOf_R_Char         (NULL, 0);
	t_sintmax            var_0989 = String_IndexOf_R_Charset      (NULL, NULL);
	t_sintmax            var_0990 = String_IndexOf_R_String       (NULL, NULL);
	t_sintmax            var_0991 = String_IndexOf_N_Char         (NULL, 0, 0);
	t_sintmax            var_0992 = String_IndexOf_N_Charset      (NULL, NULL, 0);
	t_sintmax            var_0993 = String_IndexOf_N_String       (NULL, NULL, 0);
	t_char*              var_0994 = String_Remove                 (NULL, NULL);
	t_char*              var_0995 = String_Replace_String         (NULL, NULL, NULL);
	t_char*              var_0996 = String_Concat                 (NULL, NULL);
	t_char*              var_0997 = String_Append                 (NULL, NULL);
	t_char*              var_0998 = String_Prepend                (NULL, NULL);
	t_char*              var_0999 = String_Merge                  (NULL, NULL);
	t_char*              var_1000 = String_Join                   (NULL, NULL);
	t_char*              var_1001 = String_Insert_InPlace         (NULL, NULL, 0);
	                                String_Replace_Char_InPlace   (NULL, 0, 0);
	                                String_Replace_Charset_InPlace(NULL, NULL, NULL);
	                                String_Replace_String_InPlace (NULL, NULL, NULL);
	t_char*              var_1005 = String_Map_InPlace            (NULL, NULL);
	t_char*              var_1006 = String_Trim                   (NULL, NULL);
	t_char*              var_1007 = String_Trim_L                 (NULL, NULL);
	t_char*              var_1008 = String_Trim_R                 (NULL, NULL);
	t_char*              var_1009 = String_Pad                    (NULL, 0, 0);
	t_char*              var_1010 = String_Pad_L                  (NULL, 0, 0);
	t_char*              var_1011 = String_Pad_R                  (NULL, 0, 0);
	t_size               var_1012 = String_Print                  (NULL, NULL, 0, NULL);
	t_char*              var_1013 = String_ToEscape               (NULL, NULL);
	t_size               var_1014 = String_Parse                  (NULL, NULL, 0, 0);
	t_char*              var_1015 = String_FromEscape             (NULL, 0);
	t_char*              var_1016 = String_Reverse                (NULL);
	t_char*              var_1017 = String_Insert                 (NULL, NULL, 0);
	t_char*              var_1018 = String_Sub                    (NULL, 0, 0);
	                                String_Iterate                (NULL, NULL);
	                                String_Iterate_I              (NULL, NULL);
	t_char*              var_1021 = String_Map                    (NULL, NULL);
	t_char*              var_1022 = String_Map_I                  (NULL, NULL);
	t_char**             var_1023 = String_Split_Char             (NULL, 0);
	t_char**             var_1024 = String_Split_Charset          (NULL, NULL);
	t_char**             var_1025 = String_Split_String           (NULL, NULL);
	t_char**             var_1026 = String_Divide                 (NULL, 0);
	t_uint               var_1027 = StringArray_Length            (NULL);
	t_size               var_1028 = StringArray_TotalLength       (NULL, 0);
	t_char**             var_1029 = StringArray_New               (0);
	t_char**             var_1030 = StringArray_New_C             (0, 0, 0);
	t_char**             var_1031 = StringArray_Create            (0);
	t_char**             var_1032 = StringArray_Duplicate         (NULL);
	t_char**             var_1033 = StringArray_Sub               (NULL, 0, 0);
	t_char**             var_1034 = StringArray_Copy              (NULL, 0, NULL, 0, 0);
	                                StringArray_Free              (NULL);
	                                StringArray_Delete            (NULL);
	t_char**             var_1037 = StringArray_Add               (NULL, NULL);
	t_char**             var_1038 = StringArray_Insert            (NULL, NULL, 0);
	t_char**             var_1039 = StringArray_Wedge             (NULL, NULL, 0);
	                                StringArray_RemoveAt          (NULL, 0);
	                                StringArray_RemoveAt_F        (NULL, 0, NULL);
	                                StringArray_Remove            (NULL, NULL);
	                                StringArray_Remove_F          (NULL, NULL, NULL);
	                                StringArray_RemoveAll         (NULL, NULL);
	                                StringArray_RemoveAll_F       (NULL, NULL, NULL);
	t_char**             var_1046 = StringArray_Replace           (NULL, NULL, NULL);
	t_char**             var_1047 = StringArray_ReplaceFirst      (NULL, NULL, NULL, 0);
	t_char**             var_1048 = StringArray_ReplaceLast       (NULL, NULL, NULL, 0);
	t_char**             var_1049 = StringArray_Reverse           (NULL);
	t_char**             var_1050 = StringArray_Pad_L             (NULL, 0, 0);
	t_char**             var_1051 = StringArray_Concat            (NULL, NULL);
	t_char**             var_1052 = StringArray_Append            (NULL, NULL);
	t_char**             var_1053 = StringArray_Prepend           (NULL, NULL);
	t_char**             var_1054 = StringArray_Merge             (NULL, NULL);
	t_char**             var_1055 = StringArray_Join              (NULL, NULL);
	t_bool               var_1056 = StringArray_Equals            (NULL, NULL);
	t_bool               var_1057 = StringArray_Equals_N          (NULL, NULL, 0);
	t_sint               var_1058 = StringArray_Compare           (NULL, NULL, NULL);
	t_sint               var_1059 = StringArray_Compare_N         (NULL, NULL, NULL, 0);
	t_uint               var_1060 = StringArray_Count_Char        (NULL, 0);
	t_uint               var_1061 = StringArray_Count_Charset     (NULL, NULL);
	t_uint               var_1062 = StringArray_Count_String      (NULL, NULL);
	                                StringArray_Iterate           (NULL, NULL);
	                                StringArray_Iterate_I         (NULL, NULL);
	t_char**             var_1065 = StringArray_Map               (NULL, NULL);
	t_char**             var_1066 = StringArray_Map_I             (NULL, NULL);
	t_char**             var_1067 = StringArray_Filter            (NULL, NULL);
	t_char**             var_1068 = StringArray_Filter_I          (NULL, NULL);
	void*                var_1069 = StringArray_Reduce            (NULL, NULL);
	void*                var_1070 = StringArray_Reduce_I          (NULL, NULL);
	void*                var_1071 = StringArray_Fold              (NULL, NULL, NULL);
	void*                var_1072 = StringArray_Fold_I            (NULL, NULL, NULL);
	t_u8                 var_1073 = IO_GetColor                   (0);
	t_bool               var_1074 = IO_IsTerminal                 (0);
	t_fd                 var_1075 = IO_Open                       (NULL, 0, 0);
	e_cccerror           var_1076 = IO_Close                      (0);
	e_cccerror           var_1077 = IO_ChangeMode                 (NULL, 0);
	t_io_mode            var_1078 = IO_GetMode                    (NULL);
	t_sintmax            var_1079 = IO_Read_File                  (0, NULL, 0);
	t_sintmax            var_1080 = IO_Read_Filepath              (NULL, NULL);
	char*                var_1081 = IO_Read_Filepath_Text         (NULL);
	t_sintmax            var_1082 = IO_Read_Lines                 (0, NULL);
	int                  var_1083 = IO_Read_NextLine              (0, NULL);
	t_size               var_1084 = IO_Write_Char                 (0, 0);
	t_size               var_1085 = IO_Write_String               (0, NULL);
	t_size               var_1086 = IO_Write_Data                 (0, NULL, 0);
	t_size               var_1087 = IO_Write_Line                 (0, NULL);
	t_size               var_1088 = IO_Write_Lines                (0, NULL);
	t_size               var_1089 = IO_Write_Memory               (0, NULL, 0, 0);
	t_size               var_1090 = IO_Write_Format               (0, NULL);
	t_size               var_1091 = IO_Output_Char                (0);
	t_size               var_1092 = IO_Output_String              (NULL);
	t_size               var_1093 = IO_Output_Line                (NULL);
	t_size               var_1094 = IO_Output_Lines               (NULL);
	t_size               var_1095 = IO_Output_Memory              (NULL, 0, 0);
	t_size               var_1096 = IO_Output_Format              (NULL);
	                                Logger_Init                   (NULL);
	                                Logger_Exit                   (NULL);
	                                Logger_DeleteMemory           (NULL);
	t_char*              var_1100 = Logger_GetSettings            (NULL);
	e_cccerror           var_1101 = Logger_LogSettings            (NULL);
	t_char*              var_1102 = Logger_GetTimestamp           (0);
	                                Program_Abort                 ();
	                                Program_Exit                  (0);
	e_cccerror           var_1105 = Program_OnExit                (NULL);
	int                  var_1106 = Program_Run                   (NULL);
	t_char*              var_1107 = Program_GetEnv                (NULL);
	int                  var_1108 = Program_SetEnv                (NULL, NULL, 0);
	t_char*              var_1109 = Program_GetCWD                ();
	t_time               var_1110 = Time_Now                      ();
	s_date               var_1111 = Time_ToDate_UTC               (0);
	s_date               var_1112 = Time_ToDate_LocalTime         (0);
	struct timespec      var_1113 = NanoTime_ToSTDC               (NULL);
	s_nanotime           var_1114 = NanoTime_FromSTDC             (NULL);
	s_date               var_1115 = Date_Now                      ();
	t_time               var_1116 = Date_ToTime_UTC               (NULL);
	t_time               var_1117 = Date_ToTime_LocalTime         (NULL);
	struct tm            var_1118 = Date_ToSTDC                   (NULL);
	s_date               var_1119 = Date_FromSTDC                 (NULL);
	t_size               var_1120 = Date_Parse                    (NULL, NULL, NULL);
	t_size               var_1121 = Date_Parse_Min                (NULL, NULL, NULL);
	s_date               var_1122 = Date_FromString               (NULL, NULL);
	s_date               var_1123 = Date_FromString_Min           (NULL, NULL);
	t_char*              var_1124 = Date_ToString                 (NULL, NULL);
	t_size               var_1125 = Date_ToString_N               (NULL, 0, NULL, NULL);
	t_char*              var_1126 = Date_ToString_Unix            (NULL);
	t_char*              var_1127 = DateNow_ToString_Unix         ();
	t_bool               var_1128 = Date_IsValid                  (NULL);
	                                Date_MakeValid                (NULL);
	t_uint               var_1130 = Date_DaysInMonth              (0, 0);
	e_weekday            var_1131 = Date_DayOfTheWeek             (NULL);
	t_bool               var_1132 = Date_IsLeapYear               (0);
	t_bool               var_1133 = Date_HasLeapSecond            (0, 0);
	t_bool               var_1134 = ASCII_IsLetter                (0);
	t_bool               var_1135 = ASCII_IsUppercase             (0);
	t_bool               var_1136 = ASCII_IsLowercase             (0);
	t_bool               var_1137 = ASCII_IsAlphaNumeric          (0);
	t_bool               var_1138 = ASCII_IsDigit_Decimal         (0);
	t_bool               var_1139 = ASCII_IsDigit_Hexadecimal     (0);
	t_bool               var_1140 = ASCII_IsDigit_Octal           (0);
	t_bool               var_1141 = ASCII_IsDigit_Binary          (0);
	t_bool               var_1142 = ASCII_IsWhiteSpace            (0);
	t_bool               var_1143 = ASCII_IsPunctuation           (0);
	t_bool               var_1144 = ASCII_IsPrintable             (0);
	t_bool               var_1145 = ASCII_IsValid                 (0);
	t_bool               var_1146 = ASCII_IsInCharset             (0, NULL);
	t_ascii              var_1147 = ASCII_ToUppercase             (0);
	t_ascii              var_1148 = ASCII_ToLowercase             (0);
	t_bool               var_1149 = UTF32_IsLetter                (0);
	t_bool               var_1150 = UTF32_IsUppercase             (0);
	t_bool               var_1151 = UTF32_IsLowercase             (0);
	t_bool               var_1152 = UTF32_IsAlphaNumeric          (0);
	t_bool               var_1153 = UTF32_IsDigit_Decimal         (0);
	t_bool               var_1154 = UTF32_IsDigit_Hexadecimal     (0);
	t_bool               var_1155 = UTF32_IsDigit_Octal           (0);
	t_bool               var_1156 = UTF32_IsDigit_Binary          (0);
	t_bool               var_1157 = UTF32_IsWhiteSpace            (0);
	t_bool               var_1158 = UTF32_IsPunctuation           (0);
	t_bool               var_1159 = UTF32_IsPrintable             (0);
	t_bool               var_1160 = UTF32_IsASCII                 (0);
	t_bool               var_1161 = UTF32_IsValid                 (0);
	t_bool               var_1162 = UTF32_IsInCharset             (0, NULL);
	t_utf32              var_1163 = UTF32_ToUppercase             (0);
	t_utf32              var_1164 = UTF32_ToLowercase             (0);
	t_size               var_1165 = UTF32_ToUTF8                  (NULL, 0);
	t_size               var_1166 = UTF32_ToUTF16                 (NULL, 0);
	t_utf32              var_1167 = UTF32_FromUTF8                (NULL);
	t_utf32              var_1168 = UTF32_FromUTF16               (NULL);
	t_utf32              var_1169 = UTF32_FromEscape              (NULL);
	t_size               var_1170 = UTF32_Parse                   (NULL, NULL, 0);
	t_sint               var_1171 = UTF8_ByteOrderMark            (NULL);
	t_sint               var_1172 = UTF16_ByteOrderMark           (NULL);
	t_sint               var_1173 = UTF32_ByteOrderMark           (NULL);
}
