#!/bin/sh

VERSION_FILE=VERSION

# increment the build number (3rd number of the version number)
make version-build
git add $VERSION_FILE
git commit -m "update(version): incremented version build number"
