
#include "libccc.h"
#include "libccc/fixed.h"
#include "libccc/math/fixed.h"

#include LIBCONFIG_ERROR_INCLUDE



#define DEFINEFUNC_FIXED_SUB(BITS) \
_INLINE() \
t_q##BITS	Q##BITS##_Sub(t_q##BITS a, t_q##BITS b) \
{ \
	t_s##BITS i1 = (a / FIXED_DENOMINATOR); \
	t_s##BITS i2 = (b / FIXED_DENOMINATOR); \
	if CCCERROR((i2 < 0) && (i1 > (Q##BITS##_MAX / FIXED_DENOMINATOR) + i2), ERROR_RESULTRANGE, NULL) \
	{ LIBCONFIG_ERROR_HANDLEOVERFLOW_FIXED(Q##BITS, Q##BITS##_MAX); } \
	if CCCERROR((i2 > 0) && (i1 < (Q##BITS##_MIN / FIXED_DENOMINATOR) + i2), ERROR_RESULTRANGE, NULL) \
	{ LIBCONFIG_ERROR_HANDLEOVERFLOW_FIXED(Q##BITS, Q##BITS##_MIN); } \
	return (a - b); \
} \

DEFINEFUNC_FIXED_SUB(16)
DEFINEFUNC_FIXED_SUB(32)
DEFINEFUNC_FIXED_SUB(64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_FIXED_SUB(128)
#endif
