
#include "libccc.h"
#include "libccc/fixed.h"
#include "libccc/string.h"
#include "libccc/math.h"

#include LIBCONFIG_ERROR_INCLUDE



#define DEFINEFUNC_UINT_FROMUINT(BITS, FROM) \
_INLINE() \
t_u##BITS	U##BITS##_FromU##FROM(t_u##FROM number) \
{ \
	if (U##FROM##_IsNaN(number))	return (U##BITS##_ERROR); \
	if (U##FROM##_IsInf(number))	return (U##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number >= (t_u##FROM)U##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit unsigned integer overflow for " SF_U##FROM " at " SF_U##BITS, number, U##BITS##_MAX) \
		return (U##BITS##_MAX); \
	return ((t_u##BITS)number); \
} \

DEFINEFUNC_UINT_FROMUINT(8, 8)
DEFINEFUNC_UINT_FROMUINT(8, 16)
DEFINEFUNC_UINT_FROMUINT(8, 32)
DEFINEFUNC_UINT_FROMUINT(8, 64)
DEFINEFUNC_UINT_FROMUINT(16, 8)
DEFINEFUNC_UINT_FROMUINT(16, 16)
DEFINEFUNC_UINT_FROMUINT(16, 32)
DEFINEFUNC_UINT_FROMUINT(16, 64)
DEFINEFUNC_UINT_FROMUINT(32, 8)
DEFINEFUNC_UINT_FROMUINT(32, 16)
DEFINEFUNC_UINT_FROMUINT(32, 32)
DEFINEFUNC_UINT_FROMUINT(32, 64)
DEFINEFUNC_UINT_FROMUINT(64, 8)
DEFINEFUNC_UINT_FROMUINT(64, 16)
DEFINEFUNC_UINT_FROMUINT(64, 32)
DEFINEFUNC_UINT_FROMUINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_UINT_FROMUINT(8, 128)
DEFINEFUNC_UINT_FROMUINT(16, 128)
DEFINEFUNC_UINT_FROMUINT(32, 128)
DEFINEFUNC_UINT_FROMUINT(64, 128)
DEFINEFUNC_UINT_FROMUINT(128, 8)
DEFINEFUNC_UINT_FROMUINT(128, 16)
DEFINEFUNC_UINT_FROMUINT(128, 32)
DEFINEFUNC_UINT_FROMUINT(128, 64)
DEFINEFUNC_UINT_FROMUINT(128, 128)
#endif

#define DEFINEFUNC_UINT_FROMSINT(BITS, FROM) \
_INLINE() \
t_u##BITS	U##BITS##_FromS##FROM(t_s##FROM number) \
{ \
	if (S##FROM##_IsNaN(number))	return (U##BITS##_ERROR); \
	if (number < 0)					return (U##BITS##_ERROR); \
	if (S##FROM##_IsInf(number))	return (U##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && (t_u##FROM)number >= (t_u##FROM)U##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit unsigned integer overflow for " SF_S##FROM " at " SF_U##BITS, number, U##BITS##_MAX) \
		return (U##BITS##_MAX); \
	return ((t_u##BITS)number); \
} \

DEFINEFUNC_UINT_FROMSINT(8, 8)
DEFINEFUNC_UINT_FROMSINT(8, 16)
DEFINEFUNC_UINT_FROMSINT(8, 32)
DEFINEFUNC_UINT_FROMSINT(8, 64)
DEFINEFUNC_UINT_FROMSINT(16, 8)
DEFINEFUNC_UINT_FROMSINT(16, 16)
DEFINEFUNC_UINT_FROMSINT(16, 32)
DEFINEFUNC_UINT_FROMSINT(16, 64)
DEFINEFUNC_UINT_FROMSINT(32, 8)
DEFINEFUNC_UINT_FROMSINT(32, 16)
DEFINEFUNC_UINT_FROMSINT(32, 32)
DEFINEFUNC_UINT_FROMSINT(32, 64)
DEFINEFUNC_UINT_FROMSINT(64, 8)
DEFINEFUNC_UINT_FROMSINT(64, 16)
DEFINEFUNC_UINT_FROMSINT(64, 32)
DEFINEFUNC_UINT_FROMSINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_UINT_FROMSINT(8, 128)
DEFINEFUNC_UINT_FROMSINT(16, 128)
DEFINEFUNC_UINT_FROMSINT(32, 128)
DEFINEFUNC_UINT_FROMSINT(64, 128)
DEFINEFUNC_UINT_FROMSINT(128, 8)
DEFINEFUNC_UINT_FROMSINT(128, 16)
DEFINEFUNC_UINT_FROMSINT(128, 32)
DEFINEFUNC_UINT_FROMSINT(128, 64)
DEFINEFUNC_UINT_FROMSINT(128, 128)
#endif

#define DEFINEFUNC_UINT_FROMFIXED(BITS, FROM) \
_INLINE() \
t_u##BITS	U##BITS##_FromQ##FROM(t_q##FROM number) \
{ \
	if (Q##FROM##_IsNaN(number))	return (U##BITS##_ERROR); \
	if (number._ < 0)				return (U##BITS##_ERROR); \
	if (Q##FROM##_IsInf(number))	return (U##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && (number._ / Q##FROM##_DENOM) > (t_s##FROM)U##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit unsigned integer overflow for " SF_Q##FROM " at " SF_U##BITS, number._, U##BITS##_MAX) \
		return (U##BITS##_MAX); \
	return ((t_u##BITS)(number._ / Q##BITS##_DENOM)); \
} \

DEFINEFUNC_UINT_FROMFIXED(8, 8)
DEFINEFUNC_UINT_FROMFIXED(8, 16)
DEFINEFUNC_UINT_FROMFIXED(8, 32)
DEFINEFUNC_UINT_FROMFIXED(8, 64)
DEFINEFUNC_UINT_FROMFIXED(16, 8)
DEFINEFUNC_UINT_FROMFIXED(16, 16)
DEFINEFUNC_UINT_FROMFIXED(16, 32)
DEFINEFUNC_UINT_FROMFIXED(16, 64)
DEFINEFUNC_UINT_FROMFIXED(32, 8)
DEFINEFUNC_UINT_FROMFIXED(32, 16)
DEFINEFUNC_UINT_FROMFIXED(32, 32)
DEFINEFUNC_UINT_FROMFIXED(32, 64)
DEFINEFUNC_UINT_FROMFIXED(64, 8)
DEFINEFUNC_UINT_FROMFIXED(64, 16)
DEFINEFUNC_UINT_FROMFIXED(64, 32)
DEFINEFUNC_UINT_FROMFIXED(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_UINT_FROMFIXED(8, 128)
DEFINEFUNC_UINT_FROMFIXED(16, 128)
DEFINEFUNC_UINT_FROMFIXED(32, 128)
DEFINEFUNC_UINT_FROMFIXED(64, 128)
DEFINEFUNC_UINT_FROMFIXED(128, 8)
DEFINEFUNC_UINT_FROMFIXED(128, 16)
DEFINEFUNC_UINT_FROMFIXED(128, 32)
DEFINEFUNC_UINT_FROMFIXED(128, 64)
DEFINEFUNC_UINT_FROMFIXED(128, 128)
#endif

#define DEFINEFUNC_UINT_FROMFLOAT(BITS, FROM) \
_INLINE() \
t_u##BITS	U##BITS##_FromF##FROM(t_f##FROM number) \
{ \
	if (F##FROM##_IsNaN(number))	return (U##BITS##_ERROR); \
	if (number < 0.)				return (U##BITS##_ERROR); \
	if (F##FROM##_IsInf(number))	return (U##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number > (t_f##FROM)U##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit unsigned integer overflow for " SF_F##FROM " at " SF_U##BITS, number, U##BITS##_MAX) \
		return (U##BITS##_MAX); \
	return ((t_u##BITS)number); \
} \

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_UINT_FROMFLOAT(8, 16)
#endif
DEFINEFUNC_UINT_FROMFLOAT(8, 32)
DEFINEFUNC_UINT_FROMFLOAT(8, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_UINT_FROMFLOAT(8, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_UINT_FROMFLOAT(8, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_UINT_FROMFLOAT(16, 16)
#endif
DEFINEFUNC_UINT_FROMFLOAT(16, 32)
DEFINEFUNC_UINT_FROMFLOAT(16, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_UINT_FROMFLOAT(16, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_UINT_FROMFLOAT(16, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_UINT_FROMFLOAT(32, 16)
#endif
DEFINEFUNC_UINT_FROMFLOAT(32, 32)
DEFINEFUNC_UINT_FROMFLOAT(32, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_UINT_FROMFLOAT(32, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_UINT_FROMFLOAT(32, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_UINT_FROMFLOAT(64, 16)
#endif
DEFINEFUNC_UINT_FROMFLOAT(64, 32)
DEFINEFUNC_UINT_FROMFLOAT(64, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_UINT_FROMFLOAT(64, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_UINT_FROMFLOAT(64, 128)
#endif

#if LIBCONFIG_USE_INT128
#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_UINT_FROMFLOAT(128, 16)
#endif
DEFINEFUNC_UINT_FROMFLOAT(128, 32)
DEFINEFUNC_UINT_FROMFLOAT(128, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_UINT_FROMFLOAT(128, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_UINT_FROMFLOAT(128, 128)
#endif
#endif




#define DEFINEFUNC_SINT_FROMUINT(BITS, FROM) \
_INLINE() \
t_s##BITS	S##BITS##_FromU##FROM(t_u##FROM number) \
{ \
	if (U##FROM##_IsNaN(number))	return (S##BITS##_ERROR); \
	if (U##FROM##_IsInf(number))	return (S##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number >= (t_u##FROM)S##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer positive overflow for " SF_U##FROM " at " SF_S##BITS, number, S##BITS##_MAX) \
		return (S##BITS##_MAX); \
	return ((t_s##BITS)number); \
} \

DEFINEFUNC_SINT_FROMUINT(8, 8)
DEFINEFUNC_SINT_FROMUINT(8, 16)
DEFINEFUNC_SINT_FROMUINT(8, 32)
DEFINEFUNC_SINT_FROMUINT(8, 64)
DEFINEFUNC_SINT_FROMUINT(16, 8)
DEFINEFUNC_SINT_FROMUINT(16, 16)
DEFINEFUNC_SINT_FROMUINT(16, 32)
DEFINEFUNC_SINT_FROMUINT(16, 64)
DEFINEFUNC_SINT_FROMUINT(32, 8)
DEFINEFUNC_SINT_FROMUINT(32, 16)
DEFINEFUNC_SINT_FROMUINT(32, 32)
DEFINEFUNC_SINT_FROMUINT(32, 64)
DEFINEFUNC_SINT_FROMUINT(64, 8)
DEFINEFUNC_SINT_FROMUINT(64, 16)
DEFINEFUNC_SINT_FROMUINT(64, 32)
DEFINEFUNC_SINT_FROMUINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_SINT_FROMUINT(8, 128)
DEFINEFUNC_SINT_FROMUINT(16, 128)
DEFINEFUNC_SINT_FROMUINT(32, 128)
DEFINEFUNC_SINT_FROMUINT(64, 128)
DEFINEFUNC_SINT_FROMUINT(128, 8)
DEFINEFUNC_SINT_FROMUINT(128, 16)
DEFINEFUNC_SINT_FROMUINT(128, 32)
DEFINEFUNC_SINT_FROMUINT(128, 64)
DEFINEFUNC_SINT_FROMUINT(128, 128)
#endif

#define DEFINEFUNC_SINT_FROMSINT(BITS, FROM) \
_INLINE() \
t_s##BITS	S##BITS##_FromS##FROM(t_s##FROM number) \
{ \
	if (S##FROM##_IsNaN(number))	return (S##BITS##_ERROR); \
	if (S##FROM##_IsInf(number))	return (S##BITS##_MAX * (t_s##BITS)S##FROM##_Sgn(number)); \
	if CCCERROR((FROM >= BITS && number >= (t_s##FROM)S##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer positive overflow for " SF_S##FROM " at " SF_S##BITS, number, S##BITS##_MAX) \
		return (S##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && number <= (t_s##FROM)S##BITS##_MIN), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer negative overflow for " SF_S##FROM " at " SF_S##BITS, number, S##BITS##_MIN) \
		return (S##BITS##_MIN); \
	return ((t_s##BITS)number); \
} \

DEFINEFUNC_SINT_FROMSINT(8, 8)
DEFINEFUNC_SINT_FROMSINT(8, 16)
DEFINEFUNC_SINT_FROMSINT(8, 32)
DEFINEFUNC_SINT_FROMSINT(8, 64)
DEFINEFUNC_SINT_FROMSINT(16, 8)
DEFINEFUNC_SINT_FROMSINT(16, 16)
DEFINEFUNC_SINT_FROMSINT(16, 32)
DEFINEFUNC_SINT_FROMSINT(16, 64)
DEFINEFUNC_SINT_FROMSINT(32, 8)
DEFINEFUNC_SINT_FROMSINT(32, 16)
DEFINEFUNC_SINT_FROMSINT(32, 32)
DEFINEFUNC_SINT_FROMSINT(32, 64)
DEFINEFUNC_SINT_FROMSINT(64, 8)
DEFINEFUNC_SINT_FROMSINT(64, 16)
DEFINEFUNC_SINT_FROMSINT(64, 32)
DEFINEFUNC_SINT_FROMSINT(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_SINT_FROMSINT(8, 128)
DEFINEFUNC_SINT_FROMSINT(16, 128)
DEFINEFUNC_SINT_FROMSINT(32, 128)
DEFINEFUNC_SINT_FROMSINT(64, 128)
DEFINEFUNC_SINT_FROMSINT(128, 8)
DEFINEFUNC_SINT_FROMSINT(128, 16)
DEFINEFUNC_SINT_FROMSINT(128, 32)
DEFINEFUNC_SINT_FROMSINT(128, 64)
DEFINEFUNC_SINT_FROMSINT(128, 128)
#endif

#define DEFINEFUNC_SINT_FROMFIXED(BITS, FROM) \
_INLINE() \
t_s##BITS	S##BITS##_FromQ##FROM(t_q##FROM number) \
{ \
	if (Q##FROM##_IsNaN(number))	return (S##BITS##_ERROR); \
	if (Q##FROM##_IsInf(number))	return (S##BITS##_MAX * (t_s##BITS)S##FROM##_Sgn(number._)); \
	if CCCERROR((FROM >= BITS && (number._ / Q##FROM##_DENOM) >= (t_s##FROM)S##BITS##_MAX), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer positive overflow for " SF_Q##FROM " at " SF_S##BITS, number._, S##BITS##_MAX) \
		return (S##BITS##_MAX); \
	if CCCERROR((FROM >= BITS && (number._ / Q##FROM##_DENOM) <= (t_s##FROM)S##BITS##_MIN), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer negative overflow for " SF_Q##FROM " at " SF_S##BITS, number._, S##BITS##_MIN) \
		return (S##BITS##_MIN); \
	return ((t_s##BITS)(number._ / Q##BITS##_DENOM)); \
} \

DEFINEFUNC_SINT_FROMFIXED(8, 16)
DEFINEFUNC_SINT_FROMFIXED(8, 32)
DEFINEFUNC_SINT_FROMFIXED(8, 64)
DEFINEFUNC_SINT_FROMFIXED(16, 16)
DEFINEFUNC_SINT_FROMFIXED(16, 32)
DEFINEFUNC_SINT_FROMFIXED(16, 64)
DEFINEFUNC_SINT_FROMFIXED(32, 16)
DEFINEFUNC_SINT_FROMFIXED(32, 32)
DEFINEFUNC_SINT_FROMFIXED(32, 64)
DEFINEFUNC_SINT_FROMFIXED(64, 16)
DEFINEFUNC_SINT_FROMFIXED(64, 32)
DEFINEFUNC_SINT_FROMFIXED(64, 64)
#if LIBCONFIG_USE_INT128
DEFINEFUNC_SINT_FROMFIXED(8, 128)
DEFINEFUNC_SINT_FROMFIXED(16, 128)
DEFINEFUNC_SINT_FROMFIXED(32, 128)
DEFINEFUNC_SINT_FROMFIXED(64, 128)
DEFINEFUNC_SINT_FROMFIXED(128, 16)
DEFINEFUNC_SINT_FROMFIXED(128, 32)
DEFINEFUNC_SINT_FROMFIXED(128, 64)
DEFINEFUNC_SINT_FROMFIXED(128, 128)
#endif

#define DEFINEFUNC_SINT_FROMFLOAT(BITS, FROM) \
_INLINE() \
t_s##BITS	S##BITS##_FromF##FROM(t_f##FROM number) \
{ \
	if (F##FROM##_IsNaN(number))	return (S##BITS##_ERROR); \
	if (F##FROM##_IsInf(number))	return (S##BITS##_MAX * (t_s##BITS)F##FROM##_Sgn(number)); \
	if CCCERROR((number > F##FROM##_FromS##BITS(S##BITS##_MAX_VAL)), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer positive overflow for " SF_F##FROM " at " SF_S##BITS, number, S##BITS##_MIN) \
		return (S##BITS##_MAX); \
	if CCCERROR((number < F##FROM##_FromS##BITS(S##BITS##_MIN_VAL)), ERROR_RESULTRANGE, \
		#BITS"-bit signed integer negative overflow for " SF_F##FROM " at " SF_S##BITS, number, S##BITS##_MIN) \
		return (S##BITS##_MIN); \
	return ((t_s##BITS)number); \
} \

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_SINT_FROMFLOAT(8, 16)
#endif
DEFINEFUNC_SINT_FROMFLOAT(8, 32)
DEFINEFUNC_SINT_FROMFLOAT(8, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_SINT_FROMFLOAT(8, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_SINT_FROMFLOAT(8, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_SINT_FROMFLOAT(16, 16)
#endif
DEFINEFUNC_SINT_FROMFLOAT(16, 32)
DEFINEFUNC_SINT_FROMFLOAT(16, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_SINT_FROMFLOAT(16, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_SINT_FROMFLOAT(16, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_SINT_FROMFLOAT(32, 16)
#endif
DEFINEFUNC_SINT_FROMFLOAT(32, 32)
DEFINEFUNC_SINT_FROMFLOAT(32, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_SINT_FROMFLOAT(32, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_SINT_FROMFLOAT(32, 128)
#endif

#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_SINT_FROMFLOAT(64, 16)
#endif
DEFINEFUNC_SINT_FROMFLOAT(64, 32)
DEFINEFUNC_SINT_FROMFLOAT(64, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_SINT_FROMFLOAT(64, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_SINT_FROMFLOAT(64, 128)
#endif

#if LIBCONFIG_USE_INT128
#if LIBCONFIG_USE_FLOAT16
DEFINEFUNC_SINT_FROMFLOAT(128, 16)
#endif
DEFINEFUNC_SINT_FROMFLOAT(128, 32)
DEFINEFUNC_SINT_FROMFLOAT(128, 64)
#if LIBCONFIG_USE_FLOAT80
DEFINEFUNC_SINT_FROMFLOAT(128, 80)
#endif
#if LIBCONFIG_USE_FLOAT128
DEFINEFUNC_SINT_FROMFLOAT(128, 128)
#endif
#endif
