name: CI - Tests

on:
  workflow_run:
    workflows: ["CI - Build"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        compiler: [gcc, clang]

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2



    - name: Get C# binding build artifacts
      uses: actions/download-artifact@v2
      with:
        name: libccc-build_${{matrix.os}}_${{matrix.compiler}}

    - name: Get C# binding tests artifacts
      uses: actions/download-artifact@v2
      with:
        name: libccc-tests_${{matrix.os}}_${{matrix.compiler}}



    - name: Test - simple "Hello World" (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make test-helloworld

    - name: Test - libccc test suite (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make test ARGS="-a"

    - name: Test - monads & foreach (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make test-foreach



#    - name: Release (with ${{matrix.compiler}}, for ${{matrix.os}})
#      run: make clean ; make build-release CC=${{matrix.compiler}}

# TODO: automate release tag for github ?
