name: libft CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        compiler: [gcc, clang]

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    if: ${{ !(matrix.compiler == 'clang' && matrix.os == 'windows-latest') }}
    steps:
    - uses: actions/checkout@v2
    - name: make (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make CC=${{matrix.compiler}}
