name: libft CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: prep (windows-latest, MinGW)
      if: ${{ matrix.os == 'windows-latest' }}
      run: Set-Alias -Name i686-w64-mingw32-gcc -Value gcc
    - name: make (${{ matrix.os }})
      run: make
