name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        compiler: [gcc, clang]

    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - uses: actions/checkout@v2

    - name: Add clang path to $PATH env
      if: runner.os == 'Windows'
      run: echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

    - name: make (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make CC=${{matrix.compiler}}

    - name: test (with ${{matrix.compiler}}, for ${{matrix.os}})
      run: make test CC=${{matrix.compiler}}
