name: libft CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        compiler: [gcc, clang]

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: make (with ${{matrix.compiler}}, for ${{matrix.os}})
      if: "!(${{ matrix.compiler }} == clang && ${{matrix.os}} == windows-latest)"
      run: make CC=${{matrix.compiler}}
